import Link from "next/link";
import { AdminShell } from "@/components/admin-shell";
import { requireComunAdmin } from "@/lib/admin-auth";
import {
  collectiveForwardingStateLabels,
  collectiveForwardingStates,
  nextCollectiveAdministrativeStep,
} from "@/lib/collective-actions-admin";
import {
  collectiveActionStatusLabels,
  collectiveActionTypes,
  listAdminCollectiveActions,
  listCollectiveActionCommunities,
} from "@/lib/collective-actions";
import { listAdminPautaSpaces } from "@/lib/pauta-spaces";
import { getCollectiveActionsRelease } from "@/lib/collective-actions-release";
import { isCollectiveActionsPreviewFixturesEnabled } from "@/lib/collective-actions-release-contract";
import { collectiveActionsPreviewFixtures } from "@/lib/collective-actions-preview-fixtures";
import {
  addCollectiveActionMemoryAsset,
  completeCollectiveAction,
  createCollectiveAction,
  createCollectiveActionTask,
  linkCollectiveActionSidewalkRecord,
  moveCollectiveActionToAwaitingResult,
  publishCollectiveAction,
  publishCollectiveActionMemory,
  publishCollectiveActionUpdate,
  recordCollectiveActionResult,
  saveCollectiveActionForwarding,
  startCollectiveAction,
  updateCollectiveAction,
  updateCollectiveActionTask,
} from "./actions";

export const dynamic = "force-dynamic";

export default async function AdminCollectiveActionsPage() {
  if (isCollectiveActionsPreviewFixturesEnabled()) return <CollectiveActionsPreviewAdmin />;
  const session = await requireComunAdmin({ roles: ["admin", "editor"] });
  if (!(await getCollectiveActionsRelease()).enabled)
    return <AdminShell adminEmail={session.admin.email}><h1 className="text-3xl font-black uppercase">Ações coletivas</h1><p role="status" className="mt-5 border-l-4 border-comun-yellow bg-white p-5">As Ações Coletivas estão sendo preparadas no COMUN.</p></AdminShell>;
  const [actions, communities, pautas] = await Promise.all([
    listAdminCollectiveActions(),
    listCollectiveActionCommunities(),
    listAdminPautaSpaces(),
  ]);
  return <AdminShell adminEmail={session.admin.email}>
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase text-comun-asphalt/65">Caderno coletivo em andamento</p><h1 className="mt-1 text-3xl font-black uppercase">Ações coletivas</h1><p className="mt-2 max-w-3xl text-sm text-comun-asphalt/75">Objetivo, passos, encaminhamento, resultado e memória. A área administra somente informações revisadas para publicação.</p></div><Link href="/comun/acoes" className="min-h-11 border-2 border-comun-black bg-white px-3 py-2 text-sm font-black uppercase">Ver ações públicas</Link></header>
    <form action={createCollectiveAction} className="mt-6 grid gap-3 border-2 border-comun-black bg-white p-4 md:grid-cols-2">
      <h2 className="text-xl font-black uppercase md:col-span-2">Criar caderno de ação</h2>
      <Input name="title" label="Título" required /><Input name="slug" label="Slug opcional" />
      <Select name="action_type" label="Tipo" values={collectiveActionTypes} /><Select name="status" label="Estado inicial" values={["draft", "preparing"]} />
      <Select name="visibility" label="Visibilidade" values={["internal", "community"]} /><Select name="participation_mode" label="Participação" values={["hybrid", "remote", "in_person"]} />
      <label className="grid gap-1 text-sm font-black uppercase">Pauta relacionada<select name="pauta_id" className="min-h-11 border-2 border-comun-black px-3"><option value="">Sem pauta</option>{pautas.map((pauta: any) => <option key={pauta.id} value={pauta.id}>{pauta.title}</option>)}</select></label>
      <label className="grid gap-1 text-sm font-black uppercase">Comunidade relacionada<select name="community_id" className="min-h-11 border-2 border-comun-black px-3"><option value="">Sem comunidade</option>{communities.map((community: any) => <option key={community.id} value={community.id}>{community.name}</option>)}</select></label>
      <Input name="territory_label" label="Território" /><Input name="meeting_place" label="Local de encontro" />
      <Input name="starts_at" label="Começa em" type="datetime-local" /><Input name="ends_at" label="Termina em" type="datetime-local" />
      <Textarea name="summary" label="Resumo público revisado" required /><Textarea name="objective" label="Objetivo" required />
      <button className="min-h-11 border-2 border-comun-black bg-comun-yellow font-black uppercase md:col-span-2">Criar ação</button>
    </form>
    <div className="mt-7 grid gap-5">{actions.map((action: any) => <ActionAdminCard key={action.id} action={action} />)}</div>
  </AdminShell>;
}

function CollectiveActionsPreviewAdmin() {
  return <main className="min-h-screen bg-comun-paper p-5 text-comun-black"><p className="text-xs font-black uppercase">Preview sintético · sem banco</p><h1 className="mt-2 text-3xl font-black uppercase">Caderno administrativo de ações</h1><p className="mt-3 max-w-3xl">Demonstração visual: fluxos, encaminhamentos e memória são somente sintéticos e não permitem escrita.</p><div className="mt-6 grid gap-4">{collectiveActionsPreviewFixtures.map((action: any) => <article key={action.id} className="border-2 border-comun-black bg-white p-4"><p className="text-xs font-black uppercase">{collectiveActionStatusLabels[action.status as keyof typeof collectiveActionStatusLabels]} · fixture</p><h2 className="mt-2 text-xl font-black uppercase">{action.title}</h2><p className="mt-2">Próximo passo: {action.admin_next_step}</p><div className="mt-3 grid gap-2 text-sm"><p>Tarefas: {action.tasks.length}</p><p>Atualizações: {action.updates.length}</p>{action.forwarding ? <p>Encaminhamento: {collectiveForwardingStateLabels[action.forwarding.state as keyof typeof collectiveForwardingStateLabels]}</p> : null}{action.result_summary ? <p>Resultado revisado</p> : null}{action.memory_summary ? <p>Memória final preservada</p> : null}</div><button disabled className="mt-4 min-h-11 border-2 border-comun-black px-3 py-2 font-black uppercase opacity-60">Edição indisponível no Preview</button></article>)}</div></main>;
}

function ActionAdminCard({ action }: { action: any }) {
  const nextStep = nextCollectiveAdministrativeStep(action);
  const canPublish = action.visibility !== "public" || !["open", "active", "awaiting_result", "completed"].includes(action.status);
  return <article className="border-2 border-comun-black bg-white p-4">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase text-comun-asphalt/65">{collectiveActionStatusLabels[action.status as keyof typeof collectiveActionStatusLabels]} · {action.action_type.replaceAll("_", " ")}</p><h2 className="mt-1 text-2xl font-black uppercase">{action.title}</h2><p className="mt-2 max-w-3xl text-sm text-comun-asphalt/75">{action.summary}</p></div><div className="max-w-sm border-l-4 border-comun-yellow bg-comun-paper p-3 text-sm"><strong className="uppercase">Próximo passo</strong><p className="mt-1">{nextStep}</p></div></header>
    <div className="mt-4 flex flex-wrap gap-2 text-sm font-bold"><span>{action.participantCount} participantes agregadas</span><span>{action.tasks.length} tarefas</span><span>{action.updates.length} atualizações</span>{action.forwarding ? <span>{collectiveForwardingStateLabels[action.forwarding.state as keyof typeof collectiveForwardingStateLabels]}</span> : null}</div>
    <div className="mt-4 flex flex-wrap gap-2 border-y border-comun-black/20 py-3">{canPublish ? <ActionButton action={publishCollectiveAction} id={action.id} label="Publicar" /> : null}{["open", "active"].includes(action.status) ? <ActionButton action={startCollectiveAction} id={action.id} label="Iniciar ação" /> : null}{["open", "active"].includes(action.status) ? <ActionButton action={moveCollectiveActionToAwaitingResult} id={action.id} label="Aguardar resultado" /> : null}<Link href={`/comun/acoes/${action.slug}`} className="min-h-11 border-2 border-comun-black px-3 py-2 text-sm font-black uppercase">Abrir página pública</Link></div>
    <details className="mt-4" open><summary className="cursor-pointer font-black uppercase">Identidade da ação</summary><form action={updateCollectiveAction} className="mt-3 grid gap-2 md:grid-cols-3"><input type="hidden" name="action_id" value={action.id} /><Input name="title" label="Título" defaultValue={action.title} required /><Select name="action_type" label="Tipo" values={collectiveActionTypes} defaultValue={action.action_type} /><Input name="territory_label" label="Território" defaultValue={action.territory_label ?? ""} /><Input name="meeting_place" label="Local" defaultValue={action.meeting_place ?? ""} /><Input name="starts_at" label="Começa" type="datetime-local" defaultValue={dateInputValue(action.starts_at)} /><Input name="ends_at" label="Termina" type="datetime-local" defaultValue={dateInputValue(action.ends_at)} /><Select name="participation_mode" label="Participação" values={["hybrid", "remote", "in_person"]} defaultValue={action.participation_mode} /><Textarea name="summary" label="Resumo público" defaultValue={action.summary} required /><Textarea name="objective" label="Objetivo" defaultValue={action.objective} required /><button className="min-h-11 border-2 border-comun-black p-2 text-sm font-black uppercase md:col-span-3">Salvar edição</button></form></details>
    <section className="mt-5 border-t-2 border-comun-black pt-4"><h3 className="font-black uppercase">Tarefas distribuídas</h3><div className="mt-3 grid gap-3 lg:grid-cols-2">{action.tasks.map((task: any) => <form action={updateCollectiveActionTask} key={task.id} className="grid gap-2 border border-comun-black/30 p-3 md:grid-cols-2"><input type="hidden" name="action_id" value={action.id}/><input type="hidden" name="task_id" value={task.id}/><Input name="title" label="Tarefa" defaultValue={task.title} required/><Select name="state" label="Estado" values={["draft", "open", "in_progress", "done", "cancelled", "archived"]} defaultValue={task.state}/><Textarea name="description" label="Como ajudar" defaultValue={task.description} required/><Input name="desired_count" label="Pessoas desejadas" type="number" defaultValue={String(task.desired_count)} required/><Input name="due_at" label="Prazo" type="datetime-local" defaultValue={dateInputValue(task.due_at)}/><Select name="effort_level" label="Esforço" values={["small", "medium", "collective"]} defaultValue={task.effort_level}/><Select name="participation_mode" label="Modo" values={["hybrid", "remote", "in_person"]} defaultValue={task.participation_mode}/><button className="min-h-11 border-2 border-comun-black p-2 text-sm font-black uppercase md:col-span-2">Salvar tarefa</button></form>)}</div><form action={createCollectiveActionTask} className="mt-3 grid gap-2 border-2 border-comun-black bg-comun-paper p-3 md:grid-cols-3"><input type="hidden" name="action_id" value={action.id}/><Input name="title" label="Nova tarefa" required/><Input name="desired_count" label="Pessoas" type="number" defaultValue="1" required/><Input name="due_at" label="Prazo" type="datetime-local"/><Textarea name="description" label="Como ajudar" required/><Select name="effort_level" label="Esforço" values={["small", "medium", "collective"]}/><Select name="participation_mode" label="Modo" values={["hybrid", "remote", "in_person"]}/><button className="min-h-11 border-2 border-comun-black bg-comun-yellow p-2 text-sm font-black uppercase md:col-span-3">Abrir tarefa</button></form></section>
    <section className="mt-5 border-t-2 border-comun-black pt-4"><h3 className="font-black uppercase">Linha do tempo pública</h3><ol className="mt-3 grid gap-2 border-l-2 border-comun-yellow pl-4">{action.updates.map((update: any) => <li key={update.id}><p className="text-xs font-black uppercase">{update.event_key?.replaceAll("_", " ") ?? update.update_type} · {new Date(update.occurred_at).toLocaleDateString("pt-BR")}</p><p className="font-bold">{update.title}</p><p className="text-sm text-comun-asphalt/75">{update.public_summary}</p></li>)}</ol><form action={publishCollectiveActionUpdate} className="mt-3 grid gap-2 border-2 border-comun-black p-3 md:grid-cols-3"><input type="hidden" name="action_id" value={action.id}/><Select name="update_type" label="Tipo" values={["announcement", "progress", "meeting"]}/><Input name="title" label="Título" required/><Input name="occurred_at" label="Data" type="datetime-local"/><Textarea name="public_summary" label="Resumo público revisado" required/><button className="min-h-11 border-2 border-comun-black bg-comun-yellow p-2 text-sm font-black uppercase md:col-span-3">Publicar atualização</button></form></section>
    {action.action_type === "collective_forwarding" ? <ForwardingWorkspace action={action} /> : null}
    <section className="mt-5 grid gap-4 border-t-2 border-comun-black pt-4 lg:grid-cols-2"><form action={recordCollectiveActionResult} className="grid gap-2 border-2 border-comun-black p-3"><input type="hidden" name="action_id" value={action.id}/><h3 className="font-black uppercase">Resultado</h3><Select name="result_status" label="Situação" values={["achieved", "partial", "not_achieved"]} defaultValue={action.result_status ?? "partial"}/><Textarea name="result_summary" label="Resultado público revisado" defaultValue={action.result_summary ?? ""} required/><button disabled={action.status !== "awaiting_result"} className="min-h-11 border-2 border-comun-black bg-comun-yellow p-2 text-sm font-black uppercase disabled:opacity-50">Registrar resultado</button>{action.status === "awaiting_result" && action.result_summary ? <ActionButton action={completeCollectiveAction} id={action.id} label="Concluir ação" /> : null}</form><form action={publishCollectiveActionMemory} className="grid gap-2 border-2 border-comun-black p-3"><input type="hidden" name="action_id" value={action.id}/><h3 className="font-black uppercase">Memória final</h3><Textarea name="memory_summary" label="Memória" defaultValue={action.memory_summary ?? ""} required/><Textarea name="learned_summary" label="Aprendizados" defaultValue={action.learned_summary ?? ""} required/><Textarea name="next_steps_summary" label="Próximos desdobramentos" defaultValue={action.next_steps_summary ?? ""} required/><button disabled={action.status !== "completed"} className="min-h-11 border-2 border-comun-black bg-comun-yellow p-2 text-sm font-black uppercase disabled:opacity-50">Guardar memória</button></form></section>
    <section className="mt-5 grid gap-4 border-t-2 border-comun-black pt-4 lg:grid-cols-2"><form action={addCollectiveActionMemoryAsset} className="grid gap-2 border-2 border-comun-black p-3"><input type="hidden" name="action_id" value={action.id}/><h3 className="font-black uppercase">Material público revisado</h3><Select name="asset_kind" label="Tipo" values={["document", "photograph"]}/><Input name="title" label="Título" required/><Input name="public_url" label="URL HTTPS" required/><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="public_visible"/>Publicar após revisão</label><button disabled={action.status !== "completed"} className="min-h-11 border-2 border-comun-black p-2 text-sm font-black uppercase disabled:opacity-50">Adicionar à memória</button></form><div className="border-2 border-comun-black p-3"><h3 className="font-black uppercase">Memória publicada</h3><p className="mt-2 text-sm">{action.participant_count_aggregate ?? action.participantCount} participantes agregadas · {action.tasks_completed_aggregate ?? 0} tarefas realizadas</p>{action.memoryAssets.map((asset: any) => <p key={asset.id} className="mt-2 text-sm">{asset.public_visible ? "Público" : "Em revisão"}: {asset.title}</p>)}</div></section>
    <form action={linkCollectiveActionSidewalkRecord} className="mt-5 grid gap-2 border-t-2 border-comun-black pt-4 md:grid-cols-[1fr_auto]"><input type="hidden" name="action_id" value={action.id}/><Input name="sidewalk_record_id" label="Vincular registro de calçada por ID" required/><button className="min-h-11 self-end border-2 border-comun-black px-3 py-2 text-sm font-black uppercase">Vincular</button></form>
  </article>;
}

function ForwardingWorkspace({ action }: { action: any }) {
  const forwarding = action.forwarding ?? {};
  return <section className="mt-5 border-t-2 border-comun-black pt-4"><h3 className="font-black uppercase">Encaminhamento coletivo</h3><p className="mt-1 text-sm text-comun-asphalt/75">Somente o resumo revisado e os dados marcados como públicos aparecem fora desta área.</p><form action={saveCollectiveActionForwarding} className="mt-3 grid gap-2 border-2 border-comun-black p-3 md:grid-cols-3"><input type="hidden" name="action_id" value={action.id}/><Input name="recipient_name" label="Órgão destinatário" defaultValue={forwarding.recipient_name ?? ""}/><Select name="state" label="Estado" values={collectiveForwardingStates} defaultValue={forwarding.state ?? "preparing"}/><Input name="sent_at" label="Data de envio" type="datetime-local" defaultValue={dateInputValue(forwarding.sent_at)}/><Input name="protocol_code" label="Número do protocolo" defaultValue={forwarding.protocol_code ?? ""}/><Input name="expected_response_at" label="Prazo esperado" type="datetime-local" defaultValue={dateInputValue(forwarding.expected_response_at)}/><Input name="public_document_url" label="Documento público HTTPS" defaultValue={forwarding.public_document_url ?? ""}/><Input name="public_document_label" label="Título do documento" defaultValue={forwarding.public_document_label ?? ""}/><label className="flex items-center gap-2 self-end text-sm font-bold"><input type="checkbox" name="public_visible" defaultChecked={Boolean(forwarding.public_visible)}/>Exibir resumo revisado</label><Textarea name="public_summary" label="Resumo público revisado" defaultValue={forwarding.public_summary ?? ""}/><Textarea name="response_public" label="Resposta recebida revisada" defaultValue={forwarding.response_public ?? ""}/><button className="min-h-11 border-2 border-comun-black bg-comun-yellow p-2 text-sm font-black uppercase md:col-span-3">Salvar encaminhamento</button></form></section>;
}

function ActionButton({ action, id, label }: { action: (form: FormData) => Promise<void>; id: string; label: string }) { return <form action={action}><input type="hidden" name="action_id" value={id}/><button className="min-h-11 border-2 border-comun-black bg-comun-yellow px-3 py-2 text-sm font-black uppercase">{label}</button></form>; }
function dateInputValue(value: string | null | undefined) { return value ? new Date(value).toISOString().slice(0, 16) : ""; }
function Input({ name, label, required, type = "text", defaultValue }: { name: string; label: string; required?: boolean; type?: string; defaultValue?: string }) { return <label className="grid gap-1 text-sm font-black uppercase">{label}<input className="min-h-11 border-2 border-comun-black px-3" name={name} type={type} required={required} defaultValue={defaultValue}/></label>; }
function Select({ name, label, values, defaultValue }: { name: string; label: string; values: readonly string[]; defaultValue?: string }) { return <label className="grid gap-1 text-sm font-black uppercase">{label}<select className="min-h-11 border-2 border-comun-black px-3" name={name} defaultValue={defaultValue}>{values.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></label>; }
function Textarea({ name, label, required, defaultValue }: { name: string; label: string; required?: boolean; defaultValue?: string }) { return <label className="grid gap-1 text-sm font-black uppercase md:col-span-2">{label}<textarea className="border-2 border-comun-black p-3" name={name} required={required} defaultValue={defaultValue} rows={3}/></label>; }
