import Link from "next/link";
import { AdminShell } from "@/components/admin-shell";
import { requireComunAdmin } from "@/lib/admin-auth";
import { collectiveActionTypes, listAdminCollectiveActions, listCollectiveActionCommunities } from "@/lib/collective-actions";
import { listAdminPautaSpaces } from "@/lib/pauta-spaces";
import { completeCollectiveAction, createCollectiveAction, createCollectiveActionTask, linkCollectiveActionSidewalkRecord, publishCollectiveAction, publishCollectiveActionUpdate, updateCollectiveAction } from "./actions";
import { getCollectiveActionsRelease } from "@/lib/collective-actions-release";
import { isCollectiveActionsPreviewFixturesEnabled } from "@/lib/collective-actions-release-contract";
import { collectiveActionsPreviewFixtures } from "@/lib/collective-actions-preview-fixtures";

export const dynamic = "force-dynamic";

export default async function AdminCollectiveActionsPage() {
  if (isCollectiveActionsPreviewFixturesEnabled()) return <CollectiveActionsPreviewAdmin />;
  const session = await requireComunAdmin({ roles: ["admin", "editor"] });
  if (!(await getCollectiveActionsRelease()).enabled) return <AdminShell adminEmail={session.admin.email}><h1 className="text-3xl font-black uppercase">Ações coletivas</h1><p role="status" className="mt-5 border-l-4 border-comun-yellow bg-white p-5">As Ações Coletivas estão sendo preparadas no COMUN.</p></AdminShell>;
  const [actions, communities, pautas] = await Promise.all([listAdminCollectiveActions(), listCollectiveActionCommunities(), listAdminPautaSpaces()]);
  return <AdminShell adminEmail={session.admin.email}>
    <div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-black uppercase">Ações coletivas</h1><p className="mt-2 max-w-3xl text-sm text-comun-asphalt/75">Uma esteira de mobilização: objetivo, pessoas, tarefas, atualizações e memória — sem feed infinito.</p></div><Link href="/comun/acoes" className="border-2 border-comun-black bg-white px-3 py-2 text-sm font-black uppercase">Ver ações públicas</Link></div>
    <form action={createCollectiveAction} className="mt-6 grid gap-3 border-2 border-comun-black bg-white p-4 md:grid-cols-2">
      <h2 className="text-xl font-black uppercase md:col-span-2">Criar ação coletiva</h2>
      <Input name="title" label="Título" required /><Input name="slug" label="Slug opcional" />
      <Select name="action_type" label="Tipo" values={collectiveActionTypes} /><Select name="status" label="Estado inicial" values={["draft", "preparing", "open"]} />
      <Select name="visibility" label="Visibilidade" values={["internal", "community", "public"]} /><Select name="participation_mode" label="Participação" values={["hybrid", "remote", "in_person"]} />
      <label className="grid gap-1 text-sm font-black uppercase">Pauta relacionada<select name="pauta_id" className="min-h-11 border-2 border-comun-black px-3"><option value="">Sem pauta</option>{pautas.map((pauta: any) => <option key={pauta.id} value={pauta.id}>{pauta.title}</option>)}</select></label>
      <label className="grid gap-1 text-sm font-black uppercase">Comunidade relacionada<select name="community_id" className="min-h-11 border-2 border-comun-black px-3"><option value="">Sem comunidade</option>{communities.map((community: any) => <option key={community.id} value={community.id}>{community.name}</option>)}</select></label>
      <Input name="territory_label" label="Território" /><Input name="meeting_place" label="Local de encontro" />
      <Input name="starts_at" label="Começa em" type="datetime-local" /><Input name="ends_at" label="Termina em" type="datetime-local" />
      <Textarea name="summary" label="Resumo" required /><Textarea name="objective" label="Objetivo" required />
      <button className="min-h-11 border-2 border-comun-black bg-comun-yellow font-black uppercase md:col-span-2">Criar caderno de ação</button>
    </form>
    <div className="mt-7 grid gap-5">{actions.map((action: any) => <ActionAdminCard key={action.id} action={action} />)}</div>
  </AdminShell>;
}

function CollectiveActionsPreviewAdmin() {
  return <main className="min-h-screen bg-comun-paper p-5 text-comun-black"><p className="text-xs font-black uppercase">Preview sintético · sem banco</p><h1 className="mt-2 text-3xl font-black uppercase">Administração de ações coletivas</h1><p className="mt-3 max-w-3xl">Demonstração visual: nenhuma ação administrativa é mutável neste Preview.</p><div className="mt-6 grid gap-4">{collectiveActionsPreviewFixtures.map((action) => <article key={action.id} className="border-2 border-comun-black bg-white p-4"><p className="text-xs font-black uppercase">{action.status} · fixture</p><h2 className="mt-2 text-xl font-black uppercase">{action.title}</h2><p className="mt-2">{action.summary}</p><button disabled className="mt-4 border-2 border-comun-black px-3 py-2 font-black uppercase opacity-60">Edição indisponível no Preview</button></article>)}</div></main>;
}

function ActionAdminCard({ action }: { action: any }) {
  return <article className="border-2 border-comun-black bg-white p-4">
    <p className="text-xs font-black uppercase text-comun-asphalt/60">{action.status} · {action.visibility} · {action.action_type}</p><h2 className="mt-2 text-2xl font-black uppercase">{action.title}</h2><p className="mt-2 text-sm text-comun-asphalt/75">{action.summary}</p>
    <div className="mt-4 flex flex-wrap gap-2"><Link href={`/comun/acoes/${action.slug}`} className="border-2 border-comun-black px-3 py-2 text-sm font-black uppercase">Abrir pública</Link>{action.visibility !== "public" || !["open", "active", "awaiting_result", "completed"].includes(action.status) ? <form action={publishCollectiveAction}><input type="hidden" name="action_id" value={action.id} /><button className="border-2 border-comun-black bg-comun-yellow px-3 py-2 text-sm font-black uppercase">Publicar</button></form> : null}</div>
    <form action={updateCollectiveAction} className="mt-4 grid gap-2 border-t border-comun-black/20 pt-4 md:grid-cols-3"><input type="hidden" name="action_id" value={action.id} /><input className="border-2 border-comun-black p-2" name="title" defaultValue={action.title} required /><select className="border-2 border-comun-black p-2" name="status" defaultValue={action.status}><option value="draft">Rascunho</option><option value="preparing">Preparando</option><option value="open">Aberta</option><option value="active">Em andamento</option><option value="awaiting_result">Aguardando resultado</option><option value="cancelled">Cancelada</option><option value="archived">Arquivada</option></select><input className="border-2 border-comun-black p-2" name="territory_label" defaultValue={action.territory_label ?? ""} placeholder="Território" /><textarea className="border-2 border-comun-black p-2 md:col-span-3" name="summary" defaultValue={action.summary} required rows={2}/><textarea className="border-2 border-comun-black p-2 md:col-span-2" name="objective" defaultValue={action.objective} required rows={2}/><input className="border-2 border-comun-black p-2" name="meeting_place" defaultValue={action.meeting_place ?? ""} placeholder="Local de encontro"/><button className="border-2 border-comun-black p-2 text-sm font-black uppercase md:col-span-3">Salvar edição</button></form>
    <div className="mt-5 grid gap-3 border-t-2 border-comun-black pt-4 lg:grid-cols-3">
      <form action={createCollectiveActionTask} className="grid gap-2"><input type="hidden" name="action_id" value={action.id} /><strong className="uppercase">Nova tarefa pequena</strong><input className="border-2 border-comun-black p-2" name="title" required placeholder="Ex.: Fotografar o encontro" /><textarea className="border-2 border-comun-black p-2" name="description" required rows={2} placeholder="Como ajudar" /><input className="border-2 border-comun-black p-2" name="desired_count" type="number" min="1" defaultValue="1" /><input className="border-2 border-comun-black p-2" name="due_at" type="datetime-local" aria-label="Prazo da tarefa" /><select className="border-2 border-comun-black p-2" name="effort_level"><option value="small">Pequeno esforço</option><option value="medium">Esforço médio</option><option value="collective">Coletiva</option></select><select className="border-2 border-comun-black p-2" name="participation_mode"><option value="hybrid">Híbrida</option><option value="remote">Remota</option><option value="in_person">Presencial</option></select><button className="border-2 border-comun-black bg-comun-yellow p-2 text-sm font-black uppercase">Adicionar tarefa</button></form>
      <form action={publishCollectiveActionUpdate} className="grid gap-2"><input type="hidden" name="action_id" value={action.id} /><strong className="uppercase">Atualização na linha do tempo</strong><select className="border-2 border-comun-black p-2" name="update_type"><option value="announcement">Anúncio</option><option value="progress">Andamento</option><option value="meeting">Encontro</option><option value="protocol">Protocolo</option><option value="response">Resposta</option><option value="result">Resultado</option><option value="memory">Memória</option></select><input className="border-2 border-comun-black p-2" name="title" required placeholder="Título" /><textarea className="border-2 border-comun-black p-2" name="public_summary" required rows={2} placeholder="Atualização pública" /><button className="border-2 border-comun-black bg-comun-yellow p-2 text-sm font-black uppercase">Publicar atualização</button></form>
      <div className="grid gap-3"><form action={linkCollectiveActionSidewalkRecord} className="grid gap-2"><input type="hidden" name="action_id" value={action.id} /><strong className="uppercase">Vincular registro de calçada</strong><input className="border-2 border-comun-black p-2" name="sidewalk_record_id" required placeholder="ID do registro" /><button className="border-2 border-comun-black p-2 text-sm font-black uppercase">Vincular</button></form><form action={completeCollectiveAction} className="grid gap-2"><input type="hidden" name="action_id" value={action.id} /><strong className="uppercase">Conclusão e memória</strong><textarea className="border-2 border-comun-black p-2" name="result_summary" required rows={2} placeholder="Resultado" /><textarea className="border-2 border-comun-black p-2" name="memory_summary" required rows={2} placeholder="Aprendizados e próximos passos" /><button className="border-2 border-comun-black bg-comun-yellow p-2 text-sm font-black uppercase">Concluir e guardar memória</button></form></div>
    </div>
  </article>;
}
function Input({ name, label, required, type = "text" }: { name: string; label: string; required?: boolean; type?: string }) { return <label className="grid gap-1 text-sm font-black uppercase">{label}<input className="min-h-11 border-2 border-comun-black px-3" name={name} type={type} required={required} /></label>; }
function Select({ name, label, values }: { name: string; label: string; values: readonly string[] }) { return <label className="grid gap-1 text-sm font-black uppercase">{label}<select className="min-h-11 border-2 border-comun-black px-3" name={name}>{values.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></label>; }
function Textarea({ name, label, required }: { name: string; label: string; required?: boolean }) { return <label className="grid gap-1 text-sm font-black uppercase md:col-span-2">{label}<textarea className="border-2 border-comun-black p-3" name={name} required={required} rows={3} /></label>; }
