export const sourceMatrix = [
  row(
    "territory",
    "pauta",
    "comun_pauta_spaces.territory_id",
    "comun_hub_territories.id",
    true,
    true,
    "",
  ),
  row(
    "community",
    "pauta",
    "comun_pauta_spaces.community",
    "comun_communities.slug (is_active lookup without seed fallback)",
    true,
    "projection",
    "Texto legado sem chave estrangeira; só navegar após confirmação pública do slug.",
  ),
  row(
    "pauta",
    "contribution",
    "comun_pauta_contributions.pauta_id",
    "comun_pauta_spaces.id",
    "moderated",
    true,
    "Somente approved_public pode ser projetada publicamente.",
  ),
  row(
    "pauta",
    "decision",
    "comun_pauta_decisions.pauta_id",
    "comun_pauta_spaces.id",
    "status-dependent",
    true,
    "Decisões internas não podem entrar no contexto público.",
  ),
  row(
    "pauta",
    "action",
    "comun_mobilization_actions.pauta_id",
    "comun_pauta_spaces.id",
    "visibility=public",
    true,
    "",
  ),
  row(
    "pauta",
    "task",
    "comun_pauta_tasks.pauta_id",
    "comun_pauta_spaces.id",
    "visibility-dependent",
    true,
    "Tarefas internas permanecem fora do grafo público.",
  ),
  row(
    "action",
    "task",
    "comun_pauta_tasks.action_id",
    "comun_mobilization_actions.id",
    "visibility-dependent",
    true,
    "",
  ),
  row(
    "report",
    "protocol",
    "comun_official_protocols.report_id",
    "comun_reports.id",
    "public projection",
    true,
    "Não há FK direta pauta→protocolo em todos os fluxos.",
  ),
  row(
    "pauta",
    "result",
    "comun_hub_results.pauta_id",
    "comun_pauta_spaces.id",
    "visibility=public",
    true,
    "",
  ),
  row(
    "action",
    "result",
    "comun_hub_results.action_id",
    "comun_mobilization_actions.id",
    "visibility=public",
    true,
    "",
  ),
  row(
    "territory",
    "result",
    "comun_hub_results.territory_id",
    "comun_hub_territories.id",
    "visibility=public",
    true,
    "",
  ),
  row(
    "pauta/action/result/territory",
    "memory",
    "comun_hub_archive_links (exactly one FK)",
    "comun_archive_items.id",
    "published item only",
    true,
    "Polimorfismo é explícito na junção; não inferir por título.",
  ),
  row(
    "pauta",
    "miniapp",
    "comun_pauta_modules.pauta_id",
    "comun_pauta_spaces.id",
    "visibility=public",
    true,
    "Calçadas possui projeção própria; suas contagens não equivalem a relatos da pauta.",
  ),
  row(
    "radio_program",
    "territory/pauta",
    "territory_id / pauta_id",
    "comun_radio_programs",
    "publication_status=published",
    true,
    "Vínculos são opcionais por desenho editorial.",
  ),
  row(
    "radio_episode",
    "territory/pauta/action",
    "territory_id / pauta_id / action_id",
    "comun_radio_episodes",
    "publication_status=published",
    true,
    "Vínculos são opcionais; ausência não é inconsistência.",
  ),
  row(
    "artwork",
    "territory",
    "comun_archive_artworks.territory_id",
    "comun_hub_territories.id",
    "published archive item",
    true,
    "Obra cultural não exige pauta.",
  ),
];

export const firstWaveRoutes = [
  route("/comun/territorios", "territories", "app/comun/territorios/page.tsx", [
    "isComunAppV2",
    "ComunCollectionPage",
    "ComunEmptyStateV2",
  ]),
  route(
    "/comun/territorios/[slug]",
    "territories",
    "app/comun/territorios/[slug]/page.tsx",
    ["isComunAppV2", "ComunEntityHeader", "ComunRelationRail"],
  ),
  route("/comun/comunidades", "communities", "app/comun/comunidades/page.tsx", [
    "isComunAppV2",
    "ComunCommunityCard",
  ]),
  route("/comun/c/[slug]", "communities", "app/comun/c/[slug]/page.tsx", [
    "isComunAppV2",
    "ComunContextTrail",
    "ComunRelationRail",
  ]),
  route("/comun/pautas", "pautas", "app/comun/pautas/page.tsx", [
    "isComunAppV2",
    "ComunCollectionPage",
    "ComunPautaCard",
  ]),
  route("/comun/pautas/[slug]", "pautas", "app/comun/pautas/[slug]/page.tsx", [
    "isComunAppV2",
    "createComunEntityContext",
  ]),
  route("/comun/acoes", "actions", "app/comun/acoes/page.tsx", [
    "isComunAppV2",
    "ComunCollectionPage",
    "ComunEmptyStateV2",
  ]),
  route("/comun/acoes/[slug]", "actions", "app/comun/acoes/[slug]/page.tsx", [
    "isComunAppV2",
    "ComunEntityHeader",
    "ComunRelationRail",
  ]),
  route("/comun/resultados", "results", "app/comun/resultados/page.tsx", [
    "isComunAppV2",
    "ComunCollectionPage",
    "ComunEntityHeader",
  ]),
  route(
    "/comun/calcadas",
    "miniapps",
    "components/sidewalk-miniapp-shell.tsx",
    ["isComunAppV2", "ComunRelationRail", "data-comun-miniapp-experience"],
  ),
  route(
    "/comun/calcadas/prioridades",
    "miniapps",
    "components/sidewalk-miniapp-shell.tsx",
    ["isComunAppV2", "ComunRelationRail"],
  ),
  route(
    "/comun/calcadas/resultados",
    "miniapps",
    "components/sidewalk-miniapp-shell.tsx",
    ["isComunAppV2", "ComunRelationRail"],
  ),
  route("/comun/acervo", "archive", "app/comun/acervo/page.tsx", [
    "isComunAppV2",
    "ArchiveAppV2",
    "ComunEmptyStateV2",
  ]),
  route("/comun/acervo/[slug]", "archive", "app/comun/acervo/[slug]/page.tsx", [
    "isComunAppV2",
    "ComunEntityHeader",
    "ComunRelationRail",
  ]),
  route(
    "/comun/acervo/colecoes",
    "archive",
    "app/comun/acervo/colecoes/page.tsx",
    ["isComunAppV2", "ComunCollectionPage", "ComunEmptyStateV2"],
  ),
  route(
    "/comun/acervo/colecoes/[slug]",
    "archive",
    "app/comun/acervo/colecoes/[slug]/page.tsx",
    ["isComunAppV2", "ComunEntityHeader"],
  ),
  route(
    "/comun/acervo/identificar",
    "archive",
    "app/comun/acervo/identificar/page.tsx",
    ["isComunAppV2", "ComunCollectionPage", "ComunEmptyStateV2"],
  ),
  route(
    "/comun/acervo/identificar/[slug]",
    "archive",
    "app/comun/acervo/identificar/[slug]/page.tsx",
    ["isComunAppV2", "ComunEntityHeader", "ComunRelationRail"],
  ),
  route("/comun/acervo/arte", "art", "app/comun/acervo/arte/page.tsx", [
    "isComunAppV2",
    "ComunCollectionPage",
    "ComunEmptyStateV2",
  ]),
  route(
    "/comun/acervo/arte/[slug]",
    "art",
    "app/comun/acervo/arte/[slug]/page.tsx",
    ["isComunAppV2", "ComunEntityHeader", "ComunRelationRail"],
  ),
  route("/comun/acervo/musica", "music", "app/comun/acervo/musica/page.tsx", [
    "isComunAppV2",
    "ComunCollectionPage",
    "ComunEmptyStateV2",
  ]),
  route(
    "/comun/acervo/musica/[slug]",
    "music",
    "app/comun/acervo/musica/[slug]/page.tsx",
    ["isComunAppV2", "ComunEntityHeader", "ComunRelationRail"],
  ),
  route(
    "/comun/acervo/historias-orais",
    "oral_history",
    "app/comun/acervo/historias-orais/page.tsx",
    ["isComunAppV2", "ComunCollectionPage", "ComunEmptyStateV2"],
  ),
  route(
    "/comun/acervo/historias-orais/[slug]",
    "oral_history",
    "app/comun/acervo/historias-orais/[slug]/page.tsx",
    ["isComunAppV2", "ComunEntityHeader", "ComunRelationRail"],
  ),
  route("/comun/radio", "radio", "app/comun/radio/page.tsx", [
    "isComunAppV2",
    "ComunCollectionPage",
    "ComunEmptyStateV2",
  ]),
  route(
    "/comun/radio/episodios/[slug]",
    "radio",
    "app/comun/radio/episodios/[slug]/page.tsx",
    ["isComunAppV2", "ComunEntityHeader", "ComunRelationRail"],
  ),
  route(
    "/comun/radio/programas/[slug]",
    "radio",
    "app/comun/radio/programas/[slug]/page.tsx",
    ["isComunAppV2", "ComunEntityHeader", "ComunRelationRail"],
  ),
];

export const relationalScenarios = [
  scenario(1, "território → comunidade", "foreign_key_or_published_projection"),
  scenario(2, "território → pauta", "foreign_key"),
  scenario(3, "território → miniapp", "foreign_key"),
  scenario(4, "comunidade → pauta", "published_projection"),
  scenario(5, "pauta → território", "foreign_key"),
  scenario(6, "pauta → comunidade", "published_projection"),
  scenario(7, "pauta → ação", "foreign_key"),
  scenario(8, "ação → resultado", "foreign_key"),
  scenario(9, "resultado → pauta", "foreign_key"),
  scenario(10, "resultado → memória", "junction"),
  scenario(11, "Acervo → território", "foreign_key_or_junction"),
  scenario(12, "Rádio → pauta quando houver relação", "optional_foreign_key"),
  scenario(13, "estado vazio → próxima ação", "ui_contract"),
  scenario(14, "filtros → detalhe → retorno", "navigation_contract"),
  scenario(15, "deep link → contexto", "shell_contract"),
  scenario(16, "provider semântico indisponível", "graceful_degradation"),
  scenario(17, "conteúdo sem relação", "no_fabrication"),
  scenario(18, "relação privada bloqueada", "visibility_filter"),
];

function row(origin, destination, key, source, publicAccess, available, gap) {
  return {
    origin,
    destination,
    key,
    canonicalSource: source,
    public: publicAccess,
    available,
    gap,
  };
}

function route(path, family, file, requiredTokens) {
  return { route: path, family, file, requiredTokens };
}

function scenario(id, name, proof) {
  return { id, name, proof };
}
