import Image from "next/image";
import Link from "next/link";
import { ComunShell, Section } from "@/components/comun-shell";
import { listIdentificationItems } from "@/lib/archive-identification";
export const dynamic="force-dynamic";
const states=[['','Todas'],['unidentified','Sem identificação'],['has_clues','Com pistas'],['under_review','Em pesquisa'],['partially_identified','Parcialmente identificadas'],['identified','Identificadas'],['disputed','Com divergência']];
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const p=await searchParams,page=Math.max(1,Number(p.page)||1),result=await listIdentificationItems({page,q:p.q,state:p.state});
 return <ComunShell><Section><p className="text-sm font-black uppercase text-comun-yellow">Acervo colaborativo</p><h1 className="mt-2 text-4xl font-black uppercase sm:text-6xl">Memórias em identificação</h1><p className="mt-4 max-w-3xl text-comun-paper/75">Fotografias históricas de Volta Redonda abertas à memória da comunidade. Os títulos são provisórios e as contribuições passam por moderação antes de aparecer.</p><div className="mt-5 border-2 border-comun-yellow p-4"><b className="uppercase text-comun-yellow">Autoria e contexto em identificação</b><p className="mt-1 text-sm">As prévias têm exibição autorizada ao COMUN. Conhece a autoria ou precisa solicitar crédito, correção ou retirada? <Link className="font-black underline" href="/comun/acervo/direitos-e-remocao">Use o canal de direitos</Link>.</p></div>
 <form className="mt-7 grid gap-3 border-2 border-comun-paper/30 p-4 sm:grid-cols-[1fr_auto_auto]"><label className="grid gap-1 text-sm font-black uppercase">Buscar<input name="q" defaultValue={p.q||''} placeholder="Rua, prédio, evento…" className="min-h-12 bg-white p-3 font-normal normal-case text-comun-black"/></label><label className="grid gap-1 text-sm font-black uppercase">Estado<select name="state" defaultValue={p.state||''} className="min-h-12 bg-white p-3 font-normal normal-case text-comun-black">{states.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><button className="min-h-12 self-end bg-comun-yellow px-5 font-black uppercase text-comun-black">Filtrar</button></form>
 <p className="mt-5 text-sm">{result.total} memória(s) disponível(is) para identificação.</p>{!result.campaign?<p className="mt-8 border-2 p-5">A campanha ainda não está aberta.</p>:<div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{result.items.map((item:any)=><Link href={`/comun/acervo/identificar/${item.public_slug}`} key={item.id} className="group border-2 border-comun-paper/25 bg-comun-asphalt/40 p-3 focus:outline-none focus:ring-4 focus:ring-comun-yellow">{item.preview_url?<Image src={item.preview_url} alt="Fotografia histórica de Volta Redonda em identificação" unoptimized width={item.preview_width||800} height={item.preview_height||600} className="aspect-[4/3] w-full bg-black object-contain"/>:<div className="grid aspect-[4/3] place-items-center bg-comun-black p-4 text-center">Restauração técnica pendente</div>}<p className="mt-3 text-xs font-black uppercase text-comun-yellow">{stateLabel(item.research_state)} · {item.comment_count} contribuição(ões)</p><h2 className="mt-1 text-xl font-black group-hover:underline">{item.public_title}</h2><p className="mt-2 line-clamp-2 text-sm text-comun-paper/70">{item.public_prompt}</p></Link>)}</div>}
 {result.pages>1?<nav aria-label="Paginação" className="mt-8 flex flex-wrap gap-2">{Array.from({length:result.pages},(_,i)=>i+1).map(n=><Link key={n} aria-current={n===result.page?'page':undefined} className={`grid size-11 place-items-center border-2 ${n===result.page?'bg-comun-yellow text-comun-black':'border-comun-yellow'}`} href={`?page=${n}&q=${encodeURIComponent(p.q||'')}&state=${encodeURIComponent(p.state||'')}`}>{n}</Link>)}</nav>:null}</Section></ComunShell>
}
function stateLabel(x:string){return ({unidentified:'Sem identificação',has_clues:'Com pistas',under_review:'Em pesquisa',partially_identified:'Identificação parcial',identified:'Identificada',disputed:'Com divergência'} as Record<string,string>)[x]||x}
