import { saveArchiveItem } from "./actions";
import type { ArchiveItem } from "@/lib/archive";

type Item = Partial<ArchiveItem> & { permission_reference?: string | null; editorial_notes?: string | null };
type FieldProps = { item?: Item; name: keyof Item; label: string; type?: string };

function InputField({item,name,label,type="text"}:FieldProps){return <label className="grid gap-1 text-sm font-black uppercase">{label}<input name={name} type={type} defaultValue={String(item?.[name]??"")} className="min-h-11 border-2 border-comun-black px-3"/></label>}
function TextField({item,name,label}:FieldProps){const raw=name==="official_links"?item?.official_links?.map(link=>`${link.label} | ${link.url}`).join("\n"):item?.[name];return <label className="grid gap-1 text-sm font-black uppercase md:col-span-2">{label}<textarea name={name} defaultValue={String(raw??"")} rows={3} className="border-2 border-comun-black p-3"/></label>}

export function ArchiveForm({item}:{item?:Item}){return <form action={saveArchiveItem} className="mt-5 grid gap-3 border-2 border-comun-black bg-white p-5 md:grid-cols-2">{item?.id?<input type="hidden" name="id" value={item.id}/>:null}<InputField item={item} name="title" label="Título"/><InputField item={item} name="slug" label="Slug"/><label className="grid gap-1 text-sm font-black uppercase">Tipo<select name="item_type" defaultValue={item?.item_type}>{["photograph","document","place","artist","music_release","oral_history","video","poster","newspaper","other"].map(value=><option key={value}>{value}</option>)}</select></label><label className="grid gap-1 text-sm font-black uppercase">Direitos<select name="rights_status" defaultValue={item?.rights_status??"unknown"}>{["unknown","public_domain","permission_granted","licensed","external_link_only","restricted"].map(value=><option key={value}>{value}</option>)}</select></label><TextField item={item} name="summary" label="Resumo"/><TextField item={item} name="description" label="Descrição / biografia / discografia"/><InputField item={item} name="city" label="Cidade"/><InputField item={item} name="neighborhood" label="Bairro"/><InputField item={item} name="place_name" label="Local"/><InputField item={item} name="approximate_date" label="Data aproximada"/><InputField item={item} name="year_start" label="Ano inicial" type="number"/><InputField item={item} name="year_end" label="Ano final" type="number"/><label><input type="checkbox" name="circa" value="true" defaultChecked={item?.circa}/> Data aproximada</label><span/><InputField item={item} name="source_name" label="Fonte"/><InputField item={item} name="credits" label="Créditos"/><TextField item={item} name="source_description" label="Descrição da fonte"/><InputField item={item} name="license_text" label="Licença"/><InputField item={item} name="permission_reference" label="Referência interna de permissão"/><InputField item={item} name="genre" label="Gênero artístico"/><InputField item={item} name="members" label="Integrantes"/><TextField item={item} name="official_links" label="Links oficiais (Rótulo | https://...)"/><TextField item={item} name="editorial_notes" label="Notas internas"/><button className="min-h-12 border-2 border-comun-black bg-comun-yellow font-black uppercase md:col-span-2">Salvar item</button></form>}
