"use client";
import Link from "next/link";
import { useState } from "react";

export function CommunityParticipationOnboarding({slug,name,pautaHref,options}:{slug:string;name:string;pautaHref:string;options:string[]}){
 const[saved,setSaved]=useState(false),[online,setOnline]=useState(()=>typeof navigator==="undefined"||navigator.onLine);
 function save(formData:FormData){if(!navigator.onLine){setOnline(false);return}const preference={schemaVersion:1,community:slug,collaboration:formData.getAll("collaboration").map(String),updates:formData.getAll("updates").map(String),savedAt:new Date().toISOString()};localStorage.setItem(`comun:community-preference:v1:${slug}`,JSON.stringify(preference));setSaved(true);setOnline(true)}
 return <div className="grid gap-6 lg:grid-cols-[1fr_.7fr]"><form action={save} className="bg-comun-paper p-5 text-comun-black"><h2 className="text-2xl font-black uppercase">Como quer se aproximar?</h2><p className="mt-2">Você já pode acompanhar {name}. As escolhas abaixo são opcionais e não concedem papel.</p><fieldset className="mt-5"><legend className="font-black uppercase">Formas de colaboração</legend><div className="mt-2 grid gap-2">{options.map(x=><label key={x} className="flex min-h-11 items-center gap-3 border-2 p-3"><input type="checkbox" name="collaboration" value={x}/>{x}</label>)}</div></fieldset><fieldset className="mt-5"><legend className="font-black uppercase">Atualizações significativas</legend><div className="mt-2 grid gap-2"><label className="flex min-h-11 items-center gap-3"><input type="checkbox" name="updates" value="circle"/> Roda aberta ou síntese publicada</label><label className="flex min-h-11 items-center gap-3"><input type="checkbox" name="updates" value="result"/> Resultado ou memória publicada</label></div></fieldset>{!online?<p role="alert" className="mt-4 border-l-4 border-comun-yellow pl-3">Conexão necessária para alterar preferências pessoais.</p>:null}<button className="mt-5 min-h-12 bg-comun-yellow px-5 font-black uppercase">Salvar escolhas</button></form><aside className="border-2 border-comun-yellow p-5"><p className="text-xs font-black uppercase text-comun-yellow">Acompanhamento</p><h2 className="mt-2 text-2xl font-black uppercase">{saved?"Escolhas salvas neste aparelho":"Sem decisões obrigatórias"}</h2><p className="mt-3 text-comun-paper/75">Acompanhar não transforma você em facilitador ou responsável. Papéis operacionais exigem convite e responsabilidade explícita.</p><div className="mt-5 grid gap-3"><Link href={pautaHref} className="inline-flex min-h-12 items-center justify-center bg-comun-yellow px-4 font-black uppercase text-comun-black">Abrir pauta e participar</Link><Link href={`/comun/c/${slug}`} className="inline-flex min-h-12 items-center justify-center border-2 border-comun-yellow px-4 font-black uppercase text-comun-yellow">Voltar à comunidade</Link><Link href="/comun/minha-participacao" className="font-black underline">Ver em Minha área</Link></div></aside></div>
}
