"use client";

import { useMemo, useState } from "react";
import type { SurfaceWaterObservatoryPublicDto } from "@/lib/comun-observatory-surface-water";

function date(value: string) { return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${value}T12:00:00`)); }
function display(value: number | null, qualifier: string | null, unit: string | null) { return value === null ? "Não informado" : `${qualifier ?? ""}${qualifier ? " " : ""}${new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 2 }).format(value)}${unit ? ` ${unit}` : ""}`; }

export function ComunSurfaceWaterObservatory({ dto }: { dto: SurfaceWaterObservatoryPublicDto }) {
  const [stationId, setStationId] = useState(dto.stations[0]?.id ?? "");
  const samples = useMemo(() => dto.samples.filter((sample) => sample.stationId === stationId), [dto.samples, stationId]);
  const indexes = useMemo(() => dto.officialIndexes.filter((index) => index.stationId === stationId && index.value !== null), [dto.officialIndexes, stationId]);
  const values = indexes.map((index) => index.value as number);
  const selected = dto.stations.find((station) => station.id === stationId);
  return <main className="mx-auto max-w-6xl px-4 py-8 text-comun-black sm:py-12">
    <header className="max-w-4xl"><p className="text-xs font-black uppercase text-comun-yellow">Observatório Ambiental</p><h1 className="mt-2 text-4xl font-black uppercase tracking-[-.04em] sm:text-6xl">Qualidade dos Rios</h1><p className="mt-4 text-lg">Dados oficiais do monitoramento do Rio Paraíba do Sul em Volta Redonda. Referência: 2025.</p><p className="mt-4 border-l-4 border-comun-yellow pl-4 text-sm font-bold">As medições foram feitas em datas específicas; não são dados em tempo real. Estes dados não indicam, por si só, se a água é potável.</p></header>
    <section className="mt-8" aria-labelledby="station-title"><h2 id="station-title" className="text-2xl font-black uppercase">Escolha o ponto</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{dto.stations.map((station) => <button key={station.id} type="button" onClick={() => setStationId(station.id)} aria-pressed={station.id === stationId} className={`min-h-24 border-2 p-4 text-left ${station.id === stationId ? "border-comun-black bg-comun-yellow" : "border-comun-black/25 bg-comun-paper"}`}><span className="block text-xl font-black">{station.code}</span><span className="mt-1 block text-sm">Rio Paraíba do Sul · Volta Redonda</span></button>)}</div></section>
    <section className="mt-8 grid gap-3 sm:grid-cols-4" aria-label="Resumo do ponto"><Metric value={`${samples.length}`} label="coletas em 2025" /><Metric value="10" label="parâmetros por coleta" /><Metric value={samples.length ? `${date(samples[0].sampledAt)} — ${date(samples.at(-1)!.sampledAt)}` : "Não informado"} label="período das coletas" /><Metric value={values.length ? `${Math.min(...values).toLocaleString("pt-BR")} — ${Math.max(...values).toLocaleString("pt-BR")}` : "Não informado"} label="IQA publicado pelo INEA" /></section>
    <section className="mt-10" aria-labelledby="iqa-title"><h2 id="iqa-title" className="text-3xl font-black uppercase">IQA publicado pelo INEA</h2><p className="mt-2 max-w-3xl">O IQA é um índice sintético publicado na fonte segundo sua metodologia. Ele aparece separado das medições de laboratório e não é recalculado pelo COMUN.</p><ol className="mt-4 grid gap-2 sm:grid-cols-2">{indexes.map((index) => <li key={index.sampledAt} className="flex justify-between border-2 border-comun-black/20 bg-comun-paper p-3"><span>{index.sampledAt ? date(index.sampledAt) : "Data não informada"}</span><strong>{display(index.value, index.qualifier, null)}</strong></li>)}</ol></section>
    <section className="mt-10" aria-labelledby="samples-title"><h2 id="samples-title" className="text-3xl font-black uppercase">Coletas e parâmetros</h2><p className="mt-2">Ponto {selected?.code ?? "não informado"}. Resultados com &lt; ou &gt; preservam o qualificador publicado pela fonte; resultados não informados não são convertidos em zero.</p><div className="mt-4 grid gap-3">{samples.map((sample) => <details key={sample.sampledAt} className="border-2 border-comun-black/25 bg-comun-paper p-4"><summary className="cursor-pointer font-black">Coleta de {date(sample.sampledAt)} <span className="font-normal">· {sample.measurements.length} parâmetros</span></summary><dl className="mt-4 grid gap-3 sm:grid-cols-2">{sample.measurements.map((measurement) => <div key={measurement.parameter} className="border-t border-comun-black/15 pt-2"><dt className="font-bold">{measurement.officialParameterLabel}</dt><dd className="mt-1">{display(measurement.value, measurement.qualifier, measurement.unit)}</dd>{measurement.qualifier ? <dd className="mt-1 text-xs text-comun-black/70">Qualificador publicado pela fonte.</dd> : null}</div>)}</dl></details>)}</div></section>
    <section className="mt-10 grid gap-5 border-t-2 border-comun-black/20 pt-7 sm:grid-cols-2"><div><h2 className="text-2xl font-black uppercase">O que estes dados mostram</h2><p className="mt-2 text-sm">Medições oficiais nas datas indicadas, parâmetros publicados pelo INEA e o IQA publicado na fonte.</p></div><div><h2 className="text-2xl font-black uppercase">O que estes dados não mostram</h2><p className="mt-2 text-sm">Não são tempo real, não medem água da torneira, não determinam potabilidade, não provam origem de poluição e não substituem análise normativa específica.</p></div></section>
  </main>;
}
function Metric({ value, label }: { value: string; label: string }) { return <article className="border-2 border-comun-black bg-comun-paper p-4"><p className="text-xl font-black">{value}</p><p className="mt-1 text-sm font-bold">{label}</p></article>; }
