import Link from'next/link';
export function ObservatoryHero({title,summary,status}:{title:string;summary:string;status:string}){return <header className="observatory-hero"><span className="sample-badge">{status}</span><h1>{title}</h1><p>{summary}</p></header>}
export function SampleBadge({n}:{n:number}){return <span className="sample-badge" aria-label={`Amostra: ${n}`}>amostra n={n}</span>}
export function CoverageBadge({children}:{children:React.ReactNode}){return <span className="coverage-badge">cobertura: {children}</span>}
export function MethodologyNotice({children}:{children:React.ReactNode}){return <aside className="methodology-notice"><b>Como ler estes dados</b><p>Dados produzidos a partir de observações comunitárias e sujeitos a limitações de cobertura.</p>{children}</aside>}
export function MetricCard({title,value,unit,sample}:{title:string;value:string|number;unit:string;sample:number}){return <article className="metric-card"><p>{title}</p><strong>{value} <small>{unit}</small></strong><SampleBadge n={sample}/></article>}
export function DimensionBreakdown({title,values,sample}:{title:string;values:Record<string,number>;sample:number}){const max=Math.max(1,...Object.values(values));return <section className="dimension"><h3>{title}</h3><div role="img" aria-label={`${title}, distribuição de ${sample} observações`}>{Object.entries(values).map(([k,v])=><div className="bar-row" key={k}><span>{k.replaceAll('_',' ')}</span><span className="bar-track"><span style={{width:`${100*v/max}%`}}/></span><b>{v}</b></div>)}</div><table><caption>Alternativa tabular: {title}</caption><thead><tr><th>Categoria</th><th>Observações</th></tr></thead><tbody>{Object.entries(values).map(([k,v])=><tr key={k}><td>{k.replaceAll('_',' ')}</td><td>{v}</td></tr>)}</tbody></table></section>}
export function DataLimitations({text}:{text?:string|null}){return <section className="limitations"><h2>Limitações</h2><p>{text||'Sem amostra suficiente para publicar indicadores. Ausência de dado não significa valor zero.'}</p></section>}
export function EmptyObservationState(){return <div className="empty-state"><h2>Ainda não há dados públicos suficientes</h2><p>As observações precisam de revisão e amostra mínima antes de qualquer indicador.</p></div>}
export function ActionConnection({slug,title,note}:{slug:string;title:string;note?:string|null}){return <Link className="action-connection" href={`/comun/acoes/${slug}`}><b>{title}</b><span>{note||'Ação revisada ligada aos dados.'}</span></Link>}
export function ObservationStatus(){return <p className="methodology-notice"><b>Moderação humana:</b> toda observação nasce pendente e nunca vira dado público automaticamente.</p>}
