import Link from "next/link";
import type {ReactNode} from "react";

export function MiniAppShell({children}:{children:ReactNode}){return <main className="min-h-screen bg-comun-paper text-comun-black">{children}</main>}
export function MiniAppHeader({title,summary}:{title:string;summary:string}){return <header className="border-b-2 border-comun-black bg-comun-yellow"><div className="mx-auto max-w-7xl px-4 py-7"><Link href="/comun" className="text-sm font-black underline">COMUN</Link><p className="mt-4 text-xs font-black uppercase tracking-[.18em]">Miniapp comunitário · piloto local</p><h1 className="mt-2 text-4xl font-black uppercase leading-none sm:text-6xl">{title}</h1><p className="mt-4 max-w-3xl text-lg">{summary}</p><MiniAppPrimaryAction href="/comun/mapa/contribuir?origem=calcadas&pauta=calcadas-em-circulacao">Enviar foto e marcar local</MiniAppPrimaryAction></div></header>}
export function MiniAppNavigation(){return <nav aria-label="Seções do miniapp" className="sticky top-0 z-30 border-b-2 border-comun-black bg-comun-black text-comun-paper"><div className="mx-auto flex max-w-7xl overflow-x-auto px-4">{[["mapa","Mapa"],["prioridades","Prioridades"],["mobilizacao","Mobilização"],["resultados","Resultados"]].map(([id,label])=><a key={id} href={`#${id}`} className="min-h-12 whitespace-nowrap px-4 py-3 font-black uppercase hover:bg-comun-yellow hover:text-comun-black">{label}</a>)}</div></nav>}
export function MiniAppPrimaryAction({href,children}:{href:string;children:ReactNode}){return <Link href={href} className="mt-6 inline-flex min-h-12 items-center border-2 border-comun-black bg-comun-black px-5 font-black uppercase text-comun-yellow">{children}</Link>}
export function CoverageNotice({children}:{children:ReactNode}){return <p className="mt-5 border-l-4 border-comun-yellow bg-comun-black p-4 text-sm font-bold text-comun-paper">{children}</p>}
export function SidewalkTimeline({events}:{events:{label:string;date?:string|null;active?:boolean}[]}){return <ol className="grid gap-3">{events.map((event,index)=><li key={`${event.label}-${index}`} className="grid grid-cols-[1.5rem_1fr] gap-3"><span aria-hidden="true" className={`mt-1 size-4 rounded-full border-2 border-comun-black ${event.active?"bg-comun-yellow":"bg-white"}`}/><div><strong>{event.label}</strong>{event.date?<time className="ml-2 text-sm" dateTime={event.date}>{new Date(event.date).toLocaleDateString("pt-BR")}</time>:null}</div></li>)}</ol>}
