"use client";
import { useActionState,useEffect,useRef,useState } from "react";
import { submitAuthenticatedSidewalkRecord } from "@/app/comun/mapa/contribuir/actions";
import { COMUN_DRAFT_KEY, migrateSidewalkDraft, parseSafeDrafts, type SafeDraft } from "@/lib/comun-pwa";
type Draft={step:number;category:string;manualMap:boolean};
const legacyKey="comun:sidewalk-draft:v1",initial:Draft={step:1,category:"calcada_irregular",manualMap:true},labels=["Foto","Local","Problema","Revisar"];
export function SidewalkFirstParticipationForm({pautaSlug}:{pautaSlug:string}){
 const[draft,setDraft]=useState(initial),[ready,setReady]=useState(false),[hasPhoto,setHasPhoto]=useState(false),[online,setOnline]=useState(true),[submission,submitAction,pending]=useActionState(submitAuthenticatedSidewalkRecord,null);const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{queueMicrotask(()=>{let drafts=parseSafeDrafts(localStorage.getItem(COMUN_DRAFT_KEY));if(!drafts.length){drafts=migrateSidewalkDraft(localStorage.getItem(legacyKey),pautaSlug);if(drafts.length)localStorage.setItem(COMUN_DRAFT_KEY,JSON.stringify(drafts));localStorage.removeItem(legacyKey)}const saved=drafts.find(item=>item.id===`sidewalk:${pautaSlug}`);if(saved)setDraft({step:saved.step,category:saved.category,manualMap:saved.manualMap});setOnline(navigator.onLine);setReady(true)})},[pautaSlug]);
 useEffect(()=>{if(!ready)return;const saved:SafeDraft={id:`sidewalk:${pautaSlug}`,kind:"sidewalk",step:draft.step,category:draft.category,pauta:pautaSlug,manualMap:draft.manualMap,updatedAt:new Date().toISOString(),schemaVersion:2};const others=parseSafeDrafts(localStorage.getItem(COMUN_DRAFT_KEY)).filter(item=>item.id!==saved.id);localStorage.setItem(COMUN_DRAFT_KEY,JSON.stringify([...others,saved]))},[draft,pautaSlug,ready]);
 useEffect(()=>{const up=()=>setOnline(true),down=()=>setOnline(false);window.addEventListener("online",up);window.addEventListener("offline",down);return()=>{window.removeEventListener("online",up);window.removeEventListener("offline",down)}},[]);
 const next=()=>setDraft(v=>({...v,step:Math.min(4,v.step+1)})),back=()=>setDraft(v=>({...v,step:Math.max(1,v.step-1)})),discard=()=>{localStorage.setItem(COMUN_DRAFT_KEY,JSON.stringify(parseSafeDrafts(localStorage.getItem(COMUN_DRAFT_KEY)).filter(item=>item.id!==`sidewalk:${pautaSlug}`)));setDraft(initial);setHasPhoto(false);if(fileRef.current)fileRef.current.value=""};
 return <form action={submitAction} className="mt-6 grid gap-5"><input type="hidden" name="pauta_slug" value={pautaSlug}/><input type="hidden" name="return_to" value={`/comun/pautas/${pautaSlug}`}/><input type="hidden" name="category" value={draft.category}/><input type="hidden" name="geometry_type" value="Point"/>
 {submission?.error?<p role="alert" className="border-l-4 border-comun-yellow bg-comun-paper p-4 text-comun-black"><strong>O registro não foi enviado.</strong> {submission.error}</p>:null}
 {ready&&draft.step>1?<div className="border-l-4 border-comun-yellow bg-comun-paper p-3 text-sm text-comun-black"><strong>Continuar registro de calçada.</strong> Só escolhas não sensíveis foram retomadas. <button type="button" onClick={discard} className="font-black underline">Descartar rascunho</button></div>:null}
 <ol aria-label="Etapas do registro" className="grid grid-cols-4 gap-2">{labels.map((label,index)=><li key={label} aria-current={draft.step===index+1?"step":undefined} className={`border-t-4 pt-2 text-xs font-black uppercase ${index+1<=draft.step?"border-comun-yellow text-comun-paper":"border-comun-paper/30 text-comun-paper/50"}`}>{index+1}. {label}</li>)}</ol>
 <div hidden={draft.step!==1} className="border-2 bg-comun-paper p-5 text-comun-black"><h2 className="text-2xl font-black uppercase">1. Foto</h2><p className="mt-2">Use uma imagem sem rostos, placas ou números de casa. Ela fica privada até revisão.</p><label className="mt-5 grid gap-2 font-black uppercase">JPEG da situação<input ref={fileRef} onChange={e=>setHasPhoto(Boolean(e.target.files?.length))} name="photo" type="file" accept="image/jpeg" className="min-h-12 border-2 p-2"/></label>{hasPhoto?<button type="button" onClick={()=>{if(fileRef.current)fileRef.current.value="";setHasPhoto(false)}} className="mt-3 font-black underline">Remover foto</button>:<p className="mt-3 text-sm">Você pode continuar sem foto.</p>}</div>
 <div hidden={draft.step!==2} className="border-2 bg-comun-paper p-5 text-comun-black"><h2 className="text-2xl font-black uppercase">2. Local</h2><p className="mt-2">Escolha uma referência aproximada. Não pediremos permissão de GPS.</p><label className="mt-5 grid gap-2 font-black uppercase">Bairro ou referência pública<input name="approximate_location" maxLength={120} placeholder="Ex.: Centro, perto da praça" className="min-h-12 border-2 px-3"/></label><label className="mt-4 flex min-h-12 items-center gap-3"><input type="checkbox" checked={draft.manualMap} onChange={e=>setDraft({...draft,manualMap:e.target.checked})}/> Marcar ponto manualmente</label><fieldset className="mt-4"><legend className="font-black uppercase">Alternativa textual ao mapa</legend><label className="mt-2 flex min-h-12 items-center gap-3 border-2 p-3"><input type="radio" name="fixture_point" value="-44.1000,-22.5200" defaultChecked/> Trecho sintético local</label></fieldset></div>
 <div hidden={draft.step!==3} className="border-2 bg-comun-paper p-5 text-comun-black"><h2 className="text-2xl font-black uppercase">3. Problema</h2><label className="mt-4 grid gap-2 font-black uppercase">Categoria<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})} className="min-h-12 border-2 bg-white px-3"><option value="calcada_irregular">Calçada irregular — piso quebrado</option><option value="ausencia_rampa">Ausência de rampa — barreira de acesso</option><option value="obstaculo">Obstáculo — passagem interrompida</option><option value="buraco">Buraco — risco de queda</option></select></label><label className="mt-4 grid gap-2 font-black uppercase">Impacto<select name="impact_level" className="min-h-12 border-2 bg-white px-3"><option value="medium">Dificulta a passagem</option><option value="high">Impede ou oferece risco</option><option value="low">Incômodo pontual</option></select></label><label className="mt-4 grid gap-2 font-black uppercase">Descrição curta<textarea name="description" required minLength={20} maxLength={600} rows={4} className="border-2 p-3" placeholder="Descreva sem dados pessoais."/></label></div>
 <div hidden={draft.step!==4} className="border-2 bg-comun-paper p-5 text-comun-black"><h2 className="text-2xl font-black uppercase">4. Revisar</h2><p className="mt-3">Seu registro entrará como <strong>em revisão</strong>. A localização será aproximada e a foto ficará privada até análise.</p>{!online?<p role="alert" className="mt-4 border-l-4 border-comun-yellow pl-3 font-bold">Esta ação precisa de conexão para ser enviada. O rascunho seguro foi mantido, mas a foto precisará ser selecionada novamente após recarregar.</p>:null}<button disabled={!online||pending} className="mt-6 min-h-12 w-full bg-comun-yellow px-4 font-black uppercase disabled:cursor-not-allowed disabled:opacity-50">{pending?"Enviando para revisão…":online?"Enviar contribuição para revisão":"Aguardando conexão"}</button></div>
 <nav aria-label="Ações do formulário" className="flex justify-between gap-3 pb-24 sm:pb-8">{draft.step>1?<button type="button" onClick={back} className="min-h-12 font-black uppercase text-comun-yellow underline">Voltar</button>:<span/>}{draft.step<4?<button type="button" onClick={next} className="min-h-12 bg-comun-yellow px-5 font-black uppercase">Continuar</button>:null}</nav></form>
}

export function SidewalkDraftCleanup({pautaSlug}:{pautaSlug:string}){useEffect(()=>{const remaining=parseSafeDrafts(localStorage.getItem(COMUN_DRAFT_KEY)).filter(item=>item.id!==`sidewalk:${pautaSlug}`);localStorage.setItem(COMUN_DRAFT_KEY,JSON.stringify(remaining))},[pautaSlug]);return null}
