"use client";
import { useActionState,useEffect,useRef,useState } from "react";
import { submitAuthenticatedSidewalkRecord } from "@/app/comun/mapa/contribuir/actions";
import { COMUN_DRAFT_KEY, migrateSidewalkDraft, parseSafeDrafts, type SafeDraft } from "@/lib/comun-pwa";
import {projectMercator,unprojectMercator,VOLTA_REDONDA_MAP} from "@/lib/sidewalk-map-config";
type Draft={step:number;category:string;manualMap:boolean};
const legacyKey="comun:sidewalk-draft:v1",initial:Draft={step:1,category:"irregular",manualMap:true},labels=["Foto","Local","Avaliação","Revisar"];
export function SidewalkFirstParticipationForm({pautaSlug}:{pautaSlug:string}){
 const[draft,setDraft]=useState(initial),[condition,setCondition]=useState("regular"),[point,setPoint]=useState<[number,number]|null>(null),[locationMessage,setLocationMessage]=useState("Marque um ponto no mapa ou use sua localização agora."),[ready,setReady]=useState(false),[hasPhoto,setHasPhoto]=useState(false),[online,setOnline]=useState(true),[submission,submitAction,pending]=useActionState(submitAuthenticatedSidewalkRecord,null);const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{queueMicrotask(()=>{let drafts=parseSafeDrafts(localStorage.getItem(COMUN_DRAFT_KEY));if(!drafts.length){drafts=migrateSidewalkDraft(localStorage.getItem(legacyKey),pautaSlug);if(drafts.length)localStorage.setItem(COMUN_DRAFT_KEY,JSON.stringify(drafts));localStorage.removeItem(legacyKey)}const saved=drafts.find(item=>item.id===`sidewalk:${pautaSlug}`);if(saved)setDraft({step:saved.step,category:saved.category,manualMap:saved.manualMap});setOnline(navigator.onLine);setReady(true)})},[pautaSlug]);
 useEffect(()=>{if(!ready)return;const saved:SafeDraft={id:`sidewalk:${pautaSlug}`,kind:"sidewalk",step:draft.step,category:draft.category,pauta:pautaSlug,manualMap:draft.manualMap,updatedAt:new Date().toISOString(),schemaVersion:2};const others=parseSafeDrafts(localStorage.getItem(COMUN_DRAFT_KEY)).filter(item=>item.id!==saved.id);localStorage.setItem(COMUN_DRAFT_KEY,JSON.stringify([...others,saved]))},[draft,pautaSlug,ready]);
 useEffect(()=>{const up=()=>setOnline(true),down=()=>setOnline(false);window.addEventListener("online",up);window.addEventListener("offline",down);return()=>{window.removeEventListener("online",up);window.removeEventListener("offline",down)}},[]);
 const next=()=>setDraft(v=>({...v,step:Math.min(4,v.step+1)})),back=()=>setDraft(v=>({...v,step:Math.max(1,v.step-1)})),discard=()=>{localStorage.setItem(COMUN_DRAFT_KEY,JSON.stringify(parseSafeDrafts(localStorage.getItem(COMUN_DRAFT_KEY)).filter(item=>item.id!==`sidewalk:${pautaSlug}`)));setDraft(initial);setHasPhoto(false);if(fileRef.current)fileRef.current.value=""};
 const useLocation=()=>{if(!navigator.geolocation){setLocationMessage("Localização não disponível. Marque manualmente.");return}navigator.geolocation.getCurrentPosition(({coords})=>{setPoint([coords.longitude,coords.latitude]);setLocationMessage("Localização recebida. Você pode ajustar no mapa.")},()=>setLocationMessage("Não foi possível obter a localização. Marque manualmente."),{enableHighAccuracy:false,maximumAge:0,timeout:8000})};
 return <form action={submitAction} className="mt-6 grid gap-5"><input type="hidden" name="pauta_slug" value={pautaSlug}/><input type="hidden" name="return_to" value="/comun/calcadas"/><input type="hidden" name="category" value={draft.category}/><input type="hidden" name="condition" value={condition}/><input type="hidden" name="longitude" value={point?.[0]??"not-set"}/><input type="hidden" name="latitude" value={point?.[1]??"not-set"}/><input type="hidden" name="location_source" value="manual"/><input type="hidden" name="geometry_type" value="Point"/>
 {submission?.error?<p role="alert" className="border-l-4 border-comun-yellow bg-comun-paper p-4 text-comun-black"><strong>O registro não foi enviado.</strong> {submission.error}</p>:null}
 {ready&&draft.step>1?<div className="border-l-4 border-comun-yellow bg-comun-paper p-3 text-sm text-comun-black"><strong>Continuar registro de calçada.</strong> Só escolhas não sensíveis foram retomadas. <button type="button" onClick={discard} className="font-black underline">Descartar rascunho</button></div>:null}
 <ol aria-label="Etapas do registro" className="grid grid-cols-4 gap-2">{labels.map((label,index)=><li key={label} aria-current={draft.step===index+1?"step":undefined} className={`border-t-4 pt-2 text-xs font-black uppercase ${index+1<=draft.step?"border-comun-yellow text-comun-paper":"border-comun-paper/30 text-comun-paper/50"}`}>{index+1}. {label}</li>)}</ol>
 <div hidden={draft.step!==1} className="border-2 bg-comun-paper p-5 text-comun-black"><h2 className="text-2xl font-black uppercase">1. Foto</h2><p className="mt-2">Use uma imagem sem rostos, placas ou números de casa. Ela fica privada até revisão.</p><label className="mt-5 grid gap-2 font-black uppercase">JPEG da situação<input ref={fileRef} onChange={e=>setHasPhoto(Boolean(e.target.files?.length))} name="photo" type="file" accept="image/jpeg" className="min-h-12 border-2 p-2"/></label>{hasPhoto?<button type="button" onClick={()=>{if(fileRef.current)fileRef.current.value="";setHasPhoto(false)}} className="mt-3 font-black underline">Remover foto</button>:<p className="mt-3 text-sm">Você pode continuar sem foto.</p>}</div>
 <div hidden={draft.step!==2} className="border-2 bg-comun-paper p-5 text-comun-black"><h2 className="text-2xl font-black uppercase">2. Local</h2><p className="mt-2">A localização é opcional e usada uma única vez. O ponto preciso fica privado até a revisão produzir uma versão pública.</p><button type="button" onClick={useLocation} className="mt-4 min-h-12 border-2 border-comun-black px-4 font-black uppercase">Usar localização agora</button><p role="status" className="mt-2 text-sm">{locationMessage}</p><ManualPointPicker point={point} onChange={value=>{setPoint(value);setLocationMessage("Ponto marcado manualmente.")}}/><label className="mt-5 grid gap-2 font-black uppercase">Bairro ou referência pública<input name="approximate_location" maxLength={120} placeholder="Ex.: Centro, perto da praça" className="min-h-12 border-2 px-3"/></label><label className="mt-4 grid gap-2 font-black uppercase">Bairro<select name="neighborhood" className="min-h-12 border-2 bg-white px-3"><option value="">Prefiro não informar</option><option>Centro</option><option>Aterrado</option><option>Retiro</option><option>Vila Santa Cecília</option></select></label></div>
 <div hidden={draft.step!==3} className="border-2 bg-comun-paper p-5 text-comun-black"><h2 className="text-2xl font-black uppercase">3. Avaliação</h2><fieldset><legend className="font-black uppercase">Condição da calçada</legend><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{[["good","Boa"],["regular","Regular"],["bad","Ruim"],["terrible","Péssima"]].map(([value,label])=><label key={value} className={`grid min-h-14 place-items-center border-2 p-2 font-black ${condition===value?"bg-comun-yellow":"bg-white"}`}><input className="sr-only" type="radio" checked={condition===value} onChange={()=>setCondition(value)}/>{label}</label>)}</div></fieldset><label className="mt-4 grid gap-2 font-black uppercase">Problema principal<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})} className="min-h-12 border-2 bg-white px-3"><option value="buraco">Buraco</option><option value="irregular">Irregular</option><option value="sem_rampa">Sem rampa</option><option value="obstaculo">Obstáculo</option><option value="estreita">Estreita</option><option value="inexistente">Inexistente</option><option value="entulho">Entulho</option><option value="vegetacao">Vegetação</option><option value="poste">Poste</option><option value="outro">Outro</option></select></label><label className="mt-4 grid gap-2 font-black uppercase">Descrição opcional<textarea name="description" maxLength={600} rows={4} className="border-2 p-3" placeholder="Descreva sem dados pessoais."/></label></div>
 <div hidden={draft.step!==4} className="border-2 bg-comun-paper p-5 text-comun-black"><h2 className="text-2xl font-black uppercase">4. Revisar</h2><p className="mt-3">Seu registro entrará como <strong>em revisão</strong>. A localização será aproximada e a foto ficará privada até análise.</p>{!online?<p role="alert" className="mt-4 border-l-4 border-comun-yellow pl-3 font-bold">Esta ação precisa de conexão para ser enviada. O rascunho seguro foi mantido, mas a foto precisará ser selecionada novamente após recarregar.</p>:null}<button disabled={!online||pending} className="mt-6 min-h-12 w-full bg-comun-yellow px-4 font-black uppercase disabled:cursor-not-allowed disabled:opacity-50">{pending?"Enviando para revisão…":online?"Enviar contribuição para revisão":"Aguardando conexão"}</button></div>
 <nav aria-label="Ações do formulário" className="flex justify-between gap-3 pb-24 sm:pb-8">{draft.step>1?<button type="button" onClick={back} className="min-h-12 font-black uppercase text-comun-yellow underline">Voltar</button>:<span/>}{draft.step<4?<button type="button" onClick={next} className="min-h-12 bg-comun-yellow px-5 font-black uppercase">Continuar</button>:null}</nav></form>
}

export function SidewalkDraftCleanup({pautaSlug}:{pautaSlug:string}){useEffect(()=>{const remaining=parseSafeDrafts(localStorage.getItem(COMUN_DRAFT_KEY)).filter(item=>item.id!==`sidewalk:${pautaSlug}`);localStorage.setItem(COMUN_DRAFT_KEY,JSON.stringify(remaining))},[pautaSlug]);return null}

function ManualPointPicker({point,onChange}:{point:[number,number]|null;onChange:(point:[number,number])=>void}){const p=point?projectMercator(point):null;return <div className="mt-4"><p className="font-black uppercase">Marcar no mapa</p><button type="button" aria-label="Mapa local para marcar o ponto" onClick={event=>{const rect=event.currentTarget.getBoundingClientRect();onChange(unprojectMercator((event.clientX-rect.left)/rect.width,(event.clientY-rect.top)/rect.height))}} className="relative mt-2 block h-64 w-full overflow-hidden border-2 border-comun-black bg-[#dfe7df]"><svg viewBox="0 0 600 300" className="absolute inset-0 h-full w-full" aria-hidden="true"><path d="M0 190 C100 130 210 230 310 160 S480 90 600 130" fill="none" stroke={VOLTA_REDONDA_MAP.style.water} strokeWidth="22"/><g stroke={VOLTA_REDONDA_MAP.style.grid}>{[80,180,280,380,480].map(x=><line key={x} x1={x} y1="0" x2={x-50} y2="300"/>)}</g></svg>{p?<span className="absolute grid size-10 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-2 border-comun-black bg-comun-yellow" style={{left:`${p.x*100}%`,top:`${p.y*100}%`}}>●</span>:null}<span className="absolute bottom-2 left-2 bg-white p-2 text-xs font-bold">Toque para posicionar · base local simplificada</span></button></div>}
