import Link from "next/link";
import { notFound } from "next/navigation";
import { ComunShell, Section } from "@/components/comun-shell";
import { claimCollectiveActionTask, releaseCollectiveActionTask, updateCollectiveActionParticipation } from "@/app/comun/acoes/actions";
import { getPublicCollectiveAction } from "@/lib/collective-actions";
import { collectiveActionStatusLabels, collectiveActionTypeLabels, collectiveParticipationModeLabels, collectiveTaskEffortLabels } from "@/lib/collective-actions";

export const dynamic = "force-dynamic";

export default async function CollectiveActionDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const action: any = await getPublicCollectiveAction(slug);
  if (!action) notFound();
  return <ComunShell>
    <Section>
      <p className="text-xs font-black uppercase text-comun-yellow">{(collectiveActionTypeLabels as Record<string, string>)[action.action_type] ?? action.action_type} · {(collectiveActionStatusLabels as Record<string, string>)[action.status] ?? action.status}</p>
      <h1 className="mt-2 text-4xl font-black uppercase text-comun-yellow">{action.title}</h1>
      <p className="mt-4 max-w-3xl text-lg text-comun-paper/80">{action.objective}</p>
      <div className="mt-5 grid gap-3 border-l-4 border-comun-yellow bg-comun-paper/5 p-4 sm:grid-cols-3"><Cell label="Território" value={action.territory_label ?? "a definir"}/><Cell label="Quando" value={action.starts_at ? new Date(action.starts_at).toLocaleString("pt-BR") : "em construção"}/><Cell label="Onde" value={action.meeting_place ?? "a confirmar"}/></div>
      <p className="mt-4 max-w-3xl">{action.summary}</p>
      <div className="mt-5 flex flex-wrap gap-3 text-sm font-black"><span>{action.counts.interested} interessadas</span><span>{action.counts.participating} participando</span><span>{action.counts.tasksAssumed} tarefas assumidas</span><span>{action.counts.updates} atualizações</span></div>
    </Section>
    <Section><h2 className="text-2xl font-black uppercase text-comun-yellow">Entrar na ação</h2><p className="mt-2 max-w-3xl text-comun-paper/75">Sua participação não cria perfil público nem expõe contato, localização ou observações privadas.</p><div className="mt-4 flex flex-wrap gap-3">{["interested", "participating", "available_for_task"].map((status) => <form action={updateCollectiveActionParticipation} key={status}><input type="hidden" name="slug" value={slug}/><input type="hidden" name="status" value={status}/><button className="min-h-11 border-2 border-comun-yellow px-4 font-black uppercase text-comun-yellow">{status === "interested" ? "Tenho interesse" : status === "participating" ? "Quero participar" : "Posso ajudar numa tarefa"}</button></form>)}<form action={updateCollectiveActionParticipation}><input type="hidden" name="slug" value={slug}/><input type="hidden" name="status" value="withdrew"/><button className="min-h-11 px-2 font-bold underline">Sair da ação</button></form></div><form action={updateCollectiveActionParticipation} className="mt-4 grid gap-2 border-t border-comun-paper/30 pt-4"><input type="hidden" name="slug" value={slug}/><input type="hidden" name="status" value="contributed"/><label className="grid gap-1 text-sm font-black">Contribuição curta para revisão<textarea name="contribution_note_private" rows={2} maxLength={600} className="border-2 border-comun-paper bg-comun-black p-2 text-comun-paper" placeholder="Não será publicada automaticamente."/></label><button className="min-h-11 w-fit border-2 border-comun-paper px-3 text-sm font-black">Enviar para revisão</button></form></Section>
    <Section><h2 className="text-2xl font-black uppercase text-comun-yellow">Pequenas tarefas</h2><div className="mt-4 grid gap-3">{action.tasks.map((task: any) => <article key={task.id} className="border-2 border-comun-paper/30 p-4"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-black uppercase">{task.title}</h3><p className="mt-2 max-w-2xl text-comun-paper/75">{task.description}</p><p className="mt-2 text-sm">{task.assumed_count}/{task.desired_count} assumidas · {collectiveTaskEffortLabels[task.effort_level] ?? task.effort_level} · {collectiveParticipationModeLabels[task.participation_mode] ?? task.participation_mode}{task.due_at ? ` · até ${new Date(task.due_at).toLocaleDateString("pt-BR")}` : ""}</p></div><div className="flex flex-wrap items-start gap-2"><form action={claimCollectiveActionTask}><input type="hidden" name="slug" value={slug}/><input type="hidden" name="task_id" value={task.id}/><button className="min-h-11 border-2 border-comun-yellow bg-comun-yellow px-3 font-black uppercase text-comun-black">Assumir</button></form><form action={releaseCollectiveActionTask}><input type="hidden" name="slug" value={slug}/><input type="hidden" name="task_id" value={task.id}/><button className="min-h-11 px-2 font-bold underline">Liberar</button></form></div></div></article>)}</div></Section>
    <Section><h2 className="text-2xl font-black uppercase text-comun-yellow">Linha do tempo</h2><ol className="mt-4 grid gap-3 border-l-2 border-comun-yellow pl-5">{action.updates.map((update: any) => <li key={update.id}><p className="text-xs font-black uppercase text-comun-yellow">{update.update_type} · {new Date(update.occurred_at).toLocaleDateString("pt-BR")}</p><h3 className="mt-1 font-black">{update.title}</h3><p className="mt-1 text-comun-paper/75">{update.public_summary}</p></li>)}</ol></Section>
    {action.pauta || action.community || action.sidewalkRecords.length ? <Section><h2 className="text-2xl font-black uppercase text-comun-yellow">Vínculos</h2>{action.pauta ? <Link className="mt-3 block font-black underline" href={`/comun/pautas/${action.pauta.slug}`}>Pauta: {action.pauta.title}</Link> : null}{action.community ? <p className="mt-3 font-black">Comunidade: {action.community.name}</p> : null}{action.sidewalkRecords.map((record: any) => <p className="mt-2 text-sm" key={record.slug}>Registro relacionado: {record.name ?? record.public_summary ?? "registro revisado"}</p>)}</Section> : null}
    {action.status === "completed" ? <Section><h2 className="text-2xl font-black uppercase text-comun-yellow">Resultado e memória</h2><p className="mt-3">{action.result_summary ?? "Resultado em consolidação."}</p><p className="mt-3 text-comun-paper/75">{action.memory_summary ?? "A memória desta ação permanece disponível como aprendizado coletivo."}</p></Section> : null}
  </ComunShell>;
}

function Cell({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-black uppercase text-comun-yellow">{label}</p><p className="mt-1">{value}</p></div>; }
