import { createHash } from "node:crypto";
import { z } from "zod";

const allowedTypes=["text","textarea","integer","decimal","boolean","single_select","multi_select","date","time","datetime","duration","rating_dimension","territory_reference","monitored_entity_reference","optional_evidence"] as const;
const field=z.object({key:z.string().regex(/^[a-z][a-z0-9_]{0,49}$/),label:z.string().min(1).max(120),type:z.enum(allowedTypes),required:z.boolean().default(false),options:z.array(z.string().min(1).max(80)).max(30).optional(),min:z.number().optional(),max:z.number().optional()}).strict();
export const formSchemaDefinition=z.object({fields:z.array(field).min(1).max(40),consent_text:z.string().min(10).max(500)}).strict().superRefine((v,c)=>{const keys=v.fields.map(x=>x.key);if(new Set(keys).size!==keys.length)c.addIssue({code:"custom",message:"Campos duplicados"});for(const f of v.fields)if(["single_select","multi_select","rating_dimension"].includes(f.type)&&!f.options?.length)c.addIssue({code:"custom",message:`${f.key} exige opções`})});
const scalar=z.union([z.string().max(4000),z.number().finite(),z.boolean(),z.null()]);
export function validateObservationPayload(schema:unknown,payload:unknown){const parsed=formSchemaDefinition.safeParse(schema);if(!parsed.success)return{ok:false as const,error:"Schema de formulário inválido."};if(!payload||typeof payload!=="object"||Array.isArray(payload))return{ok:false as const,error:"Payload inválido."};const data=payload as Record<string,unknown>,known=new Set(parsed.data.fields.map(f=>f.key));if(Object.keys(data).some(k=>!known.has(k)))return{ok:false as const,error:"Campo não previsto."};for(const f of parsed.data.fields){const v=data[f.key];if(f.required&&(v===undefined||v===""||v===null))return{ok:false as const,error:`${f.label} é obrigatório.`};if(v===undefined||v===""||v===null)continue;if(f.type==="multi_select"){if(!Array.isArray(v)||v.length>10||v.some(x=>typeof x!=="string"||!f.options?.includes(x)))return{ok:false as const,error:`${f.label} inválido.`};continue}if(!scalar.safeParse(v).success)return{ok:false as const,error:`${f.label} inválido.`};if(["integer","decimal","duration"].includes(f.type)&&(typeof v!=="number"||(f.type==="integer"&&!Number.isInteger(v))||(f.min!==undefined&&v<f.min)||(f.max!==undefined&&v>f.max)))return{ok:false as const,error:`${f.label} inválido.`};if(["single_select","rating_dimension"].includes(f.type)&&!f.options?.includes(String(v)))return{ok:false as const,error:`${f.label} inválido.`}}return{ok:true as const,value:data}}
export function transportCalculatedFields(p:Record<string,unknown>){const skipped=p.skipped_service===true;const minutes=(key:string)=>typeof p[key]==="string"&&/^\d{2}:\d{2}$/.test(p[key] as string)?Number((p[key] as string).slice(0,2))*60+Number((p[key] as string).slice(3)):null;const expected=minutes("expected_time"),observed=minutes("observed_time"),arrival=minutes("arrival_time");const diff=(a:number,b:number)=>((a-b)+1440)%1440;return{delay_minutes:skipped||expected===null||arrival===null?null:diff(arrival,expected),waiting_minutes:skipped||observed===null||arrival===null?null:diff(arrival,observed),skipped_service:skipped,observation_period:typeof p.date==="string"?String(p.date).slice(0,7):null}}
export function observationDedupHash(v:{observatoryId:string;line:string;stop?:string;occurredAt:string;direction?:string;kind?:string}){const window=Math.floor(new Date(v.occurredAt).getTime()/900000);return createHash("sha256").update([v.observatoryId,v.line,v.stop??"",window,v.direction??"",v.kind??""].join(":" )).digest("hex")}
export function median(values:number[]){if(!values.length)return null;const s=[...values].sort((a,b)=>a-b),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2}
export function percentile(values:number[],p:number){if(!values.length)return null;const s=[...values].sort((a,b)=>a-b),i=Math.ceil((p/100)*s.length)-1;return s[Math.max(0,Math.min(i,s.length-1))]}
export type AcceptedObservation={calculated_fields:Record<string,unknown>;payload:Record<string,unknown>};
export function aggregateTransport(rows:AcceptedObservation[],minimum=1,tolerance=5){if(rows.length<minimum)return{sampleSize:rows.length,insufficient:true as const,metrics:[]};const delays=rows.map(r=>r.calculated_fields.delay_minutes).filter((x):x is number=>typeof x==="number"),categories=(key:string)=>{const out:Record<string,number>={};for(const r of rows){const value=String(r.payload[key]??"não_observado");out[value]=(out[value]??0)+1}return out};return{sampleSize:rows.length,insufficient:false as const,metrics:[{slug:"total-observacoes",value:rows.length},{slug:"atraso-mediano",value:median(delays)},{slug:"atraso-medio",value:delays.length?delays.reduce((a,b)=>a+b,0)/delays.length:null},{slug:"atraso-p90",value:percentile(delays,90)},{slug:"dentro-tolerancia",value:delays.length?100*delays.filter(x=>x<=tolerance).length/delays.length:null},{slug:"acima-dez-minutos",value:delays.length?100*delays.filter(x=>x>10).length/delays.length:null},{slug:"servico-nao-passou",value:rows.filter(r=>r.calculated_fields.skipped_service===true).length},{slug:"lotacao",json:categories("crowding")},{slug:"acessibilidade",json:categories("accessibility")},{slug:"conservacao",json:categories("conservation")},{slug:"limpeza",json:categories("cleanliness")},{slug:"climatizacao",json:categories("climate")} ]}}
export function sanitizePublicSnapshot<T extends Record<string,unknown>>(x:T){const {internal_notes:_,private_contact:__,payload:___,...safe}=x;return safe}
