import { defineMiniapp } from "@/lib/miniapp-contract";

export const sidewalkMiniappDefinition = defineMiniapp({
  schemaVersion: 1,
  id: "mapa-das-calcadas",
  slug: "calcadas",
  title: "Calçadas de Volta Redonda",
  summary:
    "Ferramenta territorial da pauta para registrar barreiras e acompanhar prioridades, ações, resultados e memória.",
  canonicalModuleType: "map",
  routes: {
    home: "/comun/calcadas",
    contribution:
      "/comun/calcadas/contribuir",
    textAlternative: "/comun/calcadas?visualizacao=lista",
    participation: "/comun/minha-participacao",
    inbox: "/comun/inbox",
    administration: "/comun/admin/calcadas",
  },
  context: {
    pautaSlug: "calcadas-em-circulacao",
    communitySource: "canonical_pauta",
    territory: {
      slug: "volta-redonda",
      label: "Volta Redonda",
      coverageLabel: "Cobertura comunitária por adesão",
    },
  },
  primaryAction: {
    label: "Registrar calçada",
    route:
      "/comun/calcadas/contribuir",
  },
  contribution: {
    mode: "anonymous_limited",
    states: [
      "draft",
      "authorized",
      "confirmed",
      "under_review",
      "published",
      "rejected",
    ],
  },
  moderationStates: [
    "pending",
    "under_review",
    "information_requested",
    "approved",
    "rejected",
    "archived",
  ],
  followUpStates: [
    "under_review",
    "published",
    "priority",
    "forwarded",
    "waiting_response",
    "in_progress",
    "resolved",
    "reopened",
  ],
  permissions: {
    contribute: ["anonymous_limited", "authenticated"],
    moderate: ["admin", "editor"],
    operate: ["admin", "editor", "coordinator"],
  },
  publicProjection: [
    "slug",
    "name",
    "public_geometry_geojson",
    "categories",
    "condition",
    "forwarding_status",
    "verification_status",
    "public_summary",
    "approximate_location",
    "neighborhood",
    "last_observed_at",
    "resolved_at",
    "status",
    "visibility",
  ],
  politicalLinks: {
    collectiveAction: true,
    protocol: true,
    result: true,
    memory: true,
  },
  inboxEvents: [
    "information_requested",
    "published",
    "priority",
    "protocol_registered",
    "response_received",
    "resolved",
    "reopened",
  ],
  auditEvents: [
    "contribution_submitted",
    "moderation_decided",
    "priority_decided",
    "forwarding_changed",
    "field_observation_reviewed",
  ],
  privacy: {
    privateFields: [
      "private_geometry_geojson",
      "original_photo",
      "object_key",
      "member_user_id",
      "note_private",
      "signed_url",
    ],
    retentionPolicy:
      "Originais e dados privados seguem retenção operacional; somente derivadas aprovadas e projeções sanitizadas podem ser públicas.",
  },
  capabilities: [
    "map",
    "media_upload",
    "moderation",
    "field_verification",
    "territorial_grouping",
    "collective_action",
    "official_protocol",
    "public_result",
    "collective_memory",
  ],
});
