import Link from'next/link';import{AdminShell}from'@/components/admin-shell';import{requireComunAdmin}from'@/lib/admin-auth';import{createServiceSupabaseClient}from'@/lib/supabase/server';
export const dynamic='force-dynamic';export default async function Page({searchParams}:{searchParams:Promise<{origem?:string}>}){const[s,p]=await Promise.all([requireComunAdmin({roles:['admin','editor']}),searchParams]),db=createServiceSupabaseClient(),empty={data:[]};const[reports,contribs,photos,suggestions,rights,claims,participation]=db?await Promise.all([
db.from('comun_reports').select('id,protocol,title,status,risk_level,created_at').in('status',['received','under_review','needs_more_info']),
db.from('comun_pauta_contributions').select('id,contribution_type,status,risk_level,moderation_priority,created_at,pauta:comun_pauta_spaces(title)').eq('status','pending'),
db.from('comun_archive_submissions').select('id,title_suggestion,status,risk_level,created_at').in('status',['submitted','triage','research']),
db.from('comun_archive_item_suggestions').select('id,suggestion_type,status,risk_level,created_at').in('status',['pending','research']),
db.from('comun_archive_rights_removal_requests').select('id,request_type,status,created_at').in('status',['pending','reviewing']),
db.from('comun_archive_artist_claims').select('id,status,created_at').in('status',['pending','information_requested','under_review']),
db.from('comun_hub_participation_interests').select('id,status,created_at').eq('status','pending')]):[empty,empty,empty,empty,empty,empty,empty];let rows=[
...(reports.data??[]).map((x:any)=>({source:'relato',title:x.title??x.protocol,status:x.status,risk:x.risk_level,date:x.created_at,href:`/comun/admin/relatos/${x.id}`})),
...(contribs.data??[]).map((x:any)=>({source:'contribuição',title:`${x.contribution_type} · ${x.pauta?.title??'pauta'}`,status:x.status,risk:x.risk_level,date:x.created_at,href:'/comun/admin/pautas/contribuicoes'})),
...(photos.data??[]).map((x:any)=>({source:'fotografia',title:x.title_suggestion??'Fotografia recebida',status:x.status,risk:x.risk_level,date:x.created_at,href:`/comun/admin/acervo/contribuicoes/${x.id}`})),
...(suggestions.data??[]).map((x:any)=>({source:'sugestão',title:x.suggestion_type,status:x.status,risk:x.risk_level,date:x.created_at,href:'/comun/admin/acervo/sugestoes'})),
...(rights.data??[]).map((x:any)=>({source:'correção/retirada',title:x.request_type,status:x.status,risk:'attention',date:x.created_at,href:'/comun/admin/alertas'})),
...(claims.data??[]).map((x:any)=>({source:'reivindicação',title:'Perfil de artista',status:x.status,risk:'attention',date:x.created_at,href:'/comun/admin/acervo/artistas/reivindicacoes'})),
...(participation.data??[]).map((x:any)=>({source:'participação',title:'Disponibilidade para colaborar',status:x.status,risk:'private',date:x.created_at,href:'/comun/admin/organizacao'}))];if(p.origem)rows=rows.filter(x=>x.source===p.origem);return <AdminShell adminEmail={s.admin.email}><h1 className="text-3xl font-black uppercase">Caixa de entrada unificada</h1><p>Conteúdo privado permanece nas telas de origem; esta fila mostra apenas metadados operacionais.</p><form className="mt-5 flex gap-2"><select name="origem" defaultValue={p.origem??''}><option value="">Todas as origens</option>{[...new Set(rows.map(x=>x.source))].map(x=><option key={x}>{x}</option>)}</select><button className="btn">Filtrar</button></form><div className="mt-6 grid gap-2">{rows.sort((a,b)=>+new Date(b.date)-+new Date(a.date)).map((x,i)=><Link className="border-2 bg-white p-4" href={x.href} key={`${x.source}-${i}`}><p className="text-xs font-black uppercase">{x.source} · {x.status} · risco {x.risk}</p><h2 className="font-black">{x.title}</h2><small>{new Date(x.date).toLocaleString('pt-BR')} · abrir origem para vincular, pedir informação, arquivar, restringir ou rejeitar com justificativa</small></Link>)}</div></AdminShell>}
