"use server";
import { revalidatePath } from "next/cache";
import { requireComunAdmin } from "@/lib/admin-auth";
import { logComunAdminAction } from "@/lib/admin-audit";
import { upsertMemberInbox } from "@/lib/community-inbox";
import { createServiceSupabaseClient } from "@/lib/supabase/server";

export async function moderateIdentificationComment(formData:FormData){
 const session=await requireComunAdmin({roles:["admin","editor"]}),id=String(formData.get("id")),decision=String(formData.get("decision")),publicText=String(formData.get("public_text")||"").trim(),notes=String(formData.get("moderator_notes")||"").trim();
 if(!["research","needs_information","approved","rejected","archived"].includes(decision))throw new Error("Decisão inválida.");
 if(decision==="approved"&&publicText.length<10)throw new Error("Texto público insuficiente.");
 const db=createServiceSupabaseClient();if(!db)throw new Error("Banco indisponível.");
 const {data:comment,error}=await db.from("comun_archive_item_suggestions").update({status:decision,public_text:decision==="approved"?publicText:null,publication_status:decision==="approved"?"approved_public":"private",moderator_notes:notes||null,reviewed_at:new Date().toISOString()}).eq("id",id).select("archive_item_id,member_user_id,parent_id").single();if(error)throw error;
 const {data:item}=await db.from("comun_archive_identification_items").select("id,public_slug").eq("archive_item_id",comment.archive_item_id).maybeSingle();
 if(item){const {count}=await db.from("comun_archive_item_suggestions").select("id",{count:"exact",head:true}).eq("archive_item_id",comment.archive_item_id).eq("publication_status","approved_public");await db.from("comun_archive_identification_items").update({comment_count:count??0,research_state:(count??0)>0?"has_clues":"unidentified"}).eq("id",item.id);}
 if(comment.member_user_id&&item){const type=decision==="approved"?"archive_comment_approved":decision==="rejected"?"archive_comment_rejected":decision==="needs_information"?"archive_comment_needs_information":"contribution_update";await upsertMemberInbox({memberUserId:comment.member_user_id,type,title:decision==="approved"?"Contribuição aprovada":decision==="rejected"?"Contribuição não publicada":"Contribuição em revisão",summary:decision==="approved"?"Seu comentário já aparece na memória.":decision==="needs_information"?"A equipe precisa de mais informações.":"A curadoria atualizou o estado da contribuição.",actionLabel:"Ver memória",actionUrl:`/comun/acervo/identificar/${item.public_slug}`,dedupeKey:`archive-comment:${id}:${decision}`});}
 if(decision==="approved"&&comment.parent_id&&item){const {data:parent}=await db.from("comun_archive_item_suggestions").select("member_user_id").eq("id",comment.parent_id).maybeSingle();if(parent?.member_user_id&&parent.member_user_id!==comment.member_user_id)await upsertMemberInbox({memberUserId:parent.member_user_id,type:"archive_comment_reply",title:"Nova resposta aprovada",summary:"Uma resposta à sua contribuição foi publicada.",actionLabel:"Ver resposta",actionUrl:`/comun/acervo/identificar/${item.public_slug}`,dedupeKey:`archive-reply:${id}`});}
 await logComunAdminAction({session,action:"archive_identification_comment_moderated",targetType:"archive_suggestion",targetId:id,metadata:{decision,archive_item_id:comment.archive_item_id}});revalidatePath("/comun/admin/acervo/identificacao");if(item)revalidatePath(`/comun/acervo/identificar/${item.public_slug}`);
}

export async function saveIdentificationSummary(formData:FormData){
 const session=await requireComunAdmin({roles:["admin","editor"]}),itemId=String(formData.get("item_id")),status=String(formData.get("status"));if(!["draft","review","published","archived"].includes(status))throw new Error("Estado inválido.");const db=createServiceSupabaseClient();if(!db)throw new Error("Banco indisponível.");
 const payload={identification_item_id:itemId,confirmed_text:String(formData.get("confirmed_text")||"").trim()||null,open_questions_text:String(formData.get("open_questions_text")||"").trim()||null,disagreement_text:String(formData.get("disagreement_text")||"").trim()||null,editorial_basis_private:String(formData.get("editorial_basis_private")||"").trim()||null,status,published_by:status==="published"?session.admin.user_id:null,published_at:status==="published"?new Date().toISOString():null};
 const {error}=await db.from("comun_archive_identification_summaries").upsert(payload,{onConflict:"identification_item_id"});if(error)throw error;await db.from("comun_archive_identification_items").update({research_state:status==="published"?"partially_identified":"under_review"}).eq("id",itemId);await logComunAdminAction({session,action:"archive_identification_summary_updated",targetType:"archive_identification_item",targetId:itemId,metadata:{status}});revalidatePath("/comun/admin/acervo/identificacao");
}

export async function setIdentificationDisplayState(formData:FormData){const session=await requireComunAdmin({roles:["admin","editor"]}),id=String(formData.get("id")),state=String(formData.get("state"));if(!["open","paused","withdrawn"].includes(state))throw new Error("Estado inválido.");const db=createServiceSupabaseClient();if(!db)throw new Error("Banco indisponível.");await db.from("comun_archive_identification_items").update({display_state:state}).eq("id",id);await logComunAdminAction({session,action:"archive_identification_item_state_changed",targetType:"archive_identification_item",targetId:id,metadata:{state}});revalidatePath("/comun/admin/acervo/identificacao");revalidatePath("/comun/acervo/identificar");}

export async function setIdentificationCampaignState(formData:FormData){const session=await requireComunAdmin({roles:["admin"]}),id=String(formData.get("id")),state=String(formData.get("state"));if(!["open","paused","closed"].includes(state))throw new Error("Estado inválido.");const db=createServiceSupabaseClient();if(!db)throw new Error("Banco indisponível.");await db.from("comun_archive_identification_campaigns").update({state,opened_at:state==="open"?new Date().toISOString():undefined,closed_at:state==="closed"?new Date().toISOString():null}).eq("id",id);await logComunAdminAction({session,action:"archive_identification_campaign_state_changed",targetType:"archive_identification_campaign",targetId:id,metadata:{state}});revalidatePath("/comun/admin/acervo/identificacao");revalidatePath("/comun/acervo/identificar");}

export async function moderateIdentificationReport(formData:FormData){const session=await requireComunAdmin({roles:["admin","editor"]}),id=String(formData.get("id")),decision=String(formData.get("decision"));if(!["resolved","rejected","archived"].includes(decision))throw new Error("Decisão inválida.");const db=createServiceSupabaseClient();if(!db)throw new Error("Banco indisponível.");const{data,error}=await db.from("comun_archive_identification_reports").update({status:decision,reviewed_at:new Date().toISOString()}).eq("id",id).select("suggestion_id").single();if(error)throw error;if(decision==="rejected")await db.from("comun_archive_item_suggestions").update({publication_status:"approved_public"}).eq("id",data.suggestion_id).eq("status","approved");await logComunAdminAction({session,action:"archive_identification_report_moderated",targetType:"archive_identification_report",targetId:id,metadata:{decision}});revalidatePath("/comun/admin/acervo/identificacao");}
