import Link from "next/link";
import { notFound } from "next/navigation";
import { ComunShell } from "@/components/comun-shell";
import { isComunObservatoryEssentialPowerInterruptionEnabled } from "@/lib/comun-observatory-feature";
export const dynamic = "force-dynamic";
export default function EssentialServicesObservatoryPage() {
  if (!isComunObservatoryEssentialPowerInterruptionEnabled()) notFound();
  return <ComunShell><main className="mx-auto max-w-5xl px-4 py-8 text-comun-black sm:py-12"><p className="text-xs font-black uppercase text-comun-rust">Observatórios</p><h1 className="mt-2 text-4xl font-black uppercase tracking-[-.04em] sm:text-6xl">Serviços Essenciais</h1><p className="mt-4 max-w-3xl text-lg">Leituras públicas baseadas somente em fontes oficiais versionadas. Esta área não reúne relatos privados, Carteira ou encaminhamentos.</p><section className="mt-8 grid gap-4 sm:grid-cols-2"><article className="border-2 border-comun-black/25 bg-comun-paper p-5"><p className="text-xs font-black uppercase text-comun-rust">Disponível</p><h2 className="mt-2 text-2xl font-black uppercase">Energia elétrica</h2><p className="mt-2">Registros publicados de interrupção pela ANEEL para Volta Redonda, com período e limitações visíveis.</p><Link href="/comun/observatorios/servicos-essenciais/energia" className="mt-5 inline-flex min-h-11 items-center bg-comun-yellow px-4 font-black uppercase">Ver interrupções de energia</Link></article><article className="border-2 border-comun-black/20 bg-comun-paper p-5"><p className="text-xs font-black uppercase text-comun-black/60">Em preparação</p><h2 className="mt-2 text-2xl font-black uppercase">Água</h2><p className="mt-2">Ainda não há uma fonte pública periódica e metodologicamente suficiente para indicadores nesta superfície.</p></article><article className="border-2 border-comun-black/20 bg-comun-paper p-5"><p className="text-xs font-black uppercase text-comun-black/60">Em preparação</p><h2 className="mt-2 text-2xl font-black uppercase">Iluminação pública</h2><p className="mt-2">Ainda não há base pública periódica suficiente para formar indicadores seguros.</p></article></section></main></ComunShell>;
}
