"use client";
import { useState } from "react";

const choices = [["photo_or_document", "Uma foto ou documento"], ["art", "Uma obra de arte"], ["oral_history", "Uma pessoa ou história para entrevistar"], ["radio", "Algo para a Rádio"], ["unknown", "Ainda não sei"]] as const;
export function CulturalIntakeForm() {
  const [text, setText] = useState(""); const [state, setState] = useState<"idle" | "saving" | "saved" | "error">("idle"); const [protocol, setProtocol] = useState<string | null>(null); const [route, setRoute] = useState<string | null>(null);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setState("saving"); const response = await fetch("/api/comun/archive/contribution-intakes", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ intentText: text, requestId: crypto.randomUUID(), sourceSurface: "acervo_vivo" }) }); const body = await response.json().catch(() => ({})); if (!response.ok) { setState("error"); return; } setProtocol(body.protocol ?? null); setState("saved"); }
  async function choose(routeKind: string) { if (!protocol) return; const response = await fetch(`/api/comun/archive/contribution-intakes/${protocol}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ routeKind }) }); if (response.ok) setRoute(routeKind); }
  if (state === "saved") return <div role="status" tabIndex={-1} className="border-2 border-comun-yellow p-5"><h2 className="text-2xl font-black uppercase">Guardado de forma privada</h2><p className="mt-2">Antes de qualquer publicação, direitos e contexto serão verificados.</p>{protocol && <p className="mt-4 font-black">Protocolo COMUN: {protocol}</p>}<p className="mt-4 font-black">Como você quer continuar?</p><div className="mt-3 grid gap-2">{choices.map(([value, label]) => <button type="button" key={value} onClick={() => choose(value)} className="border-2 border-comun-black p-3 text-left">{label}</button>)}</div>{route && <p className="mt-4" role="status">Guardamos sua escolha. A continuidade especializada será preparada sem publicar nada.</p>}</div>;
  return <form onSubmit={submit} className="grid gap-4"><label htmlFor="cultural-intent" className="text-xl font-black">O que você quer guardar na memória da cidade?</label><textarea id="cultural-intent" required maxLength={10000} value={text} onChange={(event) => setText(event.target.value)} className="min-h-40 border-2 border-comun-black p-3" autoFocus /><button disabled={state === "saving"} className="w-fit border-2 border-comun-black bg-comun-yellow px-5 py-3 font-black">{state === "saving" ? "Guardando…" : "Guardar e continuar"}</button>{state === "error" && <p role="alert">Não foi possível guardar agora. Tente novamente.</p>}</form>;
}
