import { z } from "zod";
const id=z.string().uuid(),short=z.string().trim().max(240),common=z.object({}).strict();
export const pautaModuleTypes=["overview","construction_circle","reports","evidence","map","observatory","metrics","documents","timeline","proposals","actions","tasks","calendar","results","archive","participation","art_gallery","community_radio"] as const;
export type PautaModuleType=typeof pautaModuleTypes[number];
type Entry={type:PautaModuleType;defaultTitle:string;description:string;componentKey:string;configSchema:z.ZodTypeAny;publicAllowed:boolean;participantAllowed:boolean;internalAllowed:boolean;requirements:string[];emptyState:string;iconKey:string;futureModule:boolean};
const entry=(type:PautaModuleType,title:string,description:string,configSchema:z.ZodTypeAny=common,futureModule=false):Entry=>({type,defaultTitle:title,description,componentKey:type,configSchema,publicAllowed:!futureModule,participantAllowed:true,internalAllowed:true,requirements:[],emptyState:futureModule?"Em preparação para uma futura etapa.":"Ainda não há conteúdo disponível neste módulo.",iconKey:type,futureModule});
const base=(type:PautaModuleType,title:string,description:string)=>entry(type,title,description);
export const pautaModuleRegistry:Record<PautaModuleType,Entry>={
 overview:base("overview","Visão geral","Contexto, etapa e próxima ação."), construction_circle:entry("construction_circle","Roda de construção","Conversa organizada por rodadas.",z.object({circleId:id.optional(),showPreviousRounds:z.boolean().default(true),showSynthesis:z.boolean().default(true),allowPublicContribution:z.boolean().default(true)}).strict()), reports:base("reports","Relatos","Relatos sanitizados relacionados."), evidence:base("evidence","Evidências","Evidências revisadas."), map:entry("map","Mapa","Recorte territorial.",z.object({layerIds:z.array(id).max(20).default([]),territoryIds:z.array(id).max(20).default([]),contributionEnabled:z.boolean().default(false),defaultView:z.enum(["map","list"]).default("map")}).strict()), observatory:entry("observatory","Observatório","Indicadores e metodologia.",z.object({observatoryId:id.optional(),showMetrics:z.boolean().default(true),showMethodology:z.boolean().default(true),showCampaigns:z.boolean().default(false)}).strict()), metrics:base("metrics","Indicadores","Indicadores agregados."), documents:base("documents","Documentos","Documentos públicos relacionados."), timeline:base("timeline","Linha do tempo","Atualizações verificadas."), proposals:base("proposals","Propostas","Propostas em construção."), actions:base("actions","Ações","Ações coletivas."), tasks:base("tasks","Tarefas","Tarefas e ofertas de ajuda."), calendar:base("calendar","Calendário","Próximas datas."), results:base("results","Resultados","Resultados e retornos."), archive:entry("archive","Acervo","Memória relacionada.",z.object({collectionIds:z.array(id).max(20).default([]),relationTypes:z.array(short).max(12).default([]),limit:z.number().int().min(1).max(24).default(6)}).strict()), participation:base("participation","Participação","Próximas formas de contribuir."), art_gallery:entry("art_gallery","Arte dos territórios","Obras publicadas e relacionadas.",z.object({collectionIds:z.array(id).max(20).default([]),artworkIds:z.array(id).max(24).default([]),relationTypes:z.array(short).max(12).default([]),territoryIds:z.array(id).max(20).default([]),limit:z.number().int().min(1).max(12).default(6),showCreators:z.boolean().default(true),contributionEnabled:z.boolean().default(false)}).strict()), community_radio:entry("community_radio","Rádio comunitária","Programas e episódios publicados ligados à pauta.",z.object({programIds:z.array(id).max(20).default([]),episodeIds:z.array(id).max(24).default([]),relationTypes:z.array(short).max(12).default([]),territoryIds:z.array(id).max(20).default([]),limit:z.number().int().min(1).max(12).default(6),showSchedule:z.boolean().default(true),contributionEnabled:z.boolean().default(true),showTranscript:z.boolean().default(true)}).strict())
};
export function validatePautaModuleConfig(type:PautaModuleType,value:unknown){return pautaModuleRegistry[type].configSchema.safeParse(value)}
export const pautaAppTemplates={investigacao:["overview","reports","evidence","construction_circle","timeline","actions","results"],mapeamento:["overview","map","reports","evidence","construction_circle","actions","results","archive"],observatorio:["overview","observatory","metrics","construction_circle","actions","results"],mobilizacao:["overview","construction_circle","proposals","actions","tasks","calendar","results","participation"],apoio_comunitario:["overview","reports","construction_circle","tasks","participation","results"],memoria:["overview","archive","timeline","construction_circle","results"],projeto_territorial:["overview","map","construction_circle","actions","tasks","results"],accessible_sidewalk_mapping:["overview","reports","map","observatory","evidence","construction_circle","proposals","actions","tasks","results","art_gallery","community_radio","archive","participation"]} as const;
