'use server';
import { redirect } from 'next/navigation';
import { revalidatePath } from 'next/cache';
import { requireComunAdmin } from '@/lib/admin-auth';
import { logComunAdminAction } from '@/lib/admin-audit';
import { createServiceSupabaseClient } from '@/lib/supabase/server';
import { canPublishOralHistory, sanitizeOralHistorySnapshot } from '@/lib/archive/oral-history-rules';

const text = (form: FormData, key: string) => String(form.get(key) ?? '').trim();
const yes = (form: FormData, key: string) => form.get(key) === 'on' || form.get(key) === 'true';
async function version(db: any, item: string, entityType: string, entityId: string | null, changeType: string, snapshot: unknown, by: string) {
  await db.from('comun_archive_oral_history_editorial_versions').insert({ oral_history_item_id: item, entity_type: entityType, entity_id: entityId, change_type: changeType, sanitized_snapshot: sanitizeOralHistorySnapshot(snapshot), changed_by: by });
}

export async function createOralHistory(form: FormData) {
  const session = await requireComunAdmin({ roles: ['admin', 'editor'] }); const db = createServiceSupabaseClient(); if (!db) throw new Error('Banco indisponível');
  const title = text(form, 'title'), slug = text(form, 'slug'); if (!title || !/^[a-z0-9-]+$/.test(slug)) throw new Error('Título e slug válido são obrigatórios.');
  const item = await db.from('comun_archive_items').insert({ slug, item_type: 'oral_history', title, summary: text(form, 'public_summary') || null, city: text(form, 'city') || null, neighborhood: text(form, 'neighborhood') || null, source_name: 'Entrevista registrada pelo COMUN', rights_status: 'permission_granted', status: 'draft', visibility: 'private' }).select('id').single(); if (item.error) throw new Error(item.error.message);
  const history = await db.from('comun_archive_oral_histories').insert({ archive_item_id: item.data.id, interview_title: title, interview_date: text(form, 'interview_date') || null, interview_date_approximate: yes(form, 'interview_date_approximate'), recording_location_public: text(form, 'recording_location_public') || null, recording_location_private: text(form, 'recording_location_private') || null, public_summary: text(form, 'public_summary') || null, internal_summary: text(form, 'internal_summary') || null, publication_status: 'consent_pending' }); if (history.error) { await db.from('comun_archive_items').delete().eq('id', item.data.id); throw new Error(history.error.message); }
  await version(db, item.data.id, 'oral_history', item.data.id, 'created', { title, slug }, session.admin.email); await logComunAdminAction({ session, action: 'oral_history_created', targetType: 'archive_item', targetId: item.data.id }); redirect(`/comun/admin/acervo/historias-orais/${item.data.id}`);
}

export async function saveParticipant(form: FormData) {
  const session = await requireComunAdmin({ roles: ['admin', 'editor'] }); const db = createServiceSupabaseClient(); if (!db) throw new Error('Banco indisponível');
  const item = text(form, 'oral_history_item_id'), id = text(form, 'id'); const payload = { oral_history_item_id: item, participant_role: text(form, 'participant_role') || 'interviewee', public_name: text(form, 'public_name') || null, private_name: text(form, 'private_name') || null, preferred_identification: text(form, 'preferred_identification') || 'anonymous', biography_public: text(form, 'biography_public') || null, contact_private: text(form, 'contact_private') || null, representative_contact_private: text(form, 'representative_contact_private') || null, is_minor: yes(form, 'is_minor'), participation_status: text(form, 'participation_status') || 'pending', position: Number(text(form, 'position')) || 0, updated_at: new Date().toISOString() };
  const result = id ? await db.from('comun_archive_oral_history_participants').update(payload).eq('id', id).select('id').single() : await db.from('comun_archive_oral_history_participants').insert(payload).select('id').single(); if (result.error) throw new Error(result.error.message);
  await version(db, item, 'participant', result.data.id, id ? 'updated' : 'created', payload, session.admin.email); await logComunAdminAction({ session, action: 'oral_history_participant_added', targetType: 'oral_history_participant', targetId: result.data.id }); revalidatePath(`/comun/admin/acervo/historias-orais/${item}`);
}

export async function saveConsent(form: FormData) {
  const session = await requireComunAdmin({ roles: ['admin', 'editor'] }); const db = createServiceSupabaseClient(); if (!db) throw new Error('Banco indisponível');
  const item = text(form, 'oral_history_item_id'), participant = text(form, 'participant_id'), documentId = text(form, 'consent_document_asset_id') || null;
  if (documentId) { const asset = await db.from('comun_archive_assets').select('bucket_scope,asset_role,archive_item_id').eq('id', documentId).maybeSingle(); if (!asset.data || asset.data.archive_item_id !== item || asset.data.bucket_scope !== 'private_original' || asset.data.asset_role !== 'oral_history_consent_document') throw new Error('Termo deve ser um asset privado desta entrevista.'); }
  const payload: any = { oral_history_item_id: item, participant_id: participant, template_id: text(form,'template_id') || null, template_version: text(form,'template_version') || null, presented_at: text(form,'presented_at') || new Date().toISOString(), acceptance_method: text(form,'acceptance_method') || null, consent_stage: text(form,'consent_stage') || 'initial', supersedes_consent_id: text(form,'supersedes_consent_id') || null, publication_identity_presented: yes(form,'publication_identity_presented'), publication_text_presented: yes(form,'publication_text_presented'), publication_audio_presented: yes(form,'publication_audio_presented'), publication_image_presented: yes(form,'publication_image_presented'), consent_status: text(form, 'consent_status') || 'pending', consent_document_asset_id: documentId, valid_from: text(form, 'valid_from') || null, valid_until: text(form, 'valid_until') || null, guardian_consent: yes(form, 'guardian_consent'), recorded_by: session.admin.email, reviewed_by: session.admin.email, reviewed_at: new Date().toISOString(), private_notes: text(form, 'private_notes') || null, updated_at: new Date().toISOString() };
  for (const field of ['allow_preservation_private','allow_internal_transcription','allow_public_transcript','allow_public_audio_excerpt','allow_public_full_audio','allow_public_image','allow_public_name','allow_educational_use','allow_exhibition_use','allow_social_media_use','allow_download']) payload[field] = yes(form, field);
  const consentId=text(form,'consent_id'); const result = consentId ? await db.from('comun_archive_oral_history_consents').update(payload).eq('id',consentId).select('id').single() : await db.from('comun_archive_oral_history_consents').insert(payload).select('id').single(); if (result.error) throw new Error(result.error.message);
  await db.from('comun_archive_oral_history_participants').update({ participation_status: ['granted','partially_granted'].includes(payload.consent_status) ? 'consented' : payload.consent_status === 'withdrawn' ? 'withdrawn' : 'pending' }).eq('id', participant);
  await version(db, item, 'consent', result.data.id, payload.consent_status === 'withdrawn' ? 'withdrawn' : 'recorded', payload, session.admin.email); await logComunAdminAction({ session, action: payload.consent_status === 'withdrawn' ? 'oral_history_consent_withdrawn' : 'oral_history_consent_recorded', targetType: 'oral_history_consent', targetId: result.data.id });
  if (payload.consent_status === 'withdrawn') await withdrawOralHistoryInternal(db, session, item, participant);
  revalidatePath(`/comun/admin/acervo/historias-orais/${item}`);
}

export async function saveTranscript(form: FormData) {
  const session = await requireComunAdmin({ roles: ['admin', 'editor'] }); const db = createServiceSupabaseClient(); if (!db) throw new Error('Banco indisponível'); const item = text(form, 'oral_history_item_id'), type = text(form, 'transcript_type');
  const latest = await db.from('comun_archive_oral_history_transcript_versions').select('version_number').eq('oral_history_item_id', item).eq('transcript_type', type).order('version_number', { ascending: false }).limit(1).maybeSingle();
  const payload = { oral_history_item_id: item, transcript_type: type, version_number: (latest.data?.version_number ?? 0) + 1, content: text(form, 'content'), language: text(form, 'language') || 'pt-BR', status: text(form, 'status') || 'draft', source: text(form, 'source') || 'manual', contains_redactions: yes(form, 'contains_redactions'), editor_note: text(form, 'editor_note') || null, created_by: session.admin.email };
  if (!payload.content) throw new Error('Transcrição vazia.'); const result = await db.from('comun_archive_oral_history_transcript_versions').insert(payload).select('id').single(); if (result.error) throw new Error(result.error.message);
  await db.from('comun_archive_oral_histories').update({ transcript_status: type === 'internal_full' ? 'approved_internal' : payload.status === 'approved' ? 'approved_public' : 'review', updated_at: new Date().toISOString() }).eq('archive_item_id', item);
  await version(db, item, 'transcript', result.data.id, type === 'internal_full' ? 'imported' : 'public_version_created', { ...payload, content: `[texto preservado em versão ${payload.version_number}]` }, session.admin.email); await logComunAdminAction({ session, action: type === 'internal_full' ? 'oral_history_transcript_imported' : 'oral_history_public_version_created', targetType: 'oral_history_transcript', targetId: result.data.id }); revalidatePath(`/comun/admin/acervo/historias-orais/${item}`);
}

export async function saveSegment(form: FormData) {
  const session = await requireComunAdmin({ roles: ['admin', 'editor'] }); const db = createServiceSupabaseClient(); if (!db) throw new Error('Banco indisponível'); const item = text(form, 'oral_history_item_id'); const payload = { oral_history_item_id: item, transcript_version_id: text(form, 'transcript_version_id') || null, start_seconds: text(form, 'start_seconds') ? Number(text(form, 'start_seconds')) : null, end_seconds: text(form, 'end_seconds') ? Number(text(form, 'end_seconds')) : null, speaker_label: text(form, 'speaker_label') || null, internal_text: text(form, 'internal_text') || null, public_text: text(form, 'public_text') || null, sensitivity: text(form, 'sensitivity') || 'normal', publication_status: text(form, 'publication_status') || 'private', editorial_note_private: text(form, 'editorial_note_private') || null };
  const result = await db.from('comun_archive_oral_history_segments').insert(payload).select('id').single(); if (result.error) throw new Error(result.error.message); await version(db, item, 'segment', result.data.id, 'restricted', payload, session.admin.email); await logComunAdminAction({ session, action: 'oral_history_segment_restricted', targetType: 'oral_history_segment', targetId: result.data.id }); revalidatePath(`/comun/admin/acervo/historias-orais/${item}`);
}

export async function updateOralHistoryWorkflow(form: FormData) {
  const session = await requireComunAdmin({ roles: ['admin', 'editor'] }); const db = createServiceSupabaseClient(); if (!db) throw new Error('Banco indisponível'); const item = text(form, 'oral_history_item_id'), action = text(form, 'workflow');
  if (action === 'publish') {
    const [history, participants, consents, transcripts, segments, assets, approvals, thirdParty, work, originals, custody] = await Promise.all([db.from('comun_archive_oral_histories').select('*').eq('archive_item_id', item).single(), db.from('comun_archive_oral_history_participants').select('id,participant_role,participation_status,is_minor').eq('oral_history_item_id', item), db.from('comun_archive_oral_history_consents').select('*').eq('oral_history_item_id', item), db.from('comun_archive_oral_history_transcript_versions').select('id').eq('oral_history_item_id', item).in('transcript_type',['public_edited','public_excerpt']).eq('status','approved'), db.from('comun_archive_oral_history_segments').select('id').eq('oral_history_item_id', item).in('publication_status',['private','review']).neq('sensitivity','normal'), db.from('comun_archive_assets').select('asset_role').eq('archive_item_id', item).eq('bucket_scope','public_safe').eq('review_status','approved').in('asset_role',['oral_history_public_audio_excerpt','oral_history_public_full_audio']),db.from('comun_archive_oral_history_participant_approvals').select('participant_id,approval_status,expires_at,approved_transcript').eq('oral_history_item_id',item),db.from('comun_archive_oral_history_third_party_statements').select('id').eq('oral_history_item_id',item).in('status',['pending_review','legal_review_required']),db.from('comun_archive_oral_history_transcription_work').select('fidelity_review_status,risk_review_status').eq('oral_history_item_id',item).maybeSingle(),db.from('comun_archive_assets').select('id,bucket_scope').eq('archive_item_id',item).eq('asset_role','oral_history_original_audio'),db.from('comun_archive_asset_custody_events').select('asset_id,event_type,comun_archive_assets!inner(archive_item_id)').eq('comun_archive_assets.archive_item_id',item)]);
    const audio = assets.data?.[0]?.asset_role; const finalConsents=(consents.data??[]).filter((c:any)=>c.consent_stage==='publication_final'); const gate = canPublishOralHistory({ publicationStatus: 'approved', embargoUntil: history.data.embargo_until, participants: participants.data ?? [], consents: finalConsents, hasApprovedPublicTranscript: Boolean(transcripts.data?.length), hasRestrictedSegmentPending: Boolean(segments.data?.length), hasPublicAudio: Boolean(audio), publicAudioKind: audio === 'oral_history_public_full_audio' ? 'full' : 'excerpt' }); const extra:string[]=[];const now=new Date();for(const p of (participants.data??[]).filter((x:any)=>x.participant_role==='interviewee')){const approval=(approvals.data??[]).find((x:any)=>x.participant_id===p.id);if(!approval||!['approved','partially_approved'].includes(approval.approval_status)||!approval.approved_transcript||(approval.expires_at&&new Date(approval.expires_at)<now))extra.push(`participant_approval_invalid:${p.id}`)}if(thirdParty.data?.length)extra.push('third_party_review_pending');if(work.data?.fidelity_review_status!=='approved')extra.push('fidelity_review_missing');if(work.data?.risk_review_status!=='approved')extra.push('risk_review_missing');if((originals.data??[]).some((x:any)=>x.bucket_scope!=='private_original'))extra.push('original_not_private');const events=new Set((custody.data??[]).map((x:any)=>x.event_type));if(originals.data?.length&&!events.has('checksum_verified'))extra.push('checksum_missing');if(originals.data?.length&&!events.has('backup_confirmed'))extra.push('backup_missing'); if(!gate.allowed||extra.length) throw new Error(`Publicação bloqueada: ${[...gate.reasons,...extra].join(', ')}`);
    await db.from('comun_archive_oral_histories').update({ publication_status: 'published', updated_at: new Date().toISOString() }).eq('archive_item_id', item); await db.from('comun_archive_items').update({ status: 'published', visibility: 'public', published_at: new Date().toISOString() }).eq('id', item); await logComunAdminAction({ session, action: 'oral_history_published', targetType: 'archive_item', targetId: item });
  } else if (action === 'review') { await db.from('comun_archive_oral_histories').update({ publication_status: 'editorial_review' }).eq('archive_item_id', item); await logComunAdminAction({ session, action: 'oral_history_sent_to_review', targetType: 'archive_item', targetId: item }); }
  else if (action === 'approve') await db.from('comun_archive_oral_histories').update({ publication_status: 'approved' }).eq('archive_item_id', item);
  else if (action === 'unpublish') { await db.from('comun_archive_oral_histories').update({ publication_status: 'approved' }).eq('archive_item_id', item); await db.from('comun_archive_items').update({ status: 'unpublished', visibility: 'private' }).eq('id', item); await logComunAdminAction({ session, action: 'oral_history_unpublished', targetType: 'archive_item', targetId: item }); }
  else if (action === 'embargo') { const until = text(form, 'embargo_until'); await db.from('comun_archive_oral_histories').update({ embargo_until: until || null, publication_status: until ? 'embargoed' : 'approved' }).eq('archive_item_id', item); await db.from('comun_archive_items').update({ status: 'unpublished', visibility: 'private' }).eq('id', item); await logComunAdminAction({ session, action: 'oral_history_embargo_updated', targetType: 'archive_item', targetId: item }); }
  else if (action === 'withdraw') await withdrawOralHistoryInternal(db, session, item, null);
  await version(db, item, 'oral_history', item, action, { workflow: action, embargo_until: text(form, 'embargo_until') || null }, session.admin.email); revalidatePath(`/comun/admin/acervo/historias-orais/${item}`); revalidatePath('/comun/acervo/historias-orais');
}

export async function reviewOralHistoryAsset(form: FormData) {
  const session = await requireComunAdmin({ roles: ['admin', 'editor'] }); const db = createServiceSupabaseClient(); if (!db) throw new Error('Banco indisponível'); const id = text(form,'asset_id'), status = text(form,'review_status');
  const asset = await db.from('comun_archive_assets').select('id,archive_item_id,asset_role,bucket_scope').eq('id',id).single(); if (!asset.data || !['approved','rejected','archived'].includes(status)) throw new Error('Asset inválido.');
  if (status === 'approved' && asset.data.bucket_scope === 'public_safe' && asset.data.asset_role.includes('audio')) { const consents = await db.from('comun_archive_oral_history_consents').select('consent_status,allow_public_audio_excerpt,allow_public_full_audio,valid_until').eq('oral_history_item_id',asset.data.archive_item_id); const full=asset.data.asset_role==='oral_history_public_full_audio'; if (!consents.data?.length || consents.data.some((c:any)=>!['granted','partially_granted'].includes(c.consent_status)||(full?!c.allow_public_full_audio:!c.allow_public_audio_excerpt)||(c.valid_until&&new Date(`${c.valid_until}T23:59:59Z`)<new Date()))) throw new Error('Áudio público sem consentimento compatível.'); }
  const result=await db.from('comun_archive_assets').update({review_status:status}).eq('id',id);if(result.error)throw new Error(result.error.message);await logComunAdminAction({session,action:'oral_history_public_asset_reviewed',targetType:'archive_asset',targetId:id,metadata:{status,asset_role:asset.data.asset_role}});revalidatePath(`/comun/admin/acervo/historias-orais/${asset.data.archive_item_id}`);
}

async function withdrawOralHistoryInternal(db: any, session: any, item: string, participant: string | null) {
  await db.from('comun_archive_oral_histories').update({ publication_status: 'withdrawn', updated_at: new Date().toISOString() }).eq('archive_item_id', item); await db.from('comun_archive_items').update({ status: 'unpublished', visibility: 'private' }).eq('id', item); await db.from('comun_archive_assets').update({ review_status: 'archived', public_url: null }).eq('archive_item_id', item).eq('bucket_scope', 'public_safe'); await db.from('comun_archive_oral_history_withdrawals').insert({ oral_history_item_id: item, participant_id: participant, request_type: 'withdrawal', status: 'completed', completed_at: new Date().toISOString(), handled_by: session.admin.email }); await logComunAdminAction({ session, action: 'oral_history_withdrawal_completed', targetType: 'archive_item', targetId: item });
}
