'use server';
import { revalidatePath } from 'next/cache';
import { requireComunAdmin } from '@/lib/admin-auth';
import { logComunAdminAction } from '@/lib/admin-audit';
import { createServiceSupabaseClient } from '@/lib/supabase/server';
import { REQUIRED_FIELD_CHECKS, sanitizedCustodyMetadata } from '@/lib/archive/oral-history-pilot-rules';

const text=(f:FormData,k:string)=>String(f.get(k)??'').trim();
const yes=(f:FormData,k:string)=>['on','true','1'].includes(String(f.get(k)??''));
async function context(roles:('admin'|'editor')[]=['admin','editor']){const session=await requireComunAdmin({roles});const db=createServiceSupabaseClient();if(!db)throw new Error('Banco indisponível');return{session,db}}
const refresh=(item?:string)=>{revalidatePath('/comun/admin/acervo/historias-orais/piloto');revalidatePath('/comun/admin/acervo/historias-orais/transcricoes/trabalho');if(item)revalidatePath(`/comun/admin/acervo/historias-orais/${item}`)};

export async function saveConsentTemplate(f:FormData){const{session,db}=await context(['admin']);const id=text(f,'id'),status=text(f,'status')||'draft';const payload={template_type:text(f,'template_type'),version:text(f,'version'),title:text(f,'title'),public_explanation:text(f,'public_explanation'),status,valid_from:text(f,'valid_from')||null,approved_by:status==='approved'?session.admin.email:null,approved_at:status==='approved'?new Date().toISOString():null,retired_at:status==='retired'?new Date().toISOString():null,updated_at:new Date().toISOString()};if(!payload.version||!payload.title||!payload.public_explanation)throw new Error('Versão, título e explicação pública são obrigatórios.');const q=id?await db.from('comun_archive_consent_templates').update(payload).eq('id',id).select('id').single():await db.from('comun_archive_consent_templates').insert(payload).select('id').single();if(q.error)throw new Error(q.error.message);await logComunAdminAction({session,action:'oral_history_consent_template_saved',targetType:'consent_template',targetId:q.data.id,metadata:{status,version:payload.version}});refresh()}
export async function saveLegalReview(f:FormData){const{session,db}=await context(['admin']);const payload={template_id:text(f,'template_id'),reviewer_reference:text(f,'reviewer_reference'),reviewed_at:text(f,'reviewed_at')||new Date().toISOString(),reviewed_version:text(f,'reviewed_version'),pending_items:text(f,'pending_items')||null,decision:text(f,'decision')||'pending',review_due_at:text(f,'review_due_at')||null};if(!payload.reviewer_reference||!payload.reviewed_version)throw new Error('Referência do revisor e versão são obrigatórias.');const q=await db.from('comun_archive_consent_legal_reviews').insert(payload).select('id').single();if(q.error)throw new Error(q.error.message);await logComunAdminAction({session,action:'oral_history_legal_review_recorded',targetType:'consent_legal_review',targetId:q.data.id});refresh()}
export async function saveConsentSession(f:FormData){const{session,db}=await context();const item=text(f,'oral_history_item_id');const payload={oral_history_item_id:item,participant_id:text(f,'participant_id'),consent_id:text(f,'consent_id')||null,session_type:text(f,'session_type'),explained_by:session.admin.email,occurred_at:text(f,'occurred_at')||new Date().toISOString(),participant_questions_summary_private:text(f,'participant_questions_summary_private')||null,comprehension_confirmed:yes(f,'comprehension_confirmed'),withdrawal_process_explained:yes(f,'withdrawal_process_explained'),publication_scope_explained:yes(f,'publication_scope_explained'),preservation_scope_explained:yes(f,'preservation_scope_explained')};const q=await db.from('comun_archive_oral_history_consent_sessions').insert(payload).select('id').single();if(q.error)throw new Error(q.error.message);await logComunAdminAction({session,action:'oral_history_consent_session_recorded',targetType:'consent_session',targetId:q.data.id});refresh(item)}
export async function saveInterviewPlan(f:FormData){const{session,db}=await context();const item=text(f,'oral_history_item_id');const payload:any={oral_history_item_id:item,objective_public:text(f,'objective_public')||null,themes_public:text(f,'themes_public').split(',').map(x=>x.trim()).filter(Boolean),responsible_editor:text(f,'responsible_editor')||session.admin.email,next_action:text(f,'next_action')||null,blockers_private:text(f,'blockers_private')||null,pilot_stage:text(f,'pilot_stage')||'indicated',risk_level:text(f,'risk_level')||'low',updated_at:new Date().toISOString()};for(const k of [...REQUIRED_FIELD_CHECKS,'interviewer_prepared','consent_confirmed'])payload[k]=yes(f,k);payload.recording_check_completed=REQUIRED_FIELD_CHECKS.every(k=>payload[k]);const q=await db.from('comun_archive_oral_history_interview_plans').upsert(payload,{onConflict:'oral_history_item_id'}).select('id').single();if(q.error)throw new Error(q.error.message);await logComunAdminAction({session,action:'oral_history_interview_plan_saved',targetType:'interview_plan',targetId:q.data.id,metadata:{stage:payload.pilot_stage,risk:payload.risk_level,checklist_complete:payload.recording_check_completed}});refresh(item)}
export async function saveCustodyEvent(f:FormData){const{session,db}=await context();const assetId=text(f,'asset_id');const asset=await db.from('comun_archive_assets').select('archive_item_id,bucket_scope,size_bytes,checksum_sha256').eq('id',assetId).single();if(!asset.data)throw new Error('Asset inexistente.');if(['uploaded_private','checksum_verified','backup_confirmed'].includes(text(f,'event_type'))&&asset.data.bucket_scope!=='private_original')throw new Error('Custódia do original exige asset privado.');const payload={asset_id:assetId,event_type:text(f,'event_type'),performed_by:session.admin.email,sanitized_metadata:sanitizedCustodyMetadata({size_bytes:asset.data.size_bytes,checksum_present:Boolean(asset.data.checksum_sha256),note:text(f,'note')||undefined})};const q=await db.from('comun_archive_asset_custody_events').insert(payload).select('id').single();if(q.error)throw new Error(q.error.message);await logComunAdminAction({session,action:'oral_history_custody_event_recorded',targetType:'asset_custody_event',targetId:q.data.id,metadata:{event_type:payload.event_type}});refresh(asset.data.archive_item_id)}
export async function saveTranscriptionWork(f:FormData){const{session,db}=await context();const item=text(f,'oral_history_item_id');const payload={oral_history_item_id:item,assignee:text(f,'assignee')||session.admin.email,started_at:text(f,'started_at')||new Date().toISOString(),approximate_progress:Number(text(f,'approximate_progress')||0),last_edited_at:new Date().toISOString(),pending_items_private:text(f,'pending_items_private')||null,fidelity_review_status:text(f,'fidelity_review_status')||'pending',risk_review_status:text(f,'risk_review_status')||'pending',fidelity_reviewed_by:text(f,'fidelity_review_status')==='approved'?session.admin.email:null,risk_reviewed_by:text(f,'risk_review_status')==='approved'?session.admin.email:null,editorial_minutes:Number(text(f,'editorial_minutes')||0),revision_count:Number(text(f,'revision_count')||0),audio_duration_seconds:text(f,'audio_duration_seconds')?Number(text(f,'audio_duration_seconds')):null,transcript_character_count:Number(text(f,'transcript_character_count')||0),updated_at:new Date().toISOString()};const q=await db.from('comun_archive_oral_history_transcription_work').upsert(payload,{onConflict:'oral_history_item_id'}).select('id').single();if(q.error)throw new Error(q.error.message);await logComunAdminAction({session,action:'oral_history_transcription_work_saved',targetType:'transcription_work',targetId:q.data.id,metadata:{progress:payload.approximate_progress}});refresh(item)}
export async function saveThirdPartyStatement(f:FormData){const{session,db}=await context();const item=text(f,'oral_history_item_id');const payload={oral_history_item_id:item,segment_id:text(f,'segment_id')||null,claim_nature_private:text(f,'claim_nature_private'),referenced_party_private:text(f,'referenced_party_private')||null,additional_source_private:text(f,'additional_source_private')||null,risk_level:text(f,'risk_level')||'moderate',decision_private:text(f,'decision_private')||null,response_right_required:yes(f,'response_right_required'),treatment:text(f,'treatment')||null,status:text(f,'status')||'pending_review',updated_at:new Date().toISOString()};const id=text(f,'id');const q=id?await db.from('comun_archive_oral_history_third_party_statements').update(payload).eq('id',id).select('id').single():await db.from('comun_archive_oral_history_third_party_statements').insert(payload).select('id').single();if(q.error)throw new Error(q.error.message);await logComunAdminAction({session,action:'oral_history_third_party_statement_reviewed',targetType:'third_party_statement',targetId:q.data.id,metadata:{status:payload.status,risk:payload.risk_level}});refresh(item)}
export async function saveParticipantApproval(f:FormData){const{session,db}=await context();const item=text(f,'oral_history_item_id'),status=text(f,'approval_status')||'pending';const payload={oral_history_item_id:item,participant_id:text(f,'participant_id'),transcript_version_id:text(f,'transcript_version_id')||null,public_audio_asset_id:text(f,'public_audio_asset_id')||null,approval_status:status,approved_identity:text(f,'approved_identity')||null,approved_at:['approved','partially_approved'].includes(status)?new Date().toISOString():null,expires_at:text(f,'expires_at')||null,requested_changes_private:text(f,'requested_changes_private')||null,evidence_asset_id:text(f,'evidence_asset_id')||null,approved_transcript:yes(f,'approved_transcript'),approved_audio:yes(f,'approved_audio'),approved_image:yes(f,'approved_image'),updated_at:new Date().toISOString()};const q=await db.from('comun_archive_oral_history_participant_approvals').insert(payload).select('id').single();if(q.error)throw new Error(q.error.message);await logComunAdminAction({session,action:'oral_history_participant_approval_recorded',targetType:'participant_approval',targetId:q.data.id,metadata:{status}});refresh(item)}
