import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ComunShell,Section } from "@/components/comun-shell";
import { getOptionalCommunitySession } from "@/lib/community-auth";
import { getIdentificationItem,identificationTypeLabels,identificationTypes } from "@/lib/archive-identification";
import { reportIdentificationComment,submitIdentificationComment } from "../actions";
export const dynamic="force-dynamic";
export default async function Page({params,searchParams}:{params:Promise<{slug:string}>,searchParams:Promise<Record<string,string|undefined>>}){
 const {slug}=await params,q=await searchParams,data=await getIdentificationItem(slug);if(!data)notFound();const session=await getOptionalCommunitySession(),{item,comments,summary}=data as any,replies=(id:string)=>comments.filter((x:any)=>x.parent_id===id&&x.publication_status==='approved_public'),roots=comments.filter((x:any)=>!x.parent_id&&x.publication_status==='approved_public'||(!x.parent_id&&x.status==='withdrawn'&&replies(x.id).length));
 return <ComunShell><Section><Link href="/comun/acervo/identificar" className="font-black uppercase text-comun-yellow">← Todas as memórias</Link><article className="mt-5 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div>{item.preview_url?<Image src={item.preview_url} alt="Fotografia histórica de Volta Redonda em identificação" width={item.preview_width||1200} height={item.preview_height||900} className="h-auto w-full border-2 border-comun-yellow bg-black object-contain"/>:<div className="grid aspect-[4/3] place-items-center border-2 border-comun-yellow p-8 text-center">Esta imagem aguarda restauração técnica.</div>}</div><div><p className="font-black uppercase text-comun-yellow">Memória em identificação</p><h1 className="mt-2 text-3xl font-black uppercase sm:text-4xl">{item.public_title}</h1><p className="mt-5 border-l-4 border-comun-yellow pl-4 text-lg">{item.public_prompt}</p><p className="mt-5 text-sm text-comun-paper/70">O título é uma pista de catalogação, não uma legenda confirmada. Autoria, data, local e pessoas ainda podem estar incompletos.</p><Link href="/comun/acervo/direitos-e-remocao" className="mt-5 inline-flex font-black uppercase text-comun-yellow underline">Crédito, correção ou retirada</Link></div></article>
 {q.envio==='recebido'?<Notice>Contribuição recebida. Ela só aparecerá após revisão humana.</Notice>:null}{q.envio==='limite'?<Notice>Limite temporário atingido. Tente novamente mais tarde.</Notice>:null}{q.denuncia==='recebida'?<Notice>Denúncia recebida para revisão prioritária.</Notice>:null}
 <section className="mt-9 grid gap-5 lg:grid-cols-2"><div className="border-2 border-comun-paper/30 p-5"><h2 className="text-2xl font-black uppercase text-comun-yellow">Síntese editorial</h2>{summary?<div className="mt-4 grid gap-4">{summary.confirmed_text?<Block title="Considerado confirmado" text={summary.confirmed_text}/>:null}{summary.open_questions_text?<Block title="Questões abertas" text={summary.open_questions_text}/>:null}{summary.disagreement_text?<Block title="Divergências" text={summary.disagreement_text}/>:null}</div>:<p className="mt-3 text-comun-paper/70">Ainda não há síntese publicada. Comentários aprovados não alteram automaticamente os dados do acervo.</p>}</div><ContributionForm item={item} slug={slug} logged={Boolean(session?.user)}/></section>
 <section className="mt-10"><h2 className="text-3xl font-black uppercase text-comun-yellow">Contribuições aprovadas</h2>{roots.length?<div className="mt-5 grid gap-4">{roots.map((c:any)=><Comment key={c.id} c={c} replies={replies(c.id)} item={item} slug={slug} logged={Boolean(session?.user)} own={session?.user?.id}/>)}</div>:<p className="mt-4 border-2 border-comun-paper/25 p-5">Nenhuma contribuição pública ainda. Você pode ajudar a começar.</p>}</section></Section></ComunShell>
}
function ContributionForm({item,slug,logged,parentId}:{item:any;slug:string;logged:boolean;parentId?:string}){if(!logged)return <div className="border-2 border-comun-yellow p-5"><h2 className="text-2xl font-black uppercase text-comun-yellow">{parentId?'Responder':'O que você reconhece?'}</h2><p className="mt-3">É preciso entrar para contribuir. A leitura continua pública.</p><Link className="mt-4 inline-flex bg-comun-yellow p-3 font-black uppercase text-comun-black" href={`/comun/entrar?returnTo=${encodeURIComponent(`/comun/acervo/identificar/${slug}`)}`}>Entrar para contribuir</Link></div>;
 return <form action={submitIdentificationComment} className="border-2 border-comun-yellow p-5"><h2 className="text-xl font-black uppercase text-comun-yellow">{parentId?'Responder':'O que você reconhece?'}</h2><input type="hidden" name="item_id" value={item.id}/><input type="hidden" name="slug" value={slug}/>{parentId?<input type="hidden" name="parent_id" value={parentId}/>:null}<label className="mt-4 grid gap-1">Tipo<select name="type" className="bg-white p-3 text-comun-black">{identificationTypes.map(x=><option value={x} key={x}>{identificationTypeLabels[x]}</option>)}</select></label><label className="mt-3 grid gap-1">Contribuição<textarea name="body" required minLength={10} maxLength={3000} className="min-h-32 bg-white p-3 text-comun-black" placeholder="Conte o que sabe e como sabe."/></label><label className="mt-3 grid gap-1">Fonte ou referência opcional<input name="source" maxLength={1000} className="bg-white p-3 text-comun-black"/></label><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" name="public_name" required/> Entendo que o nome do meu perfil será exibido se o texto for aprovado.</label><button className="mt-4 min-h-12 bg-comun-yellow px-4 font-black uppercase text-comun-black">Enviar para moderação</button></form>}
function Comment({c,replies,item,slug,logged}:{c:any;replies:any[];item:any;slug:string;logged:boolean;own?:string}){const withdrawn=c.status==='withdrawn';return <article className="border-2 border-comun-paper/25 p-5"><p className="text-xs font-black uppercase text-comun-yellow">{withdrawn?'Contribuição retirada':`${identificationTypeLabels[c.suggestion_type]||'Contribuição'} · ${c.display_name_snapshot}`}</p><p className="mt-3 whitespace-pre-wrap">{withdrawn?'O conteúdo foi retirado pela pessoa autora.':c.public_text}</p>{!withdrawn?<time className="mt-2 block text-xs text-comun-paper/50">{new Date(c.created_at).toLocaleDateString('pt-BR')}</time>:null}{replies.map(r=><div className="ml-4 mt-4 border-l-4 border-comun-yellow pl-4" key={r.id}><b>{r.display_name_snapshot}</b><p className="mt-1">{r.public_text}</p></div>)}{!withdrawn?<details className="mt-4"><summary className="cursor-pointer font-black uppercase text-comun-yellow">Responder</summary><div className="mt-3"><ContributionForm item={item} slug={slug} logged={logged} parentId={c.id}/></div></details>:null}{logged&&!withdrawn?<details className="mt-3 text-sm"><summary className="cursor-pointer underline">Denunciar contribuição</summary><form action={reportIdentificationComment} className="mt-2 grid gap-2"><input type="hidden" name="slug" value={slug}/><input type="hidden" name="suggestion_id" value={c.id}/><select name="reason" className="bg-white p-2 text-comun-black"><option value="personal_data">Dado pessoal</option><option value="incorrect_authorship">Autoria incorreta</option><option value="abuse">Abuso</option><option value="offensive_content">Conteúdo ofensivo</option><option value="copyright">Direitos autorais</option><option value="other">Outro</option></select><textarea name="details" placeholder="Detalhes opcionais" className="bg-white p-2 text-comun-black"/><button className="justify-self-start border-2 border-comun-yellow p-2 font-black uppercase">Enviar denúncia</button></form></details>:null}</article>}
function Block({title,text}:{title:string;text:string}){return <div><h3 className="font-black uppercase">{title}</h3><p className="mt-1 whitespace-pre-wrap text-sm text-comun-paper/75">{text}</p></div>}
function Notice({children}:{children:React.ReactNode}){return <p role="status" className="mt-6 border-2 border-comun-yellow bg-comun-yellow p-4 font-black text-comun-black">{children}</p>}
