import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin-shell";
import { requireComunAdmin } from "@/lib/admin-auth";
import { resolveOralHistorySuggestionReadiness } from "@/lib/archive/cultural-curation-readiness";
import { materializeOralHistorySuggestionPrivateRoot } from "@/app/comun/admin/acervo/specialized-provenance-actions";
import { createServiceSupabaseClient } from "@/lib/supabase/server";
const labels:Record<string,string>={rights_review_required:"Direitos serão tratados depois da criação do rascunho.",review_only:"A contribuição continua em revisão privada.",asset_not_ready:"Nenhum arquivo público é criado nesta etapa.",oral_history_recording_consent_missing:"Consentimento de gravação ainda não foi registrado.",oral_history_voice_consent_missing:"Consentimento de voz ainda não foi registrado.",oral_history_transcription_consent_missing:"Consentimento de transcrição ainda não foi registrado.",oral_history_publication_consent_missing:"Consentimento de publicação ainda não foi registrado.",private_root_editorial_decision_required:"A decisão editorial explícita é necessária."};
export const dynamic="force-dynamic";
export default async function OralSuggestionDetail({params}:{params:Promise<{id:string}>}){const session=await requireComunAdmin({roles:["admin","editor"]}),{id}=await params,db=createServiceSupabaseClient();if(!db)notFound();const{data:suggestion}=await db.from("comun_archive_oral_history_suggestions").select("id,suggested_person_or_theme,story_summary,city,neighborhood,period_public,relationship_public,status,private_root_archive_item_id").eq("id",id).maybeSingle();if(!suggestion)notFound();const readiness=resolveOralHistorySuggestionReadiness(suggestion,{explicitEditorialDecision:false});return <AdminShell adminEmail={session.admin.email}><Link href="/comun/admin/acervo/historias-orais/sugestoes">← sugestões</Link><h1 className="mt-4 text-3xl font-black uppercase">{suggestion.suggested_person_or_theme}</h1><p>Status: {suggestion.status} · {suggestion.private_root_archive_item_id?"raiz privada já criada":"sem raiz privada"}</p><section className="mt-6 grid gap-3 border-2 bg-white p-5"><h2 className="text-xl font-black uppercase">Contexto e proveniência</h2><p>{suggestion.story_summary}</p><p>{[suggestion.city,suggestion.neighborhood,suggestion.period_public,suggestion.relationship_public].filter(Boolean).join(" · ")||"Origem registrada pela sugestão; detalhes podem ser completados no editor."}</p></section><section className="mt-5 border-2 bg-white p-5"><h2 className="text-xl font-black uppercase">Readiness</h2><p>Raiz privada: {readiness.readyForPrivateRootCreation?"pode ser criada após a decisão editorial":"ainda bloqueada"}.</p><ul className="mt-2 list-disc pl-5">{readiness.blockers.map(blocker=><li key={blocker}>{labels[blocker]||blocker}</li>)}</ul><p className="mt-3 font-bold">Publicação não está autorizada.</p></section>{suggestion.private_root_archive_item_id?<Link className="btn mt-5 inline-block" href={`/comun/admin/acervo/historias-orais/${suggestion.private_root_archive_item_id}`}>Abrir rascunho privado</Link>:<form action={materializeOralHistorySuggestionPrivateRoot} className="mt-5 grid max-w-xl gap-3 border-2 border-comun-black bg-white p-5"><h2 className="text-xl font-black uppercase">Decisão editorial</h2><p>Esta ação cria somente um rascunho privado. Consentimentos, participantes, transcrição e publicação continuam separados.</p><input type="hidden" name="suggestion_id" value={suggestion.id}/><label>Título do rascunho<input required name="title" defaultValue={suggestion.suggested_person_or_theme} className="mt-1 block w-full border-2 p-2"/></label><label>Slug canônico<input required name="slug" placeholder="entrevista-do-bairro" pattern="[a-z0-9]+(-[a-z0-9]+)*" className="mt-1 block w-full border-2 p-2"/></label><button className="btn">Criar rascunho privado</button></form>}</AdminShell>}
