import { notFound } from "next/navigation";
import { ComunShell } from "@/components/comun-shell";
import { isComunObservatoryTerritorialContextEnabled } from "@/lib/comun-observatory-feature";
import { getTerritorialContextPublicDto } from "@/lib/comun-observatory-territorial-context";

export const dynamic = "force-dynamic";
export default function TerritorialSourcesPage() {
  if (!isComunObservatoryTerritorialContextEnabled()) notFound();
  const dto = getTerritorialContextPublicDto();
  return <ComunShell><main className="mx-auto max-w-5xl px-4 py-8 text-comun-black sm:py-12"><p className="text-xs font-black uppercase text-comun-yellow">Observatórios · Território e Serviços Públicos</p><h1 className="mt-2 text-4xl font-black uppercase tracking-[-.04em] sm:text-6xl">Fontes e metodologia</h1><p className="mt-4 max-w-3xl text-lg">A leitura territorial usa somente snapshots ativos de dados oficiais públicos. Cada conjunto preserva data de verificação, fonte e limitações próprias.</p><section className="mt-8 grid gap-4"><Snapshot label="Censo 2022 / IBGE" id={dto.snapshots.territory.id} verifiedAt={dto.snapshots.territory.verifiedAt} /><Snapshot label="Saúde pública / CNES" id={dto.snapshots.health.id} verifiedAt={dto.snapshots.health.verifiedAt} /><Snapshot label="Assistência Social / CadSUAS e fontes municipais" id={dto.snapshots.socialAssistance.id} verifiedAt={dto.snapshots.socialAssistance.verifiedAt} /></section><section className="mt-8 border-t-2 border-comun-black/20 pt-6"><h2 className="text-2xl font-black uppercase">Fontes oficiais</h2><ul className="mt-4 grid gap-3 sm:grid-cols-2">{dto.sources.map((source) => <li key={source.id} className="border-2 border-comun-black/25 bg-comun-paper p-4"><p className="font-black">{source.label}</p><p className="mt-1 text-sm">{source.originalPublisher}</p><p className="mt-1 break-all text-xs">SHA-256: {source.rawSha256}</p><a href={source.officialUrl} target="_blank" rel="noreferrer" className="mt-3 inline-block font-bold underline">Abrir fonte oficial</a></li>)}</ul></section><section className="mt-8 border-l-4 border-comun-yellow pl-4 text-sm"><h2 className="font-black uppercase">Limitações</h2><ul className="mt-2 list-disc space-y-2 pl-5">{dto.limitations.map((limitation) => <li key={limitation}>{limitation}</li>)}</ul></section></main></ComunShell>;
}
function Snapshot({ label, id, verifiedAt }: { label: string; id: string; verifiedAt: string }) { return <article className="border-2 border-comun-black/25 bg-comun-paper p-4"><h2 className="font-black">{label}</h2><p className="mt-1 text-sm">Snapshot: {id}</p><p className="mt-1 text-sm">Verificado em: {new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "long", year: "numeric" }).format(new Date(verifiedAt))}</p></article>; }
