begin;

-- Escola R0. Immutable editorial seed; private progress; all writes through authenticated server boundaries.
create table public.comun_learning_programs (
  id text primary key, title text not null, version integer not null check(version > 0),
  editorial_owner text not null, reviewed_at date not null
);
create table public.comun_learning_units (
  id text primary key, program_id text not null references public.comun_learning_programs(id),
  parent_id text references public.comun_learning_units(id), unit_type text not null check(unit_type in ('track','mission')),
  position integer not null, title text not null, version integer not null check(version > 0), content jsonb not null,
  unique(program_id,id)
);
create table public.comun_learning_resources (
  id text primary key, program_id text not null references public.comun_learning_programs(id),
  title text not null, content jsonb not null
);
create table public.comun_learning_enrollments (
  user_id uuid not null references auth.users(id) on delete restrict,
  program_id text not null references public.comun_learning_programs(id),
  enrolled_at timestamptz not null default now(), primary key(user_id,program_id)
);
create table public.comun_learning_progress (
  user_id uuid not null, program_id text not null, mission_id text not null,
  step integer not null default 0 check(step between 0 and 5), revision integer not null default 0 check(revision >= 0),
  status text not null default 'started' check(status in ('started','practice_pending','completed')),
  updated_at timestamptz not null default now(), primary key(user_id,mission_id),
  foreign key(user_id,program_id) references public.comun_learning_enrollments(user_id,program_id) on delete restrict,
  foreign key(program_id,mission_id) references public.comun_learning_units(program_id,id),
  check((step < 5 and status = 'started') or (step = 5 and status in ('practice_pending','completed')))
);
create table public.comun_learning_practice_links (
  user_id uuid not null, mission_id text not null,
  pauta_id uuid not null references public.comun_pauta_spaces(id) on delete restrict,
  task_id uuid references public.comun_pauta_tasks(id) on delete set null,
  reflection text not null check(char_length(reflection) between 20 and 1200),
  state text not null default 'pending' check(state in ('pending','validated','revision_requested')),
  reviewed_by uuid references auth.users(id) on delete set null, reviewed_at timestamptz,
  review_note text check(char_length(review_note) <= 600), updated_at timestamptz not null default now(),
  primary key(user_id,mission_id),
  foreign key(user_id,mission_id) references public.comun_learning_progress(user_id,mission_id) on delete restrict,
  check(state = 'pending' or reviewed_at is not null)
);
create index comun_learning_practice_review_idx on public.comun_learning_practice_links(state,updated_at);
create index comun_learning_practice_pauta_idx on public.comun_learning_practice_links(pauta_id);
create index comun_learning_practice_task_idx on public.comun_learning_practice_links(task_id);
create index comun_learning_units_parent_idx on public.comun_learning_units(parent_id);

alter table public.comun_learning_programs enable row level security;
alter table public.comun_learning_units enable row level security;
alter table public.comun_learning_resources enable row level security;
alter table public.comun_learning_enrollments enable row level security;
alter table public.comun_learning_progress enable row level security;
alter table public.comun_learning_practice_links enable row level security;
revoke all on table public.comun_learning_programs from public,anon,authenticated;
revoke all on table public.comun_learning_units from public,anon,authenticated;
revoke all on table public.comun_learning_resources from public,anon,authenticated;
revoke all on table public.comun_learning_enrollments from public,anon,authenticated;
revoke all on table public.comun_learning_progress from public,anon,authenticated;
revoke all on table public.comun_learning_practice_links from public,anon,authenticated;
grant select on public.comun_learning_programs, public.comun_learning_units, public.comun_learning_resources to anon,authenticated;
grant select on public.comun_learning_enrollments, public.comun_learning_progress, public.comun_learning_practice_links to authenticated;
grant select,insert,update,delete on public.comun_learning_programs, public.comun_learning_units, public.comun_learning_resources,
 public.comun_learning_enrollments, public.comun_learning_progress, public.comun_learning_practice_links to service_role;
create policy learning_program_read on public.comun_learning_programs for select to anon,authenticated using(true);
create policy learning_unit_read on public.comun_learning_units for select to anon,authenticated using(true);
create policy learning_resource_read on public.comun_learning_resources for select to anon,authenticated using(true);
create policy learning_enrollment_own on public.comun_learning_enrollments for select to authenticated using(user_id=(select auth.uid()));
create policy learning_progress_own on public.comun_learning_progress for select to authenticated using(user_id=(select auth.uid()));
create policy learning_practice_own on public.comun_learning_practice_links for select to authenticated using(user_id=(select auth.uid()));

-- Service-role only, SECURITY INVOKER: transaction and optimistic revision prevent stale tabs from overwriting progress.
create function public.comun_learning_event(p_user_id uuid,p_mission_id text,p_revision integer,p_event text,p_answer integer default null)
returns jsonb language plpgsql security invoker set search_path = public,pg_temp as $$
declare m public.comun_learning_units; p public.comun_learning_progress; c jsonb; correct boolean; next_step integer;
begin
 select * into m from public.comun_learning_units where id=p_mission_id and unit_type='mission';
 if m.id is null then raise exception 'learning_invalid_mission'; end if;
 insert into public.comun_learning_enrollments(user_id,program_id) values(p_user_id,m.program_id) on conflict do nothing;
 insert into public.comun_learning_progress(user_id,program_id,mission_id) values(p_user_id,m.program_id,m.id) on conflict do nothing;
 select * into p from public.comun_learning_progress where user_id=p_user_id and mission_id=m.id for update;
 if p.revision <> p_revision then raise exception 'learning_stale_revision'; end if;
 next_step:=p.step;
 if p_event='answer' and p.step in (1,3) then
   c:=m.content->'challenges'->(case when p.step=1 then 0 else 1 end);
   if p_answer is null or p_answer < 0 or p_answer >= jsonb_array_length(c->'options') then raise exception 'learning_invalid_answer'; end if;
   correct:=p_answer=(c->>'answer')::integer;
   if correct then next_step:=p.step+1; end if;
 elsif p_event='continue' and p.step in (0,2,4) then next_step:=p.step+1;
 else raise exception 'learning_invalid_transition'; end if;
 update public.comun_learning_progress set step=next_step,revision=revision+1,updated_at=now(),
   status=case when next_step<5 then 'started' when (m.content->>'requiresPractice')::boolean then 'practice_pending' else 'completed' end
 where user_id=p_user_id and mission_id=m.id returning * into p;
 return jsonb_build_object('progress',to_jsonb(p)-'user_id'-'program_id','correct',correct,'feedback',c->>'feedback');
end; $$;
revoke all on function public.comun_learning_event(uuid,text,integer,text,integer) from public,anon,authenticated;
grant execute on function public.comun_learning_event(uuid,text,integer,text,integer) to service_role;

create function public.comun_learning_submit_practice(p_user_id uuid,p_mission_id text,p_pauta_id uuid,p_task_id uuid,p_reflection text)
returns void language plpgsql security invoker set search_path = public,pg_temp as $$
begin
 perform 1 from public.comun_learning_progress where user_id=p_user_id and mission_id=p_mission_id and step=5 and status='practice_pending' for update;
 if not found then raise exception 'learning_practice_not_available'; end if;
 if not exists(select 1 from public.comun_pauta_memberships pm join public.comun_pauta_spaces ps on ps.id=pm.pauta_id
   where pm.member_user_id=p_user_id and pm.pauta_id=p_pauta_id and pm.status='active' and ps.status <> 'archived') then
   raise exception 'learning_pauta_access'; end if;
 if p_task_id is not null and not exists(select 1 from public.comun_pauta_tasks where id=p_task_id and pauta_id=p_pauta_id and status <> 'archived') then raise exception 'learning_task_access'; end if;
 insert into public.comun_learning_practice_links(user_id,mission_id,pauta_id,task_id,reflection)
 values(p_user_id,p_mission_id,p_pauta_id,p_task_id,btrim(p_reflection))
 on conflict(user_id,mission_id) do update set pauta_id=excluded.pauta_id,task_id=excluded.task_id,reflection=excluded.reflection,
 state='pending',reviewed_by=null,reviewed_at=null,review_note=null,updated_at=now();
end; $$;
revoke all on function public.comun_learning_submit_practice(uuid,text,uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.comun_learning_submit_practice(uuid,text,uuid,uuid,text) to service_role;

create function public.comun_learning_review_practice(p_reviewer uuid,p_user_id uuid,p_mission_id text,p_decision text,p_note text)
returns void language plpgsql security invoker set search_path = public,pg_temp as $$
begin
 if p_reviewer=p_user_id or not exists(select 1 from public.comun_admin_users where user_id=p_reviewer and is_active and role in ('admin','editor')) then raise exception 'learning_review_access'; end if;
 if p_decision not in ('validated','revision_requested') then raise exception 'learning_invalid_review'; end if;
 -- Same lock order as submission: progress first, then practice.
 perform 1 from public.comun_learning_progress where user_id=p_user_id and mission_id=p_mission_id for update;
 update public.comun_learning_practice_links set state=p_decision,reviewed_by=p_reviewer,reviewed_at=now(),review_note=nullif(btrim(p_note),''),updated_at=now()
 where user_id=p_user_id and mission_id=p_mission_id and state='pending';
 if not found then raise exception 'learning_review_not_pending'; end if;
 update public.comun_learning_progress set status=case when p_decision='validated' then 'completed' else 'practice_pending' end,revision=revision+1,updated_at=now()
 where user_id=p_user_id and mission_id=p_mission_id and step=5;
end; $$;
revoke all on function public.comun_learning_review_practice(uuid,uuid,text,text,text) from public,anon,authenticated;
grant execute on function public.comun_learning_review_practice(uuid,uuid,text,text,text) to service_role;

-- Version 1 editorial catalogue. Future versions must preserve completed content versions.
insert into public.comun_learning_programs values('organizadores-r0','Formação de Organizadores',1,'Equipe Escola COMUN','2026-10-06');
insert into public.comun_learning_units values('fundamentos','organizadores-r0',null,'track',1,'Fundamentos',1,'{"id": "fundamentos", "title": "Fundamentos", "description": "Do problema observável à primeira pauta."}'::jsonb);
insert into public.comun_learning_units values('investigacao','organizadores-r0',null,'track',2,'Investigação Popular',1,'{"id": "investigacao", "title": "Investigação Popular", "description": "Perguntas, fontes e limites da evidência."}'::jsonb);
insert into public.comun_learning_units values('organizacao','organizadores-r0',null,'track',3,'Organização',1,'{"id": "organizacao", "title": "Organização", "description": "Escuta, convites e responsabilidade compartilhada."}'::jsonb);
insert into public.comun_learning_units values('estrategia','organizadores-r0',null,'track',4,'Estratégia',1,'{"id": "estrategia", "title": "Estratégia", "description": "Objetivos, atores e hipóteses de mudança."}'::jsonb);
insert into public.comun_learning_units values('o-que-e-um-problema','organizadores-r0','fundamentos','mission',1,'O que é um problema?',1,'{"id": "o-que-e-um-problema", "number": "1.1", "title": "O que é um problema?", "track": "fundamentos", "minutes": 4, "version": 1, "concept": "Descreva um fato que possa ser observado. Intenções atribuídas a alguém são hipóteses: precisam de evidência. Separar as duas coisas ajuda a investigar sem começar pela conclusão.", "help": "No primeiro caso: O relato descreve uma condição percebida. Ainda precisamos medir, registrar horários e verificar sua extensão. No segundo exemplo: Uma medição contextualizada pode ser conferida e comparada.", "challenges": [{"prompt": "Uma escola tem salas muito quentes. Qual frase descreve um problema observável?", "options": ["A Prefeitura não se importa.", "Alunos relatam calor nas salas durante as aulas.", "Todos os gestores são incompetentes."], "answer": 1, "feedback": "O relato descreve uma condição percebida. Ainda precisamos medir, registrar horários e verificar sua extensão."}, {"prompt": "Qual registro ajuda a verificar esse problema?", "options": ["Uma medição com data, horário e local.", "Uma opinião sobre o prefeito.", "Uma manchete sem fonte."], "answer": 0, "feedback": "Uma medição contextualizada pode ser conferida e comparada."}], "application": "Descreva o problema na síntese de uma pauta, indicando o que já foi observado e o que falta verificar.", "requiresPractice": true, "resourceId": "fundamentos"}'::jsonb);
insert into public.comun_learning_units values('causa-ou-consequencia','organizadores-r0','fundamentos','mission',2,'Causa ou consequência?',1,'{"id": "causa-ou-consequencia", "number": "1.2", "title": "Causa ou consequência?", "track": "fundamentos", "minutes": 5, "version": 1, "concept": "Problema é a condição que queremos mudar. Causa é uma explicação para sua ocorrência. Consequência é um efeito. Uma relação causal plausível ainda precisa ser investigada.", "help": "No primeiro caso: O atraso é um possível efeito da falta do ônibus. No segundo exemplo: A falha mecânica é uma explicação possível, ainda sem confirmação.", "challenges": [{"prompt": "O ônibus não passou e uma pessoa chegou atrasada ao trabalho. O atraso é:", "options": ["Consequência.", "Causa demonstrada.", "Estratégia."], "answer": 0, "feedback": "O atraso é um possível efeito da falta do ônibus."}, {"prompt": "Atribuir a falta do ônibus a uma falha mecânica, sem documento, é:", "options": ["Uma causa confirmada.", "Uma hipótese de causa.", "Um objetivo."], "answer": 1, "feedback": "A falha mecânica é uma explicação possível, ainda sem confirmação."}], "application": "Separe problema, possíveis causas e efeitos na sua pauta.", "requiresPractice": false, "resourceId": "fundamentos"}'::jsonb);
insert into public.comun_learning_units values('evidencia-ou-suposicao','organizadores-r0','fundamentos','mission',3,'Evidência ou suposição?',1,'{"id": "evidencia-ou-suposicao", "number": "1.3", "title": "Evidência ou suposição?", "track": "fundamentos", "minutes": 6, "version": 1, "concept": "Evidência é um registro que sustenta uma afirmação específica. Indício orienta uma investigação. Hipótese propõe uma explicação. Nenhum deles autoriza afirmar mais do que o registro permite.", "help": "No primeiro caso: A foto sustenta uma afirmação localizada, não a frequência nem a causa. No segundo exemplo: Explicitar a incerteza permite avançar sem transformar suspeita em fato.", "challenges": [{"prompt": "Uma foto mostra lixo em uma rua em determinada data. Ela prova:", "options": ["Que nunca há coleta no bairro.", "Que havia lixo naquele lugar e momento.", "Que a empresa desviou dinheiro."], "answer": 1, "feedback": "A foto sustenta uma afirmação localizada, não a frequência nem a causa."}, {"prompt": "Como registrar uma explicação ainda não confirmada?", "options": ["Como fato.", "Como hipótese, com a pergunta a investigar.", "Como conclusão definitiva."], "answer": 1, "feedback": "Explicitar a incerteza permite avançar sem transformar suspeita em fato."}], "application": "Marque uma afirmação da pauta como documentada e outra como hipótese.", "requiresPractice": false, "resourceId": "fundamentos"}'::jsonb);
insert into public.comun_learning_units values('objetivo-observavel','organizadores-r0','fundamentos','mission',4,'O que queremos mudar?',1,'{"id": "objetivo-observavel", "number": "1.4", "title": "O que queremos mudar?", "track": "fundamentos", "minutes": 5, "version": 1, "concept": "Um objetivo descreve uma mudança verificável. Inclua a condição desejada e um marco de avaliação. A atividade que faremos é um meio, não o resultado final.", "help": "No primeiro caso: Há uma condição concreta que pode ser conferida. No segundo exemplo: A reunião pode apoiar um objetivo, mas não demonstra por si só que o problema mudou.", "challenges": [{"prompt": "Qual objetivo permite verificar avanço?", "options": ["Melhorar tudo.", "Fazer dez posts.", "Restabelecer a iluminação dos pontos identificados e verificar seu funcionamento."], "answer": 2, "feedback": "Há uma condição concreta que pode ser conferida."}, {"prompt": "“Realizar uma reunião” descreve:", "options": ["Uma atividade.", "Um resultado social garantido.", "Uma evidência de solução."], "answer": 0, "feedback": "A reunião pode apoiar um objetivo, mas não demonstra por si só que o problema mudou."}], "application": "Registre um objetivo observável e a forma de verificá-lo na pauta.", "requiresPractice": true, "resourceId": "fundamentos"}'::jsonb);
insert into public.comun_learning_units values('estrategia-tatica-tarefa','organizadores-r0','fundamentos','mission',5,'Estratégia não é atividade',1,'{"id": "estrategia-tatica-tarefa", "number": "1.5", "title": "Estratégia não é atividade", "track": "fundamentos", "minutes": 6, "version": 1, "concept": "Objetivo é a mudança desejada. Estratégia é a hipótese sobre como chegar a ela. Tática é uma ação escolhida. Tarefa é uma responsabilidade concreta, com pessoa e prazo.", "help": "No primeiro caso: Há uma entrega concreta, uma responsável e um prazo. No segundo exemplo: A frase propõe um caminho. Ainda precisamos detalhar ações, responsáveis e critérios de revisão.", "challenges": [{"prompt": "“Maria verifica o documento até sexta” é:", "options": ["Estratégia.", "Tarefa.", "Objetivo."], "answer": 1, "feedback": "Há uma entrega concreta, uma responsável e um prazo."}, {"prompt": "“Articular moradores para obter uma resposta formal” é principalmente:", "options": ["Uma hipótese estratégica.", "Uma medição.", "Uma tarefa individual completa."], "answer": 0, "feedback": "A frase propõe um caminho. Ainda precisamos detalhar ações, responsáveis e critérios de revisão."}], "application": "Classifique uma iniciativa existente como objetivo, estratégia, tática ou tarefa.", "requiresPractice": false, "resourceId": "fundamentos"}'::jsonb);
insert into public.comun_learning_units values('minha-primeira-pauta','organizadores-r0','fundamentos','mission',6,'Minha primeira pauta',1,'{"id": "minha-primeira-pauta", "number": "1.6", "title": "Minha primeira pauta", "track": "fundamentos", "minutes": 7, "version": 1, "concept": "Uma pauta reúne problema, evidências, lacunas e objetivo. Comece pelo que sabemos e pela próxima pergunta. Não é preciso ter todas as respostas para organizar a investigação.", "help": "No primeiro caso: A síntese orienta trabalho verificável e distribui perguntas. No segundo exemplo: Uma lacuna explícita pode virar trabalho concreto.", "challenges": [{"prompt": "O que deve aparecer numa primeira síntese?", "options": ["Só indignação.", "Problema, registro disponível, lacuna e objetivo.", "Uma lista de culpados sem fonte."], "answer": 1, "feedback": "A síntese orienta trabalho verificável e distribui perguntas."}, {"prompt": "Falta uma informação essencial. O próximo passo é:", "options": ["Esconder a lacuna.", "Concluir mesmo assim.", "Registrar a dúvida e atribuir uma tarefa de verificação."], "answer": 2, "feedback": "Uma lacuna explícita pode virar trabalho concreto."}], "application": "Revise a síntese de uma pauta: problema, evidência, lacuna, objetivo e próxima pergunta.", "requiresPractice": true, "resourceId": "fundamentos"}'::jsonb);
insert into public.comun_learning_units values('pergunta-verificavel','organizadores-r0','investigacao','mission',7,'Transforme dúvida em pergunta',1,'{"id": "pergunta-verificavel", "number": "2.1", "title": "Transforme dúvida em pergunta", "track": "investigacao", "minutes": 4, "version": 1, "concept": "Uma boa pergunta delimita assunto, período e informação necessária. Quanto mais precisa, mais fácil escolher a fonte e reconhecer uma resposta suficiente.", "help": "No primeiro caso: A pergunta delimita evento, linha e período. No segundo exemplo: O recorte transforma inquietação em investigação.", "challenges": [{"prompt": "Qual pergunta é verificável?", "options": ["Por que tudo é ruim?", "Quantas viagens deixaram de ocorrer na linha X em setembro?", "Quem odeia o bairro?"], "answer": 1, "feedback": "A pergunta delimita evento, linha e período."}, {"prompt": "Uma pergunta ficou ampla demais. Como melhorar?", "options": ["Delimitar local, período e dado esperado.", "Adicionar mais acusações.", "Tirar o período."], "answer": 0, "feedback": "O recorte transforma inquietação em investigação."}], "application": "Escreva uma pergunta que possa ser respondida com documento ou dado.", "requiresPractice": false, "resourceId": "investigacao"}'::jsonb);
insert into public.comun_learning_units values('hierarquia-de-fontes','organizadores-r0','investigacao','mission',8,'Nem toda fonte vale igual',1,'{"id": "hierarquia-de-fontes", "number": "2.2", "title": "Nem toda fonte vale igual", "track": "investigacao", "minutes": 5, "version": 1, "concept": "Escolha fontes adequadas à afirmação. Para verificar o texto de um contrato, consulte o contrato. Para compreender experiências, escute as pessoas. Uma fonte primária também pode conter erros e precisa de contexto.", "help": "No primeiro caso: O documento original permite conferir o que foi formalizado. No segundo exemplo: A experiência tem valor, respeitando o alcance da fonte.", "challenges": [{"prompt": "Para saber o valor registrado num contrato, comece por:", "options": ["Um comentário anônimo.", "O instrumento contratual e seus aditivos.", "Um vídeo que não cita documentos."], "answer": 1, "feedback": "O documento original permite conferir o que foi formalizado."}, {"prompt": "Um relato de morador é adequado para registrar:", "options": ["Sua experiência, sem generalizar para toda a cidade.", "A execução completa de um orçamento.", "A intenção de todos os gestores."], "answer": 0, "feedback": "A experiência tem valor, respeitando o alcance da fonte."}], "application": "Classifique as fontes da pauta conforme a pergunta que cada uma responde.", "requiresPractice": false, "resourceId": "investigacao"}'::jsonb);
insert into public.comun_learning_units values('fonte-primaria','organizadores-r0','investigacao','mission',9,'Fonte primária',1,'{"id": "fonte-primaria", "number": "2.3", "title": "Fonte primária", "track": "investigacao", "minutes": 5, "version": 1, "concept": "Fonte primária é um registro original relevante para a pergunta: ato oficial, dado produzido, documento ou depoimento direto. Guarde autoria, data, origem e trecho utilizado.", "help": "No primeiro caso: O relatório permite verificar metodologia, período e limites. No segundo exemplo: Sem contexto, não sabemos o que o número representa.", "challenges": [{"prompt": "Uma notícia cita um relatório. Qual é a fonte primária do número citado?", "options": ["O relatório original.", "O compartilhamento da notícia.", "A legenda de um post."], "answer": 0, "feedback": "O relatório permite verificar metodologia, período e limites."}, {"prompt": "Encontrou uma planilha sem origem. O que falta?", "options": ["Uma frase mais forte.", "Autoria, período e método de produção.", "Só um novo título."], "answer": 1, "feedback": "Sem contexto, não sabemos o que o número representa."}], "application": "Localize uma fonte original e registre sua origem e seu limite na pauta.", "requiresPractice": true, "resourceId": "investigacao"}'::jsonb);
insert into public.comun_learning_units values('ler-documento-publico','organizadores-r0','investigacao','mission',10,'Documento público',1,'{"id": "ler-documento-publico", "number": "2.4", "title": "Documento público", "track": "investigacao", "minutes": 6, "version": 1, "concept": "Ao ler um documento, registre identificação, órgão, data, trecho e página. Diferencie o que foi solicitado, respondido e efetivamente demonstrado. Documento oficial não significa execução comprovada.", "help": "No primeiro caso: A promessa registrada ainda precisa de acompanhamento. No segundo exemplo: A referência permite retornar ao contexto original.", "challenges": [{"prompt": "Um ofício promete reparar uma rua. Isso comprova:", "options": ["Que a obra terminou.", "Que houve uma manifestação formal sobre o reparo.", "Que toda a cidade foi atendida."], "answer": 1, "feedback": "A promessa registrada ainda precisa de acompanhamento."}, {"prompt": "Como permitir que outra pessoa confira um trecho?", "options": ["Indicar documento, data e página.", "Enviar só uma frase recortada.", "Trocar a data pela data do post."], "answer": 0, "feedback": "A referência permite retornar ao contexto original."}], "application": "Leia um documento e registre trecho, página, data e dúvida restante.", "requiresPractice": false, "resourceId": "investigacao"}'::jsonb);
insert into public.comun_learning_units values('transparencia-e-lai','organizadores-r0','investigacao','mission',11,'Transparência e LAI',1,'{"id": "transparencia-e-lai", "number": "2.5", "title": "Transparência e LAI", "track": "investigacao", "minutes": 7, "version": 1, "concept": "Comece procurando informação já publicada. Se faltar um registro, identifique o órgão que o mantém e peça documentos ou dados delimitados. Evite misturar um pedido de informação com uma reclamação. Confira as regras do canal oficial antes de protocolar.", "help": "No primeiro caso: O pedido especifica registro, assunto e período. No segundo exemplo: A busca inicial evita duplicação e orienta o destinatário.", "challenges": [{"prompt": "Qual pedido é mais preciso?", "options": ["Expliquem por que vocês não trabalham.", "Enviem a relação de viagens realizadas na linha X entre as datas A e B.", "Resolva todos os problemas."], "answer": 1, "feedback": "O pedido especifica registro, assunto e período."}, {"prompt": "Antes de solicitar um documento, convém:", "options": ["Verificar se já está publicado e qual órgão o mantém.", "Inventar um prazo de resposta.", "Enviar a qualquer órgão sem conferir."], "answer": 0, "feedback": "A busca inicial evita duplicação e orienta o destinatário."}], "application": "Prepare um pedido delimitado e registre a tarefa de protocolar no canal oficial.", "requiresPractice": true, "resourceId": "investigacao"}'::jsonb);
insert into public.comun_learning_units values('limites-da-evidencia','organizadores-r0','investigacao','mission',12,'O que a evidência não prova?',1,'{"id": "limites-da-evidencia", "number": "2.6", "title": "O que a evidência não prova?", "track": "investigacao", "minutes": 6, "version": 1, "concept": "Uma conclusão deve caber na evidência. Associação não prova causalidade. Ausência de resposta não demonstra automaticamente fraude. Escreva também o que seu material ainda não permite concluir.", "help": "No primeiro caso: O registro não informa sozinho a extensão nem a causa. No segundo exemplo: A coexistência dos fatos não demonstra o mecanismo nem uma irregularidade específica.", "challenges": [{"prompt": "Três moradores relatam falta de água. Podemos afirmar:", "options": ["Toda a cidade ficou sem água.", "Há três relatos que precisam de localização e verificação.", "Houve sabotagem comprovada."], "answer": 1, "feedback": "O registro não informa sozinho a extensão nem a causa."}, {"prompt": "Uma empresa recebeu dinheiro e houve atraso. Isso prova desvio?", "options": ["Sim, sempre.", "Não; precisamos verificar obrigações, execução e documentos.", "Prova também a intenção de cada gestor."], "answer": 1, "feedback": "A coexistência dos fatos não demonstra o mecanismo nem uma irregularidade específica."}], "application": "Revise uma afirmação e escreva seu limite de evidência.", "requiresPractice": false, "resourceId": "investigacao"}'::jsonb);
insert into public.comun_learning_units values('adicionar-evidencia','organizadores-r0','investigacao','mission',13,'Adicione uma evidência',1,'{"id": "adicionar-evidencia", "number": "2.7", "title": "Adicione uma evidência", "track": "investigacao", "minutes": 7, "version": 1, "concept": "Uma evidência útil liga fonte, afirmação e limite. Registre no espaço canônico da pauta, respeitando sua visibilidade. Não publique dados pessoais de terceiros para demonstrar um problema coletivo.", "help": "No primeiro caso: A ficha permite revisão por outra pessoa. No segundo exemplo: A relevância do documento não torna todo seu conteúdo necessário à publicação.", "challenges": [{"prompt": "Qual ficha pode ser conferida?", "options": ["Título forte sem referência.", "Afirmação, fonte, data, trecho e limite.", "Uma imagem sem contexto."], "answer": 1, "feedback": "A ficha permite revisão por outra pessoa."}, {"prompt": "Um documento contém contato privado. Como compartilhar?", "options": ["Publicar inteiro.", "Usar o fluxo de revisão e proteger o dado pessoal.", "Copiar o contato para a manchete."], "answer": 1, "feedback": "A relevância do documento não torna todo seu conteúdo necessário à publicação."}], "application": "Adicione uma evidência ou contribuição na pauta e indique o registro para revisão.", "requiresPractice": true, "resourceId": "investigacao"}'::jsonb);
insert into public.comun_learning_units values('organizar-e-divulgar','organizadores-r0','organizacao','mission',14,'Organizar não é divulgar',1,'{"id": "organizar-e-divulgar", "number": "3.1", "title": "Organizar não é divulgar", "track": "organizacao", "minutes": 4, "version": 1, "concept": "Divulgação amplia alcance. Organização cria vínculos, compromissos e capacidade de agir junto. As duas podem se apoiar, mas número de visualizações não demonstra distribuição de responsabilidade.", "help": "No primeiro caso: Há compromisso e acompanhamento além da audiência. No segundo exemplo: O vínculo se constrói com convite, escuta e responsabilidade.", "challenges": [{"prompt": "Qual sinal mostra organização?", "options": ["Muitas curtidas.", "Pessoas assumem tarefas e combinam como acompanhar.", "Um vídeo viral sem retorno."], "answer": 1, "feedback": "Há compromisso e acompanhamento além da audiência."}, {"prompt": "Após uma divulgação, o próximo passo organizativo pode ser:", "options": ["Convidar interessados para uma conversa com propósito e retorno.", "Medir apenas curtidas.", "Declarar que todos já participam."], "answer": 0, "feedback": "O vínculo se constrói com convite, escuta e responsabilidade."}], "application": "Avalie se uma ação criou audiência, vínculos ou compromissos.", "requiresPractice": false, "resourceId": "organizacao"}'::jsonb);
insert into public.comun_learning_units values('escute-primeiro','organizadores-r0','organizacao','mission',15,'Escute primeiro',1,'{"id": "escute-primeiro", "number": "3.2", "title": "Escute primeiro", "track": "organizacao", "minutes": 5, "version": 1, "concept": "Perguntas abertas ajudam a compreender experiência, impacto e desejo de mudança. Evite conduzir a pessoa à sua resposta preferida. Confirme o que entendeu e respeite a decisão de não participar.", "help": "No primeiro caso: A pessoa pode explicar a própria experiência. No segundo exemplo: A confirmação reduz interpretações equivocadas e respeita a pessoa.", "challenges": [{"prompt": "Qual pergunta abre uma escuta?", "options": ["Você concorda que minha solução é a melhor?", "Como esse problema afeta sua rotina?", "Você está errado, não está?"], "answer": 1, "feedback": "A pessoa pode explicar a própria experiência."}, {"prompt": "Depois de ouvir, uma boa atitude é:", "options": ["Confirmar o entendimento e perguntar o que ela gostaria de mudar.", "Prometer resolver tudo.", "Divulgar seu contato sem perguntar."], "answer": 0, "feedback": "A confirmação reduz interpretações equivocadas e respeita a pessoa."}], "application": "Prepare três perguntas abertas para uma conversa.", "requiresPractice": false, "resourceId": "organizacao"}'::jsonb);
insert into public.comun_learning_units values('conversa-individual','organizadores-r0','organizacao','mission',16,'Conversa individual',1,'{"id": "conversa-individual", "number": "3.3", "title": "Conversa individual", "track": "organizacao", "minutes": 6, "version": 1, "concept": "Uma conversa pode ter abertura, escuta, problema compartilhado, convite e próximo contato. Seja claro sobre o propósito e combine qualquer registro. Participação é voluntária.", "help": "No primeiro caso: O convite é concreto e deixa a decisão com a pessoa. No segundo exemplo: Organização exige consentimento e respeito, não pressão individual.", "challenges": [{"prompt": "Qual encerramento constrói continuidade?", "options": ["Te adiciono a qualquer grupo sem avisar.", "Quer participar desta atividade? Podemos combinar um retorno?", "Você deve aceitar."], "answer": 1, "feedback": "O convite é concreto e deixa a decisão com a pessoa."}, {"prompt": "A pessoa não quer participar agora. Você:", "options": ["Respeita e pergunta se deseja algum retorno.", "Insiste até aceitar.", "Anuncia publicamente sua recusa."], "answer": 0, "feedback": "Organização exige consentimento e respeito, não pressão individual."}], "application": "Realize uma conversa e registre apenas aprendizados necessários, sem dados privados de terceiros.", "requiresPractice": true, "resourceId": "organizacao"}'::jsonb);
insert into public.comun_learning_units values('problema-ao-convite','organizadores-r0','organizacao','mission',17,'Do problema ao convite',1,'{"id": "problema-ao-convite", "number": "3.4", "title": "Do problema ao convite", "track": "organizacao", "minutes": 5, "version": 1, "concept": "Um convite explica o que faremos, por que, quando e qual ajuda é possível. Ofereça uma tarefa compatível com tempo e interesse. Evite promessas que o grupo não pode cumprir.", "help": "No primeiro caso: O convite descreve atividade, tempo e contribuição possível. No segundo exemplo: Responsabilidades podem ser proporcionais à disponibilidade.", "challenges": [{"prompt": "Qual convite é mais concreto?", "options": ["Venha mudar tudo.", "Podemos conferir os horários da linha juntos sábado, por 30 minutos?", "Faça qualquer coisa."], "answer": 1, "feedback": "O convite descreve atividade, tempo e contribuição possível."}, {"prompt": "A pessoa só tem 15 minutos. Como adaptar?", "options": ["Oferecer uma contribuição pequena e combinada.", "Exigir presença integral.", "Excluir da participação."], "answer": 0, "feedback": "Responsabilidades podem ser proporcionais à disponibilidade."}], "application": "Escreva um convite com propósito, duração e contribuição possível.", "requiresPractice": false, "resourceId": "organizacao"}'::jsonb);
insert into public.comun_learning_units values('reuniao-termina-em-acao','organizadores-r0','organizacao','mission',18,'Reunião que termina em ação',1,'{"id": "reuniao-termina-em-acao", "number": "3.5", "title": "Reunião que termina em ação", "track": "organizacao", "minutes": 6, "version": 1, "concept": "Defina um resultado esperado, uma pauta curta e o tempo. Ao final, registre decisão, responsável, prazo e retorno. Divergência pode exigir uma nova pergunta, em vez de uma decisão forçada.", "help": "No primeiro caso: Sem responsabilidade e entrega, a decisão não orienta ação. No segundo exemplo: O acompanhamento permite verificar se o combinado aconteceu.", "challenges": [{"prompt": "O que falta em “precisamos pesquisar mais”?", "options": ["Uma pessoa responsável, entrega e prazo.", "Um slogan.", "Mais uma reunião sem pauta."], "answer": 0, "feedback": "Sem responsabilidade e entrega, a decisão não orienta ação."}, {"prompt": "Antes de encerrar uma reunião, confira:", "options": ["Só o número de presentes.", "Decisões, tarefas e como serão acompanhadas.", "Quem falou mais alto."], "answer": 1, "feedback": "O acompanhamento permite verificar se o combinado aconteceu."}], "application": "Prepare uma pauta com tempo e resultado esperado.", "requiresPractice": false, "resourceId": "organizacao"}'::jsonb);
insert into public.comun_learning_units values('facilite-de-verdade','organizadores-r0','organizacao','mission',19,'Facilite de verdade',1,'{"id": "facilite-de-verdade", "number": "3.6", "title": "Facilite de verdade", "track": "organizacao", "minutes": 7, "version": 1, "concept": "Facilitar é cuidar do processo: abertura, participação, tempo, síntese e encaminhamento. Faça espaço para quem falou pouco. A síntese precisa ser confirmada pelo grupo.", "help": "No primeiro caso: O combinado oferece uma referência comum para redistribuir a palavra. No segundo exemplo: A síntese deve refletir o que foi acordado.", "challenges": [{"prompt": "Uma pessoa monopoliza a conversa. Você pode:", "options": ["Humilhar a pessoa.", "Lembrar o combinado de tempo e abrir espaço para outras falas.", "Encerrar sem avisar."], "answer": 1, "feedback": "O combinado oferece uma referência comum para redistribuir a palavra."}, {"prompt": "Ao sintetizar uma decisão, faça:", "options": ["Confirmação com o grupo e registro de responsáveis.", "Uma versão que ninguém viu.", "Um ranking das pessoas."], "answer": 0, "feedback": "A síntese deve refletir o que foi acordado."}], "application": "Conduza 15 minutos de uma reunião e registre decisão, responsável e retorno na pauta.", "requiresPractice": true, "resourceId": "organizacao"}'::jsonb);
insert into public.comun_learning_units values('quem-pode-mudar','organizadores-r0','estrategia','mission',20,'Quem realmente pode mudar isso?',1,'{"id": "quem-pode-mudar", "number": "4.1", "title": "Quem realmente pode mudar isso?", "track": "estrategia", "minutes": 5, "version": 1, "concept": "Separe quem decide, executa, influencia e vive o impacto. Confirme competências institucionais em documentos, sem deduzir autoridade apenas da visibilidade de uma pessoa.", "help": "No primeiro caso: Competência precisa ser conferida conforme a demanda. No segundo exemplo: Influência e autoridade formal são relações diferentes.", "challenges": [{"prompt": "Para definir o destinatário de uma demanda, comece por:", "options": ["Quem aparece mais na televisão.", "O órgão com competência sobre o assunto.", "Qualquer perfil popular."], "answer": 1, "feedback": "Competência precisa ser conferida conforme a demanda."}, {"prompt": "Uma pessoa pode influenciar uma decisão sem:", "options": ["Ter a competência formal para assiná-la.", "Conversar com ninguém.", "Existir uma decisão."], "answer": 0, "feedback": "Influência e autoridade formal são relações diferentes."}], "application": "Identifique quem decide e quem executa na sua pauta.", "requiresPractice": false, "resourceId": "estrategia"}'::jsonb);
insert into public.comun_learning_units values('atores-institucionais','organizadores-r0','estrategia','mission',21,'Atores institucionais',1,'{"id": "atores-institucionais", "number": "4.2", "title": "Atores institucionais", "track": "estrategia", "minutes": 5, "version": 1, "concept": "Um mapa de atores relaciona papéis à decisão concreta. Não é uma lista fixa de aliados e inimigos. Atualize o mapa com evidência de competência, interesse e capacidade de influência.", "help": "No primeiro caso: A atuação deve ser descrita conforme sua competência. No segundo exemplo: O mapa é uma hipótese de trabalho revisável.", "challenges": [{"prompt": "Um órgão fiscaliza, mas não executa a obra. Seu papel principal é:", "options": ["Execução.", "Fiscalização e possível influência.", "Morador atingido."], "answer": 1, "feedback": "A atuação deve ser descrita conforme sua competência."}, {"prompt": "Uma posição de um ator mudou. O mapa deve:", "options": ["Permanecer igual para sempre.", "Ser atualizado com o registro que sustenta a mudança.", "Ser substituído por insultos."], "answer": 1, "feedback": "O mapa é uma hipótese de trabalho revisável."}], "application": "Monte um mapa de decisão, execução, influência e impacto.", "requiresPractice": false, "resourceId": "estrategia"}'::jsonb);
insert into public.comun_learning_units values('recursos-obstaculos','organizadores-r0','estrategia','mission',22,'Recursos e obstáculos',1,'{"id": "recursos-obstaculos", "number": "4.3", "title": "Recursos e obstáculos", "track": "estrategia", "minutes": 5, "version": 1, "concept": "Recursos incluem tempo, conhecimento, vínculos, ferramentas e legitimidade. Obstáculos incluem restrições materiais e institucionais. Um plano precisa caber na capacidade real do grupo.", "help": "No primeiro caso: Capacidade depende também de tempo e saberes. No segundo exemplo: A restrição precisa alterar o plano para que ele seja executável.", "challenges": [{"prompt": "Qual recurso deve entrar no plano?", "options": ["Só dinheiro.", "Tempo disponível e habilidades das pessoas.", "Uma equipe imaginária."], "answer": 1, "feedback": "Capacidade depende também de tempo e saberes."}, {"prompt": "Uma tarefa exige mais tempo do que a equipe possui. Faça:", "options": ["Ignore a restrição.", "Reduza escopo ou distribua responsabilidades com acordo.", "Prometa entrega imediata."], "answer": 1, "feedback": "A restrição precisa alterar o plano para que ele seja executável."}], "application": "Registre recursos disponíveis e um obstáculo que exige adaptar o plano.", "requiresPractice": false, "resourceId": "estrategia"}'::jsonb);
insert into public.comun_learning_units values('hipotese-de-mudanca','organizadores-r0','estrategia','mission',23,'Hipótese de mudança',1,'{"id": "hipotese-de-mudanca", "number": "4.4", "title": "Hipótese de mudança", "track": "estrategia", "minutes": 7, "version": 1, "concept": "Use: se fizermos X, esperamos Y, porque Z. Escreva a relação esperada e um sinal que a contradiga. Estratégia melhora quando pode ser testada, não quando parece infalível.", "help": "No primeiro caso: A frase descreve ação, efeito esperado e mecanismo proposto. No segundo exemplo: Evidência contrária deve poder modificar a estratégia.", "challenges": [{"prompt": "Qual frase é uma hipótese de mudança?", "options": ["Vamos postar porque sim.", "Se documentarmos a falha e reunirmos os atingidos, esperamos uma resposta porque haverá uma demanda verificável.", "Vai dar certo com certeza."], "answer": 1, "feedback": "A frase descreve ação, efeito esperado e mecanismo proposto."}, {"prompt": "Como avaliar uma hipótese?", "options": ["Definir sinais de avanço e de necessidade de revisão.", "Contar apenas esforço.", "Ignorar resultados contrários."], "answer": 0, "feedback": "Evidência contrária deve poder modificar a estratégia."}], "application": "Escreva uma hipótese e o que indicaria que ela precisa mudar.", "requiresPractice": false, "resourceId": "estrategia"}'::jsonb);
insert into public.comun_learning_units values('primeiro-ciclo-estrategico','organizadores-r0','estrategia','mission',24,'Primeiro ciclo estratégico',1,'{"id": "primeiro-ciclo-estrategico", "number": "4.5", "title": "Primeiro ciclo estratégico", "track": "estrategia", "minutes": 8, "version": 1, "concept": "Um ciclo liga objetivo, hipótese, primeira ação, responsável, marco e data de revisão. Registre resultados e incertezas. A revisão permite mudar o caminho mantendo o compromisso com a mudança desejada.", "help": "No primeiro caso: O plano explicita o caminho e como será revisto. No segundo exemplo: A avaliação orienta uma adaptação fundamentada.", "challenges": [{"prompt": "Qual plano permite acompanhamento?", "options": ["Ação sem responsável.", "Objetivo, hipótese, ação, pessoa responsável, marco e revisão.", "Só uma previsão otimista."], "answer": 1, "feedback": "O plano explicita o caminho e como será revisto."}, {"prompt": "O primeiro marco não ocorreu. O próximo passo é:", "options": ["Revisar evidências, obstáculos e hipótese com o grupo.", "Declarar sucesso mesmo assim.", "Culpar quem questionou."], "answer": 0, "feedback": "A avaliação orienta uma adaptação fundamentada."}], "application": "Registre um ciclo na pauta, vinculando ação ou tarefa existente e uma data de revisão.", "requiresPractice": true, "resourceId": "estrategia"}'::jsonb);
insert into public.comun_learning_resources values('fundamentos','organizadores-r0','Ficha de problema e objetivo','{"id": "fundamentos", "title": "Ficha de problema e objetivo", "track": "fundamentos", "essential": "Registre o que sabemos e o que ainda precisa ser verificado.", "tool": ["Problema observável: o que acontece, onde e quando?", "Evidência disponível: qual registro sustenta a descrição?", "Lacunas: o que não sabemos?", "Objetivo: qual condição queremos mudar?", "Próxima pergunta: o que investigar primeiro?"], "sources": []}'::jsonb);
insert into public.comun_learning_resources values('investigacao','organizadores-r0','Checklist de fontes e pedido de informação','{"id": "investigacao", "title": "Checklist de fontes e pedido de informação", "track": "investigacao", "essential": "Toda afirmação precisa de uma fonte adequada e de um limite explícito.", "tool": ["Qual pergunta o registro responde?", "Quem produziu? Em que data e período?", "Onde está o original? Qual trecho e página?", "O que o registro demonstra? O que não demonstra?", "Pedido: solicito [registro] de [assunto], no período [datas], em formato disponível. Confira órgão e canal oficial."], "sources": [{"title": "Busca de pedidos e respostas — Fala.BR", "url": "https://buscalai.cgu.gov.br/"}, {"title": "Portal da Transparência do Governo Federal", "url": "https://portaldatransparencia.gov.br/"}]}'::jsonb);
insert into public.comun_learning_resources values('organizacao','organizadores-r0','Roteiro de conversa e facilitação','{"id": "organizacao", "title": "Roteiro de conversa e facilitação", "track": "organizacao", "essential": "Escute, faça um convite concreto e confirme o próximo passo.", "tool": ["Abertura: explique o propósito e combine o tempo.", "Escuta: como isso afeta sua rotina? O que gostaria de mudar?", "Convite: atividade, duração e contribuição possível.", "Reunião: resultado esperado, pauta e tempo de cada ponto.", "Fechamento: decisão, responsável, prazo e retorno."], "sources": []}'::jsonb);
insert into public.comun_learning_resources values('estrategia','organizadores-r0','Ficha do ciclo estratégico','{"id": "estrategia", "title": "Ficha do ciclo estratégico", "track": "estrategia", "essential": "Explicite o caminho esperado e como você saberá se precisa mudá-lo.", "tool": ["Objetivo observável.", "Quem decide, executa, influencia e vive o impacto?", "Recursos reais e obstáculos.", "Se fizermos X, esperamos Y, porque Z.", "Primeira ação, responsável e prazo.", "Marco de avaliação, sinais contrários e data de revisão."], "sources": []}'::jsonb);

alter table public.comun_learning_enrollments add column saved_resource_ids text[] not null default '{}';
create function public.comun_learning_bookmark(p_user_id uuid,p_resource_id text)
returns void language plpgsql security invoker set search_path=public,pg_temp as $$
declare resource public.comun_learning_resources; saved text[];
begin
 select * into resource from public.comun_learning_resources where id=p_resource_id;
 if resource.id is null then raise exception 'learning_invalid_resource'; end if;
 insert into public.comun_learning_enrollments(user_id,program_id) values(p_user_id,resource.program_id) on conflict do nothing;
 select saved_resource_ids into saved from public.comun_learning_enrollments where user_id=p_user_id and program_id=resource.program_id for update;
 update public.comun_learning_enrollments set saved_resource_ids=case when p_resource_id=any(saved) then array_remove(saved,p_resource_id) else array_append(saved,p_resource_id) end
 where user_id=p_user_id and program_id=resource.program_id;
end; $$;
revoke all on function public.comun_learning_bookmark(uuid,text) from public,anon,authenticated;
grant execute on function public.comun_learning_bookmark(uuid,text) to service_role;

commit;
