import AxeBuilder from "@axe-core/playwright";
import {readFileSync} from "node:fs";
import {rm,writeFile} from "node:fs/promises";
import {expect,test,type Browser,type Page} from "@playwright/test";
import {OPERATIONAL_SURFACES} from "../../lib/operational-surfaces";

const manifest=JSON.parse(readFileSync(".local/comun-auth/current.json","utf8")) as {itemId:string;personas:{persona:string;state:string}[]};
const stateFor=(persona:string)=>{const state=manifest.personas.find(entry=>entry.persona===persona)?.state;if(!state)throw new Error(`storageState ausente: ${persona}`);return state};
async function openPersona(browser:Browser,persona:string,path:string,viewport?:{width:number;height:number}){const context=await browser.newContext({storageState:stateFor(persona),viewport}),page=await context.newPage();await page.goto(path);return{context,page}}
async function assertAccessible(page:Page){await expect(page.getByLabel("E-mail")).toHaveCount(0);const result=await new AxeBuilder({page}).analyze();expect(result.violations.filter(({impact})=>impact==="serious"||impact==="critical")).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}
// O Chromium falha intermitentemente ao sobrescrever PNG recém-escrito no Windows
// (indexador/antivírus segura o arquivo). Captura em buffer e persiste via fs,
// que tolera o compartilhamento; o erro propaga se o bloqueio for real.
async function saveScreenshot(page:Page,path:string){const buffer=await page.screenshot({fullPage:true});await rm(path,{force:true});await writeFile(path,buffer)}
const surfacesByRole=Object.entries(Object.groupBy(OPERATIONAL_SURFACES.filter(({key})=>key!=="expired"),({role})=>role));

test("@a11y central e detalhe em todos os viewports",async({browser},info)=>{const{context,page}=await openPersona(browser,"operations_admin","/comun/admin/operacao",info.project.use.viewport as {width:number;height:number});try{await expect(page.getByRole("heading",{name:"Central operacional"})).toBeVisible();await assertAccessible(page);await page.goto(`/comun/admin/operacao/${manifest.itemId}`);await expect(page.getByRole("heading",{name:"Retirada urgente sintética"})).toBeVisible();await assertAccessible(page)}finally{await context.close()}});
test("@visual central e detalhe em todos os viewports",async({browser},info)=>{const{context,page}=await openPersona(browser,"operations_admin","/comun/admin/operacao",info.project.use.viewport as {width:number;height:number});try{await assertAccessible(page);await saveScreenshot(page,`reports/screenshots/sprint-33-2-1-central-${info.project.name}.png`);await page.goto(`/comun/admin/operacao/${manifest.itemId}`);await assertAccessible(page);await saveScreenshot(page,`reports/screenshots/sprint-33-2-1-detail-${info.project.name}.png`)}finally{await context.close()}});
test("@a11y superfícies especializadas com persona correta",async({browser},info)=>{if(!["360x800","1366x768"].includes(info.project.name))return;for(const[role,surfaces]of surfacesByRole){const{context,page}=await openPersona(browser,role,`/comun/admin/operacao/superficies/${surfaces![0].key}`,info.project.use.viewport as {width:number;height:number});try{for(const surface of surfaces!){await page.goto(`/comun/admin/operacao/superficies/${surface.key}`);await expect(page.getByRole("heading",{name:surface.title})).toBeVisible();await assertAccessible(page)}}finally{await context.close()}}});
test("@visual superfícies especializadas com persona correta",async({browser},info)=>{if(!["360x800","1366x768"].includes(info.project.name))return;for(const[role,surfaces]of surfacesByRole){const{context,page}=await openPersona(browser,role,`/comun/admin/operacao/superficies/${surfaces![0].key}`,info.project.use.viewport as {width:number;height:number});try{for(const surface of surfaces!){await page.goto(`/comun/admin/operacao/superficies/${surface.key}`);await assertAccessible(page);await saveScreenshot(page,`reports/screenshots/sprint-33-2-1-${surface.key}-${info.project.name}.png`)}}finally{await context.close()}}});
test("@a11y @visual sessão expirada não revela superfície protegida",async({browser},info)=>{if(!["360x800","1366x768"].includes(info.project.name))return;const{context,page}=await openPersona(browser,"operations_admin","/comun/admin/operacao",info.project.use.viewport as {width:number;height:number});try{await context.clearCookies();await page.goto("/comun/admin/operacao/superficies/expired");await expect(page).toHaveURL(/\/comun\/admin\/login/);expect(await page.content()).not.toContain("Item fixture");const result=await new AxeBuilder({page}).analyze();expect(result.violations.filter(({impact})=>impact==="serious"||impact==="critical")).toEqual([]);await saveScreenshot(page,`reports/screenshots/sprint-33-2-1-expired-${info.project.name}.png`)}finally{await context.close()}});
